classes/controllers/FrmStylesController.php

I noticed this while testing.
The `output_vars` function expects that `$defaults` is an array. But `false` is getting passed here.
It throws a warning on this code:
```
if ( ! isset( $defaults[ $var ] ) ) {
$defaults[ $var ] = '';
}
```
> PHP Deprecated:  Automatic conversion of false to array is deprecated in /var/www/src/wp-content/plugins/formidable/classes/helpers/FrmStylesHelper.php on line 313

Avoid automatic conversion of false to array when saving styles

---

.github/workflows/phpcs.yml
classes/controllers/FrmAppController.php
classes/helpers/FrmAppHelper.php
classes/views/shared/admin-footer-links.php

This PR makes sure that the Floating and Footer Links in the admin panel match the chosen brand name. If the brand isn't 'formidable', Floating links won't be shown, and social media and docs links in the Footer Links will be turned off.
[QA link for testing](https://qa.formidableforms.com/sherv/wp-admin/admin.php?page=formidable-settings&t=white_label_settings)
[White labeling needs to comply in the backend](https://github.com/Strategy11/formidable-pro/issues/4058)
1. Go to `WP Admin > Formidable > Global Settings > White Labeling`.
2. If the brand name set under `Plugin Label` isn't `formidable`, make sure Floating links are not shown.
3. Check that the Footer Links show the correct brand name from the 'Plugin Label'.
4. See that social media and docs links in the Footer Links are off …

Enhanced Compliance with White Labeling Settings in Admin Floating and Footer Links

---

css/frm_admin.css

The whitelabel setting is used in the name so `.formidable_page_formidable-payments` may not exist,

Update the payments page selector for modal overlay

---

css/frm_admin.css

Fix https://github.com/Strategy11/formidable-pro/issues/4417
- Add code snippet to show admin menu
- Add an HTML field to a form and try going full screen

Override tinymce full screen position when admin sidebar is shown

---

stripe/controllers/FrmStrpLiteAppController.php
stubs.php

Related ticket https://secure.helpscout.net/conversation/2359769162/173015
The issue is that I'm only checking the one option name. Not the one for PayPal.
To patch this, here's a snippet:
```
if ( false === get_option( 'frm_trans_db_version' ) ) {
update_option( 'frm_trans_db_version', 0 );
}
```

Stop redirecting to Stripe settings when PayPal migrations have run

---

stripe/controllers/FrmTransLiteActionsController.php
stripe/models/FrmTransLiteAction.php

These checks were copied from the Stripe plugin and are not necessary anymore as they exist in this repo.

Remove `is_callable` checks from Stripe code where functions exist in Lite

---

classes/models/FrmFieldFormHtml.php

Related ticket https://secure.helpscout.net/conversation/2369627291/173981/
I had added this with https://github.com/Strategy11/formidable-forms/pull/1252
To be consistent with our update here https://github.com/Strategy11/formidable-pro/pull/4249
Here's a related stack overflow question I found https://stackoverflow.com/questions/36776126/whats-an-accessible-way-to-group-items-within-a-radiogroup-html5-wai-aria
The top answer there agrees with the ticket,
> So suggest using role=group and removing the tabindex=0 as the div container isn't itself an interactive object and should not be in the focus order:

Remove tabindex from radio button groups

---

classes/models/FrmPluginSearch.php

Fix https://github.com/Strategy11/formidable-pro/issues/4407
I tried to make sure all search terms are found in the terms for an addon before it is matched when searching for a plugin.
1. Go to the Plugins -> Add New and search for "Download monitor"
2. Our Campaign monitor plugin should not show up in the result
3. Do another search with "Campaign monitor" and our "Campaign monitor" should show up
Basically, you should not see any of our plugins in the search suggestion unless all of the terms in the addon name are found in the query term.
This is the suggestion we are talking about in the search result.

Make sure all search terms are found in addon terms during plugin search

---

classes/helpers/FrmAppHelper.php

Just updating this since I missed this one. I don't usually check for a format like 6.4.x.

Update since version

---

classes/controllers/FrmAppController.php
css/frm_admin.css

Related ticket https://secure.helpscout.net/conversation/2374651794/174477/
I'm always hiding the gateway field. But I shouldn't if the payments submodule is active.

Stop hiding the gateway field when the payments submodule is active

---

classes/models/FrmHoneypot.php
css/custom_theme.css.php
css/frm_grids.css
js/formidable.js

Fixes https://github.com/Strategy11/formidable-wpml/issues/104 by changing how the Honeypot is hidden using overflow style rules and a 0 size.
I also made the honeypot more difficult to predict, giving it a randomly generated class/name value.

Hide honeypot using overflow and randomize class and name

---

css/custom_theme.css.php

Fixes https://secure.helpscout.net/conversation/2381207070/175134/
This can be patched as well with `div[class^="frm__"] { position: absolute; }`

Fix honeypot causes inline submit button to break to a new line

---

classes/controllers/FrmAppController.php

Related ticket https://secure.helpscout.net/conversation/2382420517/175264
This shouldn't really be possible, but I've seen errors like this come up that seem to happen when updating the plugin, when some code has loaded and other code hasn't.
> Error Message: Uncaught Error: Class 'FrmOverlayController' not found
> File Path: .../plugins/formidable/classes/controllers/FrmAppController.php

Check that overlay controller exists just in case

---

classes/helpers/FrmAppHelper.php

**Related tickets**
https://secure.helpscout.net/conversation/1567213496/76049/
https://secure.helpscout.net/conversation/1763132632/90276
> Fatal error: [snuffleupagus][disabled_function] Aborted execution on call of the function 'include_once' in .../wp-content/plugins/formidable/classes/helpers/FrmAppHelper.php on line 1025
When the Snuffleupagus PHP security module is active (https://snuffleupagus.readthedocs.io/), `include` and `include_all` only work with PHP files. Other file types result in a fatal error.
Because of this rule,
`sp.disable_function.function("include_once").value_r("\.(inc|phtml|php)$").allow();`
Using `readfile` instead should fix this.

Avoid a fatal error when using the Snuffleupagus security module

---

classes/controllers/FrmAppController.php
stripe/controllers/FrmTransLitePaymentsController.php
stripe/helpers/FrmTransLiteAppHelper.php

Related ticket https://secure.helpscout.net/conversation/2389539238/175949/
> WordPress database error Table 'wp_frm_subscriptions' doesn't exist for query SELECT COUNT(*) FROM wp_frm_subscriptions made by do_action('forms_page_formidable-payments'), WP_Hook->do_action, WP_Hook->apply_filters, FrmTransLitePaymentsController::route, FrmTransLiteListsController::route, FrmTransLiteListsController::display_list, include('/plugins/formidable/stripe/views/lists/list.php'), FrmListHelper->views, FrmTransLiteListHelper->get_views, FrmTransLiteDb->get_count [12-Oct-2023 14:55:13 UTC] PHP Warning: Undefined property: stdClass::$status in ../wp-content/plugins/formidable/stripe/helpers/FrmTransLiteAppHelper.php on line 74
The problem here is that PayPal only has the one payments table, not a …

Stop using the Stripe Lite payments table when only PayPal has migrated

---

classes/views/frm-entries/list.php

Fixes https://github.com/Strategy11/formidable-pro/issues/3395
The "Add New" button on the entries list would appear for users who don't have the permissions to create entries.
This button logic was moved here with the v6.0 update. But I tried v5.5.7, and the button appears then as well so this is an old issue.

Stop showing the add new entry button without permissions to add entries

---

stripe/controllers/FrmTransLiteActionsController.php

This is the same update as https://github.com/Strategy11/formidable-payments/pull/71 but for Stripe Lite.

Add payment refunded action event trigger type

---

classes/controllers/FrmAddonsController.php
js/formidable.js

Fixes https://github.com/Strategy11/formidable-pro/issues/4485
These permission checks don't appear to be necessary.
The function `can_install_addon_api` is called from our API, so the user is not logged in and doesn't have this permission. Instead the token is verified using `hash_equals` against the DB record.
The `install_addon` function is called in one function only, `download_and_activate`.
`download_and_activate` is only called when the API token is valid, or via `ajax_install_addon` which goes through `install_addon_permissions` which handles the permission check, so this permission check happens twice.

Remove extra permission checks that break API

---

classes/models/FrmHoneypot.php

This update applies the same solution that's applied to the honeypot input to the label.
When form styling is disabled, it adds an inline `style="display:none;"` style.

Use FrmFormsHelper::maybe_hide_inline on honeypot label too

---

classes/helpers/FrmAppHelper.php

Related issue https://github.com/Strategy11/formidable-pro/issues/3591
Related pull request https://github.com/Strategy11/formidable-pro/pull/4490
The View permission removed from lite to be handled conditionally in pro.

Remove unconditional view permission set from global settings

---

classes/models/FrmHoneypot.php

The honeypot is showing up too often.
I think part of the issue is that it's getting generated too often.
This update stops generating it, once it's been generated once.
This way it is at least not always the same for every customer.
But also works better with caching.

Stop generating a honeypot class name so often

---

js/formidable_admin.js

This PR fixes the issue where the "Add Fields Here" message was not displaying after all form fields were deleted.
["Add Fields Here" Message Not Displaying After Deleting All Fields](https://github.com/Strategy11/formidable-pro/issues/4509)
https://qa.formidableforms.com/sherv10/wp-admin/admin.php?page=formidable&frm_action=edit&id=1
1. Go to the form builder
2. Delete all form fields
3. Verify that the "Add Fields Here" message displays correctly

Fix: Display "Add Fields Here" Message After Deleting All Fields

---

css/custom_theme.css.php

This PR resolves the vertical centering issue of dropdown arrows across all supported themes.
[Only try to vertically center dropdown arrows for certain themes](https://github.com/Strategy11/formidable-pro/issues/4066)
https://qa.formidableforms.com/sherv7/wp-admin/admin-ajax.php?action=frm_forms_preview&form=fixverticalcenteringofdropdownarrows&theme=1
1. Activate any supported theme (Ex: Astra, Default Themes).
2. Navigate to `WP Admin > Formidable > Forms`.
3. Open an existing form or create a new form.
4. Add a dropdown field.
5. Verify that the dropdown arrow is vertically centered.

Fix Vertical Centering of Dropdown Arrows for All Themes

---

classes/helpers/FrmAppHelper.php
tests/misc/test_FrmAppHelper.php

Fixes https://github.com/Strategy11/formidable-pro/issues/3811
I chose some hard coded values here.
If the length is 50 characters over what it should be, and I can't detect any spaces, then I truncate at the limit + 10.
**Before**
**After**

Force truncate for strings way over the limit with no spaces

---

js/formidable.js

I noticed this JS error with geolocation fields.
I'm just adding a check so this doesn't trigger an error.

Check select option before check hasClass

---

classes/models/FrmDb.php

I was looking at database queries while working on a ticket.
I noticed this query,
> SELECT e.id,e.created_at as meta_value
> FROM wp_frm_items e
> WHERE e.form_id=751
> AND e.is_draft=0
> AND DATE_FORMAT(e.created_at, '%Y-%m-%d %H:%i:%s') >='2023-10-03 00:00:00'
> AND DATE_FORMAT(e.created_at, '%Y-%m-%d %H:%i:%s') <='2023-11-03 23:59:59'
This `DATE_FORMAT` seems excessive. It's converting it from `Y-m-d H:i:s` to `Y-m-d H:i:s`.
If I for example run `SELECT * FROM wp_frm_items e WHERE e.created_at != DATE_FORMAT(e.created_at, '%Y-%m-%d %H:%i:%s')`, I get 0 results.
Removing this optimizes the query.
There are 2 queries that use this running on my reports page. They take `0.2732` and `0.2511` seconds.
With this PR, they took 0.1549 and 0.1555 seconds. 0.5243, saving ~.21 seconds.
I tried …

Stop using DATE FORMAT on created_at/updated_at queries

---

css/frm_admin.css

This ID is hard coded in the `FrmSolution.php` file.
The style is used for these icons,
Without the margin, it looks like this.
I've added `#frm-new-template` in front of this so it only happens on `FrmSolution.php` pages like the Directory page here.
**Before**
**After**

Apply margin to image option containers in #frm-new-template page

---

js/formidable.js

FIxes https://strategy11.slack.com/archives/C799A2R61/p1699553137716059
This update resets the submit button when the bfcache is triggered on back button press.

Enable submit button on bf cache

---

classes/views/frm-fields/front-end/combo-field/combo-field.php

Fix https://github.com/Strategy11/formidable-pro/issues/4323
`data-frmval` was missing from name field inputs when a default value is set and that caused issue which is fixed by this update.

Output data-frmval for name fields

---

classes/views/frm-fields/front-end/checkbox-field.php

I accidentally removed this in https://github.com/Strategy11/formidable-forms/pull/1372/files
It was causing a unit test in Pro to break.

Fix accidentally removed checkbox hook

---

tests/base/FrmAjaxUnitTest.php
tests/misc/test_FrmOverlayController.php

Related issue https://github.com/Strategy11/formidable-pro/issues/4282
This fixes this deprecated message
> PHP Deprecated: Creation of dynamic property test_FrmProFieldsAjax::$53 is deprecated in ...plugins/formidable/tests/base/FrmAjaxUnitTest.php on line 44
I also made an update to fix a message when the LIte unit tests run
> Deprecated: Creation of dynamic property test_FrmOverlayController::$time_mock is deprecated in .../plugins/formidable/tests/misc/test_FrmOverlayController.php on line 7

Fix deprecated phpunit message

---

classes/views/applications/header.php
classes/views/shared/admin-header.php

This update adds screen reader text for the header logo link.
This fixes an issue caught by the axe DevTools extension.
"Links must have discernible text"

Add view forms screen reader text for header logo

---

classes/helpers/FrmCurrencyHelper.php

I noticed this `Undefined array key "usd"` warning when looking at a manually entered payment.
The index key is `USD`, not `usd`. This just fixes the case.

Fix fallback currency in wrong case

---

stripe/controllers/FrmTransLiteEntriesController.php
stripe/controllers/FrmTransLiteListsController.php

Fixes https://github.com/Strategy11/formidable-pro/issues/4476
I also added a check to fix https://secure.helpscout.net/conversation/2426376840/179938
> Warning: Undefined property: stdClass::$sub_id in .../plugins/formidable-paypal/helpers/FrmPaymentsListHelper.php on line 172
> Warning:  Undefined property: stdClass::$status in .../plugins/formidable-paypal/helpers/FrmPaymentsListHelper.php on line 172

Add more PayPall fallback checks

---

classes/views/frm-forms/add_field.php
js/formidable_admin.js

When using axe DevTools (https://chromewebstore.google.com/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?pli=1), the "More Options" toggles have an accessibility error, "Links must have discernible text".
This update adds screen reader text ("Toggle More Options Dropdown") to the toggles, fixing the issue.
I also refactored a bit, using more `frmDom` functions.
_There's still one instance of this error coming from the header logo. I'm working on that separately. I'm trying to determine the best text to use there still._

Add screen reader text for more options dropdown toggles

---

classes/controllers/FrmAppController.php
stripe/controllers/FrmTransLitePaymentsController.php
stripe/helpers/FrmTransLiteListHelper.php
stripe/views/lists/list.php

Related ticket https://secure.helpscout.net/conversation/2428049678/180141/
We only show the "Edit" link when the Stripe add on is active.
But this means that the "Edit" link isn't displayed when the PayPal add on is active and we're using the Stripe Lite view (which happens if Stripe migrations have run).

Add edit link to payments table when paypal is active

---

classes/helpers/FrmAppHelper.php
classes/models/FrmMigrate.php

Related update https://github.com/Strategy11/formidable-pro/pull/4540#pullrequestreview-1730324322
This moves the indexes into Lite so database queries are optimized for all sites.
I run this after it creates the tables so it always runs. I tried getting it to work in the `dbDelta` call but I don't believe that's supported for this kind of index.

Add composite indexes for entries tables

---

classes/models/FrmHoneypot.php

Related ticket https://secure.helpscout.net/conversation/2430174033/180445/
The `aria-hidden="true"` attribute causes issues with Google PageSight. It also makes the honeypot more obvious. We're better off removing it.
Since nothing in the honeypot container should be tabbable, it shouldn't cause many issues with screen readers.

Remove aria hidden from honeypot container

---

classes/helpers/FrmFieldsHelper.php
classes/views/frm-fields/front-end/checkbox-field.php

Fix https://github.com/Strategy11/formidable-pro/issues/4578 together with https://github.com/Strategy11/formidable-pro/pull/4584
I believe this fix would ideally be in Pro but since most of the stuff is built into Lite, I'm just updating lite.
Fixes in this update:
- Checked state of other option on front end page load.
https://github.com/Strategy11/formidable-forms/assets/41271840/e652528c-94ab-45dd-adbe-0922763d0ffc

Fix how 'other' option checked state is determined

---

css/frm_admin.css

Fix https://github.com/Strategy11/formidable-pro/issues/4362
**Before:**
**After:**

Fix Pirate forms importer style

---

classes/controllers/FrmAppController.php
css/frm_admin.css

Fixes https://github.com/Strategy11/formidable-pro/issues/4464
To replicate Kristine's issue, you can use this snippet:
```
global $_updated_user_settings;
$_updated_user_settings['unfold'] = true;
```
Basically she has the "unfold" user setting on. I'm not totally sure how this gets set though.
This update adds a new `frm-unfold` class when this `unfold` setting is on (so `auto-fold` is never added) and that the `mfold` user preference is not set to `f` which adds the `folded`.
Maybe this is complicating it though. May we just want to not check for the `.auto-fold` class and always set `left: 160px;` by default?

Add left styling rule when auto fold class is not set on body

---

classes/controllers/FrmAddonsController.php

Fixes https://github.com/Strategy11/formidable-forms/issues/1405
The welcome page passes `views-info` for the upgrade link args. The function was setting an array key, which causes issues when the variable isn't an array.
This update sets it to an array. By the time `FrmAppHelper::admin_upgrade_link` is called, we no longer need the `medium` value being passed in `$upgrade_link_args`. If it's a string, it's fine to set it to an empty array.
The next line sets the link as before, now with an array value.

Support string $upgrade_link_args in FrmAddonsController::conditional_action_button

---

classes/models/FrmEntry.php

I noticed this while testing the dashboard.
This is the database query
```
SELECT COUNT(*)
FROM wp_frm_items it
LEFT OUTER JOIN wp_frm_forms fr
ON it.form_id=fr.id
WHERE parent_form_id IS NULL
OR parent_form_id <=1
LIMIT 1
```
This query takes `0.1478` seconds.
Within the `LEFT OUTER JOIN`, using a `INNER JOIN` but omitting the word `INNER` since it's the default,
```
SELECT COUNT(*)
FROM wp_frm_items it
JOIN wp_frm_forms fr
ON it.form_id=fr.id
WHERE parent_form_id IS NULL
OR parent_form_id <=1
LIMIT 1
```
This query takes `0.0368` seconds.
It is 4 times faster in my Query Monitor times.
If I simply run this in my SQL browser it goes from 193ms to to 80ms, still about 2.4 times faster.
The `OUTER JOIN` is really slow.
Changing this means that the entry count will no longer include deleted …

Optimize the join for record count query

---

classes/models/FrmField.php
classes/views/frm-fields/back-end/settings.php

Fixes https://github.com/Strategy11/formidable-pro/issues/3967
Here's a basic snippet to simulate something similar to the issue from this ticket https://github.com/Strategy11/formidable-pro/issues/3967#issuecomment-1850615714
When any `$_POST` data includes the word "select", this will force a redirect to a 404 page.
```
foreach ( $_POST as $key => $value ) {
if ( false !== strpos( $value, 'select' ) ) {
wp_redirect( site_url() . '/404-page' );
die();
}
}
```
I tested this fix out as a beta on the customer's website, and it fixes the issue with their security plugin blocking saving a dropdown "select" field.
@stephywells What do you think? Is there anything else I'd need to do here to cover this?

Pro issue 3967

---

css/frm_admin.css

This PR addresses a styling issue identified in [#4210](https://github.com/Strategy11/formidable-pro/issues/4210), which is particularly noticeable when the bottom row of the "View entry" tables has a darker zebra stripe. The problem involves the table corners appearing improperly due to the overlap of background colors on the table's `border-radius` styling.
https://qa.formidableforms.com/sherv/wp-admin/admin.php?page=formidable-entries&frm_action=show&id=2&form=53
[View entry table corners look bad #4210](https://github.com/Strategy11/formidable-pro/issues/4210)
1. Go to the "View entry" page within the Formidable Forms.
2. Check tables with zebra striping, especially those where the bottom row has a darker stripe.
3. Confirm that the table corners now render cleanly, with no background …

Resolve Zebra Stripe Styling Issue on Bottom Row of View Entry Tables - Issue #4210

---

classes/controllers/FrmFormTemplatesController.php

This PR addresses the issue reported in [#4640](https://github.com/Strategy11/formidable-pro/issues/4640), where warnings were logged due to the failure in including `modal.php` in `FrmFormTemplatesController.php`. The modification involves moving `self::init_template_resources();` to the `load_admin_hooks` method. This ensures the correct initialization and inclusion of `modal.php`, thereby resolving the warning during plugin upload on the QA site.
[#4640](https://github.com/Strategy11/formidable-pro/issues/4640)

Fix Warning for modal.php Inclusion in Form Templates on QA Upload

---

classes/helpers/FrmAppHelper.php

This is to make it less ambiguous since anyone can "view a form" on the front end to preview it.
I'm just renaming `View Forms` to `View Forms List`,

Rename view forms permission

---

classes/controllers/FrmAppController.php
classes/controllers/FrmFormsController.php

Fix https://github.com/Strategy11/formidable-pro/issues/3184
Removing `delete_all` from the query args and redirecting to the resulting url fixes this issues like similar issues that used the same fix.
1. Trash some forms, go to the 'Trash' tab from the form list page and then use the 'Empty Trash' button to permanently delete them.
2. Leave that tab as it is and trash more forms in a new tab.
3. Get back to the previous tab and refresh the page
4. Confirm that the forms deleted in step 2 are not deleted from trash

Avoid permanent deletion of forms from trash list on page refresh after emptying the trash

---

classes/views/frm-fields/back-end/settings.php
classes/views/frm-forms/add_field_links.php
css/frm_admin.css

Toggle field label (add spacing)
Before:
After:
Field options heading
Before:
After:

Fix a couple admin spacing issues

---

css/custom_theme.css.php

Related PR https://github.com/Strategy11/formidable-pro/pull/4635
This update adds some basic styling rules for the slim select element, like borders, to make it more consistent with other Formidable fields.

Add slimselect to basic field style settings

---

css/frm_admin.css

This PR resolves the display issue of column checkboxes in the Form Entries on iPads in landscape mode, ensuring they are responsive and display correctly on all devices.
[Issue #2567](https://github.com/Strategy11/formidable-pro/issues/2567)
https://qa.formidableforms.com/sherv13/wp-admin/admin.php?page=formidable-entries&frm_action=list&form=30
1. Go to `WP Admin > Formidable > Entries`.
2. Use an iPad in landscape mode to view the page.
3. Check that the column checkboxes are displaying correctly.

Fix Column Checkboxes on Form Entries for iPad Landscape

---

js/formidable_admin.js

Related issue https://github.com/Strategy11/formidable-pro/issues/4329
Requires https://github.com/Strategy11/formidable-pro/pull/4639 to actually fix the issue.
Switching a Product field type from User defined to Checkbox triggers this error below and this PR fixes that.

Fix js Error when switching Product field type

---

classes/controllers/FrmFormsController.php
classes/views/frm-forms/preview/footer.php
classes/views/frm-forms/preview/header.php

Fix https://github.com/Strategy11/formidable-pro/issues/4478
We can know whether calling functions `get_header` and `get_footer` would cause deprecation warnings ahead of time and avoid it if so. We can instead copy pieces of code from core to call relevant functions and output html fragments required.
Preview a form in theme and check the error log for deprecation warnings.
> PHP Deprecated: File Theme without header.php is deprecated since version 3.0.0 with no alternative available. Please include a header.php template in your theme. in /var/www/src/wp-includes/functions.php on line 5646
> PHP Deprecated: str_replace(): Passing null to parameter https://github.com/Strategy11/formidable-pro/issues/3 ($subject) of type array|string is deprecated in …

Avoid deprecation warnings when calling template functions

---

stripe/models/FrmTransLitePayment.php

If you haven't connected Stripe Connect, and you're not using PayPal, the table may not exist at all.
I missed that we weren't checking that during review.
Related ticket https://wordpress.org/support/topic/database-errors-from-scheduled-frmemailsummaryhelper/

Avoid a db error when getting payments stats

---

classes/views/frm-form-actions/_email_settings.php
css/frm_admin.css

This PR addresses the layout issue reported in [Issue #4673](https://github.com/Strategy11/formidable-pro/issues/4673), concerning the misplacement of the CC, BCC, and From fields in the email settings. The objective is to realign these fields for better user experience and interface consistency.
https://qa.formidableforms.com/sherv/wp-admin/admin.php?page=formidable&frm_action=settings&id=53
[Email settings for cc, bcc, and from are out of place #4673](https://github.com/Strategy11/formidable-pro/issues/4673)
1. Navigate to `WP Admin > Formidable > Forms`.
2. Open an existing form or create a new one and go to its settings.
3. Navigate to `Actions & Notifications > Email Notification`.
4. Verify that the CC, BCC, and From fields are correctly aligned with the "To" field, reflecting the …

Fix Layout for Email Settings: CC, BCC, and From Fields

---

changelog.txt
classes/helpers/FrmAppHelper.php
classes/helpers/FrmFormsHelper.php
formidable.php
languages/formidable.pot
phpstan.neon
readme.txt

Related Slack conversation https://strategy11.slack.com/archives/C799A2R61/p1704452914859179
Custom styles cannot be disabled because this `isset` was changed to a `! empty`.
We need to support "0" as well.
This was introduced with https://github.com/Strategy11/formidable-forms/pull/1415

Fix issue with toggling styles for form

---

classes/views/frm-forms/settings-buttons.php
classes/views/styles/_styles-list.php

Related ticket https://secure.helpscout.net/conversation/2472223781/185414/
It looks like the "Manage Styling" global settings section is saving "Styling disabled" as a empty string.
The check for this toggle was too strict, checking only for `'0'`. Now I do an `(int)` conversion first and check for `0`.
I also noticed that I forgot to remove the styling description from the Buttons section which no longer has styling settings. So I removed the styling part of the description,

Fix styling toggle appears enabled when disabled from global settings

---

css/frm_admin.css

This PR addresses the issue where the "View Payment" page appears blank in Lite v6.7.
[Issue #4710 - "View Payment" page is blank as of Lite v6.7](https://github.com/Strategy11/formidable-pro/issues/4710)
https://qa.formidableforms.com/sherv/wp-admin/admin.php?page=formidable-payments&action=show&id=1&type
1. Navigate to `WP Admin > Formidable > Payments`.
2. Click on any payment to view its details.
3. Verify that the "View Payment" page now displays the content correctly.

Fix for Blank "View Payment" Page

---

classes/controllers/FrmAddonsController.php
classes/models/FrmFormState.php
classes/models/FrmSettings.php

I'm going through a list of autoload options, and removing what isn't needed on every page.
Also, the settings are duplicated in the autoloading with both the transient and the option. This PR simplifies and optimizes getting the global settings. I'm not seeing a good reason to muddy this up with an extra transient when the option is being auto loaded.
@Crabcyborg do you see any possible issues with this?

Switch a few options to not autoload for performance

---

classes/helpers/FrmAppHelper.php
classes/views/styles/_style-card.php
css/admin/applications.css
css/admin/frm_admin_global.css
css/frm_admin.css
js/admin/applications.js

I missed this one the first time around. The "New" tag is also green now.
Before:
After:
I had to make a few changes to the application list so this would fit. We'll need to circle back to this later to match the template page better since this isn't ideal.

Update frm-new-pill to match tags

---

classes/helpers/FrmAppHelper.php

Related Slack conversation https://strategy11.slack.com/archives/CJFQ599V5/p1705053738151109
There isn't really any harm in allowing list tags: `ul`, `ol,` and `li`.
So I'm adding those to the list of tags that are allowed by default.

Stop stripping list tags from form input HTML

---

classes/models/fields/FrmFieldType.php

Related comment https://github.com/Strategy11/formidable-pro/issues/4647#issuecomment-1892513008
I'm bumping up the `updated_by` check. If it's set, the permission check only checks the `updated_by` user's permissions.
This means that old entry data submitted by untrusted users that wasn't sanitized in the past (in older versions prior to v6.7.1) won't be sanitized with the additional strict filtering on display if the entry was updated by a privileged user that may not have noticed an unsafe anchor tag or img, but that's pretty low risk.

Stop sanitizing on display if updated by user is privileged

---

css/frm_admin.css

This PR rectifies the overlapping issue in search boxes across various places
[Some search boxes are overlapping #4693](https://github.com/Strategy11/formidable-pro/issues/4693)
To ensure the overlapping issue is resolved, please follow these steps:
1. **Application Item Search:**
- Go to an existing Application.
- Click on the "Add Item" button.
- Select "Existing forms/views/pages".
- Observe the "Search Items" search box.
2. **View Name Search:**
- Navigate to any View.
- Click on the name of the View.
- Check the "Search views" search box.
3. **Advanced Tab Search in View Editor:**
- Open any View and click on a column in the editor.
- In the sidebar, go to the "Advanced" tab.
- Look for the search box here.
https://qa.formidableforms.com/sherv3/wp-admin/term.php?taxonomy=frm_applicati …

Resolve Overlapping Search Boxes Issue

---

js/admin/dom.js

Fixes https://github.com/Strategy11/formidable-pro/issues/4717
I think this is because the cleaning happens now more than once, to clean nested HTML as well.
The error is because there are `svg` elements here with no `use` children. The svg has no child at all.
The cause is because the svg used on the option itself is getting sanitized multiple times and uses an inconsistent `xlink:href`/`href` value.
Now I check for both values just in case one fails.
This code worked on the assumption an `svg` always had this child. I've updated it to not break in that case either.

Fix pro issue 4717 / Check svg has a use child when cleaning HTML

---

classes/helpers/FrmStylesHelper.php

Related ticket https://secure.helpscout.net/conversation/2474621653/185651/
This update stops prepending a `#` in front of an HSL color.
Trying to get an HSL colour to work with `wpColorPicker` however doesn't appear to be supported. It looks like it's supported by the underlying iris library (https://automattic.github.io/Iris/) but when I tried changing to iris I wasn't having much luck with HSL colours either.

Stop prepending # in front of HSL colors

---

classes/helpers/FrmStylesHelper.php

Following up from https://github.com/Strategy11/formidable-forms/pull/1472
There are other types of colors too.
This adds checks for `hsla` and `hwb` as well.
https://developer.mozilla.org/en-US/docs/Web/CSS/color

Stop prepending # in front of hsla hwb

---

classes/views/xml/import_form.php
css/frm_admin.css

This PR resolves the issue where the 'Entries' checkbox appeared for XML exports in Formidable Lite, despite being non-functional. Now, the 'Entries' option is hidden when XML is selected in Lite mode, aligning with the expected behavior.
https://qa.formidableforms.com/sherv2/wp-admin/admin.php?page=formidable-import
[#4709 - Stop showing "Entries" as an XML export option when Pro is inactive](https://github.com/Strategy11/formidable-pro/issues/4709)
1. Disable Pro.
2. Go to `WP Admin > Formidable > Import/Export`.
3. Verify that the 'Entries' checkbox is not visible for XML export.

Fix: Hide 'Entries' for XML Export in Lite Mode (#4709)

---

classes/helpers/FrmStylesHelper.php
tests/styles/test_FrmStylesHelper.php

Following up from https://github.com/Strategy11/formidable-forms/pull/1472
I was seeing this error when I tried to use an HSL color
> PHP Deprecated:  Invalid characters passed for attempted conversion, these have been ignored in /var/www/src/wp-content/plugins/formidable/classes/helpers/FrmStylesHelper.php on line 275

Add unit tests for color brightness and add support for hsl to hex

---

js/admin/style.js

Fixes https://github.com/Strategy11/formidable-pro/issues/4725
I can only replicate this in Chrome on Toyin's account.
The Lite placeholder options is added because Pro isn't hooking into the `frm_style_card_dropdown_options` filter yet.
It needs a little bit more time. Changing this from `0` to `1` seems to fix the issue. It's tough to actually try waiting for Pro as well since Pro may not exist at all either.

Pro issue 4725 / Delay adding hamburger menus by 1ms

---

classes/views/shared/reports-info.php
js/formidable_admin.js

This PR addresses the issue where support footer links are not correctly positioned on the "lite-reports" page (#4714). Currently, these links appear at the top of the page, above the content, and move up and down when scrolling, rather than staying in a fixed position.
https://qa.formidableforms.com/sherv/wp-admin/admin.php?page=formidable&frm_action=lite-reports&form=1162
[Support footer links don't appear in the right place on the "lite-reports" page](https://github.com/Strategy11/formidable-pro/issues/4714)
To reproduce this issue:
1. Disable Pro.
2. Go to a form with entries.
3. Click on the greyed-out "Reports" tab.
- Example URL: `https://example.com/wp-admin/admin.php?page=formidable&frm_action=lite-reports&form=1162`
This PR includes adjustments to ensure the support footer links …

Fix: Correct Placement of Support Footer Links on Lite-Reports Page

---

js/formidable_admin.js

Related issue https://github.com/Strategy11/formidable-pro/issues/4706
The logic is all in Pro, but this hook is required.

Add new JS hook frm_after_authorize

---

classes/controllers/FrmFieldsController.php
classes/controllers/FrmFormsController.php
classes/helpers/FrmFieldsHelper.php
classes/models/fields/FrmFieldType.php
classes/views/frm-fields/back-end/settings.php
classes/views/frm-forms/add_field.php
classes/views/frm-forms/add_field_links.php
classes/views/frm-forms/edit.php
js/formidable_admin.js
tests/fields/test_FrmFieldType.php
tests/fields/test_FrmFieldsController.php
tests/fields/test_FrmFieldsHelper.php

Fixes https://github.com/Strategy11/formidable-pro/issues/4713
I cannot reliably delete the draft fields. The only event listener (that isn't deprecated) that gets triggered when leaving the page is `beforeunload` which is cancellable (with no way of knowing if it was cancelled or not) which doesn't make it a reliable event to try deleting drafts from as they would get deleted when you cancel because of unsaved changes.
And if we delete on form builder load there is a risk of deleting another user's draft fields that they are working on, so I'm not deleting fields due to the possible bugs that could occur from deleting fields that shouldn't be deleted.
This update adds a new `draft_fields` input to the page that stores a CSV of all draft field IDs. This allows us to cross-reference this …

Pro issue 4713 / Add a draft flag to new fields and hide them from the front end except for on preview

---

js/formidable_admin.js

I noticed this while working on fixing https://github.com/Strategy11/formidable-pro/issues/1644
Too many calls to `handleFieldDrop` were causing issues.
I believe this has some impact on performance on a large form.
I merged this branch with https://github.com/Strategy11/formidable-forms/pull/1467 in another branch (https://github.com/Strategy11/formidable-forms/compare/combined_performance_updates?expand=1).
My update may not make a large difference, but it may be worth trying to test these together using the `combined_performance_updates` branch to see if this update helps make https://github.com/Strategy11/formidable-forms/pull/1467 feel any more snappy.

Stop triggering drop field functions multiple times

---

classes/helpers/FrmFormsListHelper.php

Fix https://github.com/Strategy11/formidable-pro/issues/4577
Just adding a label to checkboxes in form list that would announce 'Select {form_name}" when checkboxes are selected.

Add label to form list checkboxes

---

classes/helpers/FrmAppHelper.php
classes/helpers/FrmEmailSummaryHelper.php
classes/views/frm-settings/misc.php

- Show a message with link to disable summary emails in profile for Elite and Business users (licenses that could have lots of sites)
- Changed setting name from "Recipients" to "Summary email recipients" for clarity
- Check white labeling based on icon instead of name. For a while, the menu default was "Forms" so this is excluding too many sites. Also, don't check if pro is inactive (Part of https://github.com/Strategy11/formidable-pro/issues/4687 )

Add message with Email summary settings

---

classes/views/frm-fields/back-end/settings.php

Fixes https://github.com/Strategy11/formidable-pro/issues/4757
This just adds the `&t=captcha_settings` to the URL.

Fix pro issue #4757 / Link to captcha settings section

---

classes/models/FrmInbox.php

Related update https://github.com/Strategy11/formidable-stripe/pull/325
This adds a new filter `frm_inbox_message_is_for_user` so we can use custom rules in the Stripe add-on.

New filter `frm_inbox_message_is_for_user`

---

classes/models/fields/FrmFieldType.php

Fixes https://secure.helpscout.net/conversation/2503809609/189379/
> Warning: undefined property stdClass::$updated_by
I'm not sure how the entry doesn't have an `updated_by`, but adding a check doesn't hurt.

Check entry->updated_by is set fix

---

css/frm_admin.css

Fixes https://github.com/Strategy11/formidable-pro/issues/4777
I tested this on our staging site where it has the same issue as formidableforms.com.
I think the issue is just the order that the CSS loads. It must be loading in a different order on these sites where the WordPress styles get less priority.
I took the style suggestion from the issue, which did the trick. I also tested with JavaScript disabled, which had the same issue with displaying both buttons, so I added a `no-js` rule as well.

Pro issue 4777 / Add more css to hide search buttons

---

classes/models/fields/FrmFieldType.php

Related comment https://github.com/Strategy11/formidable-forms/pull/1501#discussion_r1483226320
Related PR https://github.com/Strategy11/formidable-pro/pull/4789
This update adds another check for `user_id` so old versions of Pro don't trigger this warning.
The issue is that `FrmProSummaryValues::base_entry` creates an `stdClass` with no `user_id` or `updated_by` values. In https://github.com/Strategy11/formidable-pro/pull/4789 I define these keys now.

Also check for entry user id in should strip most html

---

classes/controllers/FrmAddonsController.php
js/formidable_admin.js

Remove the old v1 connect js since it was unused
Firefox is removing all paramters from the URL if any utms are included. This removed the utms so the link will work.

Fix: parameters getting stripped from connect flow

---

classes/models/FrmAddon.php
classes/models/FrmFormApi.php
tests/misc/test_FrmFormApi.php

**Related tickets**
https://secure.helpscout.net/conversation/2506175920/189635
https://secure.helpscout.net/conversation/2506108172/189628/
It looks like an error for a nulled license works differently.
Instead of the expected `$addons['error']` array, it's a string like "Your license has been blocked!".
The "Y" shows up in PHP 7.4.
In PHP 8 it throws a fatal error instead,
> Uncaught TypeError: Cannot access offset of type string on string in .../formidable/classes/models/FrmFormApi.php:261
> Stack trace:
> #0 .../formidable/classes/models/FrmFormApi.php(245): FrmFormApi->get_error_from_response()
> #1 .../formidable/classes/models/FrmAddon.php(327): FrmFormApi->error_for_license()
> #2 .../formidable/classes/models/FrmAddon.php(317): FrmAddon->show_license_message()
> #3 …

Make form API error handling support string errors

---

js/admin/dom.js

Fixes https://github.com/Strategy11/formidable-pro/issues/4810
Bootstrap multiselect by default shows "All selected" when all items are selected.
This isn't very useful when there are only a couple options. With this update, I'm removing the "All selected text", so it never shows.
**Before**
**After**
If you select a lot of options, it starts to count them. IF you select all of them, after this update, instead of "All selected", it will just continue to show a count.
**I'm not sure if we want to make this more dynamic?**
It starts to count items elected when the number of options selected exceeds `numberDisplayed`. The default value for `numberDisplayed` is 3.
We could consider bumping this number as well. For example, if I bump it to 10, it looks like this,
It might be that we want to …

Stop showing "All Selected" text in Bootstrap multiselect dropdowns

---

js/admin/dom.js

Quoting Steph from https://github.com/Strategy11/formidable-pro/pull/4630#pullrequestreview-1883987426
> It would also help to show -- Select -- in the dropdown if nothing is selected.
Before this was always an empty string so there were no placeholders.
I figure this is fine to add to all multiselect dropdowns and not just the one in the linked PR.

Use please select placeholder for bootstrap multiselect

---

js/admin/style.js
js/formidable_admin.js

Fix https://github.com/Strategy11/formidable-pro/issues/4611
1. Go to Visual Styler page and turn on your Assistive software.
2. Try tabbing through the accordion headers and confirm that the state of the currently tabbed accordion element is announced as you do so.

Add aria-expanded to accordion h3 elements

---

js/admin/dom.js

Related comment https://github.com/Strategy11/formidable-pro/pull/4630#issuecomment-1952836137
> I don't see the tooltip issue when clicking the dropdown anymore, but if I hover the selected option then I can see it.
This update removes the title attribute from the bootstrap multiselect dropdown toggle buttons after it is initialized.

Remove title from bootstrap multiselect dropdown toggle button

---

classes/models/fields/FrmFieldHTML.php

Related ticket https://secure.helpscout.net/conversation/2511714226/190280/
When showing a quiz score's correct answers, `FrmProEntriesController::show_entry_shortcode` is called.
When a user is not logged in, `FrmAppHelper::strip_most_html` is removing `img` tags from HTML field display.
This was introduced with https://github.com/Strategy11/formidable-forms/pull/1439
An HTML field doesn't really need any of the logic from `FrmFieldType::get_display_value`.
This skips some code, so `fill_default_atts`, `FrmAppHelper::strip_most_html`, `prepare_display_value`, and some checks for if `$value` is an array with checks for `$atts['show']`, are all skipped entirely.
HTML fields really don't need any of that. They should just display as is, since there isn't any user content directly defining …

Stop stripping most HTML from HTML field display value fix

---

classes/models/FrmFormApi.php

Related ticket https://secure.helpscout.net/conversation/2517410674/190926
> An error of type E_ERROR was caused in line 161 of the file .../plugins/formidable/classes/models/FrmFormApi.php. Error message: Uncaught TypeError: Cannot access offset of type string on string in .../plugins/formidable/classes/models/FrmFormApi.php:161
The array of `$addons` includes non-array values `$addon` like `"active_sub" => "no"` and `"expires" => "1769903999"`.
This update makes sure that we only check array `$addon` values.
Pre-release,
[formidable-6.8.3b.zip](https://github.com/Strategy11/formidable-forms/files/14361728/formidable-6.8.3b.zip)

Add an is_array check in get_addon_for_license function fix

---

js/formidable_admin.js

This has been broken since v6.4.2. Caused by https://github.com/Strategy11/formidable-pro/pull/3829 where we swapped font icons for SVGs. This was missed.
I've moved this code into Pro instead https://github.com/Strategy11/formidable-pro/pull/4827
So I'm removing it from here. Since it's already been broken, it makes sense to move this rather than fix it in Lite.

Remove setStarValues function from Lite

---

classes/helpers/FrmAppHelper.php
classes/helpers/FrmFieldsHelper.php
classes/models/FrmSettings.php
classes/models/fields/FrmFieldType.php
tests/fields/test_FrmFieldsHelper.php

Related ticket https://secure.helpscout.net/conversation/2505693625/189582/
> if a field is left blank, the error message needs to include what field , such as "The name field cannot be left blank", "the message field cannot be left blank", etc.
I initially brought this up in Slack (https://strategy11.slack.com/archives/G01KDLFJTJS/p1707484587610489).
Quoting Steph's reply,
> We could use "[label] cannot be blank", but I think it's fine if we replace "this field" so we don't have to add extra support, and fix this for existing forms.
I'm using `[field_name]` (rather than `[label]`) which is already a supported in a few places. I believe it works with JavaScript validation without making further changes because it gets replaced in field HTML already.
**Some issues with blank error messages …

Add field name shortcode for error messages

---

classes/models/FrmFormApi.php

Following up from an update from yesterday (https://github.com/Strategy11/formidable-forms/pull/1524).
I'm testing with errors, and there are still PHP warnings coming from this line still because errors are arrays but do not include the `title` key.
> PHP Warning:  Undefined array key "title" in /var/www/src/wp-content/plugins/formidable/classes/models/FrmFormApi.php on line 161
>  PHP Deprecated:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated

Add an isset check to FrmFormApi::get_addon_for_license

---

tests/base/FrmUnitTest.php

I saw this message a lot when running Stripe unit tests.
This is just a small update to not pass a string as the 1st argument to `setValue`. I'm passing null instead of the param is the unexpected type.
> PHP Deprecated:  Calling ReflectionProperty::setValue() with a 1st argument which is not null or an object is deprecated in .../formidable/tests/base/FrmUnitTest.php on line 655

Fix deprecated messaged when running Stripe unit tests

---

classes/controllers/FrmSMTPController.php
classes/models/FrmSolution.php
css/_single_theme.css.php
css/custom_theme.css.php
css/font_icons.css
css/frm_admin.css
css/frm_grids.css

Related ticket https://secure.helpscout.net/conversation/2518544642/191058/
This update removes a lot of the prefixed `-webkit-` and `-moz-` CSS rules. These are legacy from back when CSS3 was really new and are no longer required. Many of these now throw warnings when validating site CSS (like using https://jigsaw.w3.org/).
Many of these at least no longer work in Firefox, and documentation is fully removed.
I didn't fix everything. This is more of a phase 1 update. It helps drop a lot of errors from the CSS validation list so the remaining pieces are easier to digest. So far I was able to drop about 50 lines of CSS across various files.
I mostly target a few rules in this update including `-webkit-box-sizing`, `-moz-border-radius`, `-webkit-box-shadow`, and `animation` rules.
Once this …

Remove a lot of old CSS rules that are no longer required

---

classes/helpers/FrmStylesHelper.php
css/_single_theme.css.php
tests/styles/test_FrmStylesHelper.php

I noticed some issues when testing my Formidable CSS against https://jigsaw.w3.org/css-validator/
Colour values when using RGB values are coming through wrong as `background: rgba(, , , 0.15) !important;`.
The problem is that `hex2rgb` is called unconditionally and doesn't work with rgb values.
I also added a check if `$border_width` is empty to avoid a parsing error,
Really, we should be checking if every setting is empty, but each check makes this look more messy.

Make hex to rgb function work with rgb values

---

classes/controllers/FrmAddonsController.php
classes/controllers/FrmHooksController.php
classes/helpers/FrmAppHelper.php

- Remove the ajax for v1 connect process. The JS for the 'frm_connect' ajax was removed in an earlier PR
- Pass a return page and installed flag to the connect progress. If it's already installed, the api won't return a file_url
The server-side updates are already in place, and most of the changes are there.
With this update:
- After connecting, we'll return to the same page we started from (settings, dashboard, add-ons)
- If the plugin is already installed, there shouldn't be any errors
- The connect process should be much smoother. This includes when pro is installed but disconnected and when pro is not installed.

Update connect flow

---

classes/helpers/FrmFormTemplatesHelper.php

This PR addresses an issue where the unit test `test_FrmFormTemplatesController::test_render` was failing due to an undefined index 'name'.
Verify that the test runs successfully in all environments.

Fix Undefined Index 'name' in Form Templates Unit Test

---

js/formidable_admin.js

Related PR https://github.com/Strategy11/formidable-forms/pull/1533
This is just a small attempt to clean this part of this update up a bit. I don't think we need to create a temporary element and risk getting only a single child when the HTML returns multiple.

Use insertAdjacentHTML for 4796 fix

---

js/formidable_admin.js

Fixes https://github.com/Strategy11/formidable-ai/issues/51
This update in lite is required to make shortcode popups work for an AI field in https://github.com/Strategy11/formidable-ai/pull/50 work

Add shortcodes popup to ai field

---

classes/helpers/FrmEmailSummaryHelper.php
tests/emails/test_FrmEmailSummaryHelper.php

With https://github.com/Strategy11/formidable-forms/pull/1457/ the function `maybe_remove_recipients_from_api` was introduced.
The problem is that `$recipients` is a string, not an array, so the function doesn't really work as expected.

Pro issue 4842 / Convert string recipients to array fix

---

classes/helpers/FrmXMLHelper.php
classes/views/xml/import_form.php

This update adds a `accept=".xml, .csv"` attribute when Pro is active, or a `accept=".xml"` attribute when only Lite is active.
I figure this is better for usability. It's more clear what can be uploaded since the wrong types are all faded out.
I got a little mixed up trying to upload a `.zip` of a `.xml` for a moment. This update helps make the types easier to tell apart, preventing a `.zip` upload from happening by accident.

Filter import file options

---

css/frm_admin.css
tests/emails/test_FrmEmailSummaryHelper.php

Fixes https://github.com/Strategy11/formidable-pro/issues/4749
This issue is not specific to Product fields but any field with options and separate values settings.
The issue is that this `display: block` rule is overwriting the `display: none` rule from `frm_hidden`.
**This is not a live bug yet.** It's just a bug in master. This is introduced in https://github.com/Strategy11/formidable-forms/pull/1442

Separate value input is visible when disabled fix

---

js/formidable_admin.js

Fix https://github.com/Strategy11/formidable-ai/pull/50
We want to support multiple shortcodes popups per field as per Mike's comment in Guide prompt for AI field here: https://github.com/Strategy11/formidable-ai/pull/50#issuecomment-1969627465

Support multiple shortcode popups per field

---

js/formidable.js

I don't think we need these functions anymore.
These functions were deprecated back in September 2015, nearly 9 years ago.
In this commit https://github.com/Strategy11/formidable-forms/commit/5695ba18b4806ae6e4d0838d0d443f779df43673
This helps simplify and reduce the size of our front end JS, dropping 45 lines of old deprecated code.

Drop old deprecated frontend JS functions

---

css/frm_admin.css

Following up from https://github.com/Strategy11/formidable-forms/pull/1549
The CSS added in https://github.com/Strategy11/formidable-forms/pull/1442 is causing other issues too.
I'm changing this to only happen for `frm_has_shortcodes` children to cut back on styling conflicts.
`display: block` is causing these icons to look off.
They should look like this

Only make frm_has_shortcodes children spans display block fix

---

classes/models/FrmForm.php
tests/forms/test_FrmForm.php

Related ticket https://secure.helpscout.net/conversation/2518729092/191090/
A lot of code works on the assumption that `$form->options` is an array.
I tried adding some checks in some updates yesterday (in https://github.com/Strategy11/formidable-forms/pull/1543, https://github.com/Strategy11/formidable-pro/pull/4845 and https://github.com/Strategy11/formidable-pro/pull/4844) but I think we're better off just forcing `$form->options` as an array right away. Trying to fix this in every place where we assume `$form->options` is an array is turning into too much work and too many undetected bugs.
**This update now forces all results from `FrmForm::getOne` to have an array `$form->options` value when `$form` is not null. I used the lite form defaults so some basic keys are defined, to help …

New function `FrmForm::prepare_form_row_data`

---

css/frm_admin.css

This PR resolves the UI inconsistencies reported in [Issue #4832](https://github.com/Strategy11/formidable-pro/issues/4832), focusing on the add-ons page when the pro version is installed but not authorized. Changes include altering button styles from primary to tertiary, ensuring that activate/deactivate/uninstall options do not coexist with the upgrade button, and improving the vertical alignment of text and buttons.
[Messed up add-ons page with lots of buttons #4832](https://github.com/Strategy11/formidable-pro/issues/4832)
https://github.com/Strategy11/formidable-pro/pull/4857
1. Install the Formidable Pro plugin but leave it unauthorized.
2. Navigate to the Add-Ons page (`WP Admin > Formidable > Add-Ons`).
3. Observe the button styles and alignment, comparing them to the provided …

Fix Alignment and Button Styles on Add-Ons Page

---

classes/models/FrmAddon.php

This was introduced in https://github.com/Strategy11/formidable-forms/pull/1517
> PHP Deprecated:  Creation of dynamic property FrmProEddController::$save_status is deprecated in /var/www/src/wp-content/plugins/formidable/classes/models/FrmAddon.php on line 802
I'm just defining the property so it isn't dynamic.

Define new FrmAddon property

---

js/formidable_admin.js

Related PR https://github.com/Strategy11/formidable-quizzes/pull/194
This helps to avoid the unsaved changes pop up after removing a scored quiz row.
This is because we call `fieldUpdated()` when the row is removed without checking the page first.
We'll likely want to add the unsaved changes pop up in global settings in the future. This update just makes sure that the pop up does not appear when the update button is clicked.

Set fields updated to 0 on global settings form submit

---

js/formidable_admin.js

I'm just removing some more old deprecated JS, trying to clean up a bit.
It looks like v2.0 is from Apr 10, 2015 so this has been deprecated for about 9 years.

Remove old deprecated admin functions

---

js/formidable_admin.js

Fix https://github.com/Strategy11/formidable-pro/issues/4846
The new shortcodes popup position was fixed and not updated when scroll and this update fixes that.
Followup conversation https://github.com/Strategy11/formidable-pro/pull/4856#discussion_r1516262084

Update position of shortcodes popup on scroll

---

classes/helpers/FrmAppHelper.php
tests/misc/test_FrmAppHelper.php

Fix https://github.com/Strategy11/formidable-pro/issues/3453
This update adds a check for a variable value against null and then convert it to empty string before passing it to string manipulation functions.
1. Make sure your PHP version is `>=8.1`
2. There could be different methods to test this but I just used `FrmAppHelper::recursive_function_map( array(), 'trim' );` in a code snippet.

Prevent null from being passed to string functions

---

psalm.xml

There were no conflicts for this rule other than `apply_filters`.
🥳

Fix too many arguments psalm rule

---

css/packages/s11-floating-links.css
js/packages/floating-links/s11-floating-links.js

This update aims to reduce the height of the inbox slide-in, made to look more similar to the review request pop up.

Compact inbox slidein

---

js/formidable_admin.js

Fix https://github.com/Strategy11/formidable-pro/issues/4934
Sharing Mike's screen record about the issue:
https://github.com/Strategy11/formidable-pro/assets/9134515/a136bf85-d72d-45b0-8e73-33999adc5ab6
Confirm that the tooltip doesn't get stuck anymore when deleting actions.

Delete tooltip on action delete

---

css/frm_admin.css

Fix https://github.com/Strategy11/formidable-pro/issues/4659
Just reverting fields modal style in views editor.
**Before:**

Undo changes to modal in views editor

---

classes/models/FrmFormApi.php

We ran into a site that had a Cloudflare browser integrity check. Then the transient wasn't getting cleared so the plugin thought is was in Lite mode.
This update clears the running transient too when the api cache is cleared.
See https://secure.helpscout.net/conversation/2565742705/195727

Clear the running transient too when resetting cache

---

js/formidable_admin.js

Fixes https://github.com/Strategy11/formidable-pro/issues/4944
This makes it work more like it did in v6.8.4. When there are no fields, the index is always 0, so the drag marker always shows at the top, above the no fields element.
**Pre-release,**
[formidable-6.9b.zip](https://github.com/Strategy11/formidable-forms/files/14949646/formidable-6.9b.zip)

Fix issue 4944 / Drag to index 0 when there are no fields

---

classes/models/FrmInbox.php

**Related ticket** https://secure.helpscout.net/conversation/2575367680/196908
This update just adds a check that the keys are actually set first to avoid the warning.
Warning: Undefined array key "image" in /home/1210999.cloudwaysapps.com/xrqfjetdjw/public_html/wp-content/plugins/formidable/classes/models/FrmInbox.php on line 514

Add isset check for inbox slidein

---

classes/controllers/FrmFieldsController.php
classes/helpers/FrmFieldsHelper.php
classes/models/FrmFieldTypeOptionData.php

This update stores and re-uses the type options for each field type.
With a really long form, my load page is down from ~68.5 seconds to ~61.7 seconds, a ~6.8 second savings, about 10% faster.
**Before**
**After**

Store and reuse type options for field type

---

classes/models/fields/FrmFieldType.php
classes/models/fields/FrmFieldUserID.php
phpstan.neon

This update just makes comment signatures more consistent to adhere to the Liskov substitution principle.

Fix some phpstan contravariance issues

---

classes/helpers/FrmFormMigratorsHelper.php

This skips some logic that happens on the inbox constructor when it isn't needed.

Do not init inbox if there are no importable forms

---

.eslintrc.json
js/formidable.js
js/formidable_admin.js
js/formidable_admin_global.js
tests/cypress/e2e/formidable-admin.cy.js
tests/cypress/e2e/spec.cy.js

I ran `./node_modules/.bin/eslint ./js/formidable_admin.js --fix` with just the `no-var` and `prefer-const` rules in `formidable_admin.js` and `formidable_admin_global.js`.
This gets us away from `var` and closer to a more modern standard.

Replace var with let/const in admin js files

---

classes/controllers/FrmApplicationsController.php

Fix: [i18n] The strings in Applications are not displayed translated

Fix: [i18n] The strings in Applications are not displayed translated

---

classes/models/FrmHoneypot.php

This is just a tiny tweak that may help with the Honeypot iOS issue?
"false" isn't really a standard option but "off" is.

Use off for autocomplete on honeypot not false

---

js/formidable.js

Related ticket https://secure.helpscout.net/conversation/2590327517/198659
The inconsistency here is that we usually use the `html_id` for the error which is really `'field_' . $field['field_key']` and possibly more for an embedded/repeated form.
The `key` variable in this case is really an integer field ID, so it's inconsistent.
To replicate,
1. Add a field to a form. Make it required
2. Enable AJAX submit.
3. Submit the form.
**Expected result**
- The error should use the id `frm_error_field_29yf4d`.
**Actual result**
- The error is formatted like `frm_error_field_3` instead.
**Pre-release,**
[formidable-6.9.2b.zip](https://github.com/Strategy11/formidable-forms/files/15238502/formidable-6.9.2b.zip)

Use field keys for errors not ids

---

js/formidable.js

Pro v.6.9.2 is now live.
Lite likely won't go out for a few weeks with version v6.10. So deprecating `frmUpdateField` for next release shouldn't be an issue.
I'm dropping a lot of old global functions that were deprecated in v3.0. I don't see any references to these in our docs or in GitHub. They should be good to get rid of.

Drop several deprecated global JS functions and deprecate frmUpdateField

---

classes/helpers/FrmAppHelper.php
js/formidable.js

This is only included in Pro on the entries page sidebar.
I'm moving it into the Pro entries.js code now, out of Lite, where it isn't required.
Related PR https://github.com/Strategy11/formidable-pro/pull/5046

Deprecate and conditionally include resend email logic

---

classes/helpers/FrmFormsHelper.php

Using my slow form with 1,0004 fields, the form settings page is pretty slow to load.
It's mostly because of these calls to `FrmField::all_field_selection()`. By calling it only once (instead of nearly 900 times), it cuts my page load by about 69% 🚀.
This optimization also helps on the form builder where we also use this sidebar for populating HTML/Rich Text fields.
_On form settings_
**Before**
~10.43 seconds
**After**
~3.24 seconds
**~7.19 seconds faster**
_In the form builder_
**Before**
~48.3 seconds
**After**
~41.31 seconds
**~6.99 seconds faster**

Store and reuse field selection data when outputting shortcode options optimization

---

css/custom_theme.css.php

Firefox is complaining about this even 😅. This legacy style is no longer required.

Drop old css moz drop shadow rule

---

css/frm_admin.css

The `opacity: 0.5` rule covers this.
The other rule must have been for old browsers. It's no longer required, and since it's deprecated it throws warnings.

Stop using deprecated "alpha" in css

---

classes/helpers/FrmXMLHelper.php

Fix: calendar views - fields option IDs mapping. 
Issue reported here: https://github.com/Strategy11/formidable-views/issues/512#event-12748325797

fix calendar view options on import

---

classes/controllers/FrmFormsController.php

This is more of a WP/Theme issue, but this update helps make sure that Formidable isn't triggering a deprecated message.

Add a null check to avoid deprecated message when previewing

---

classes/controllers/FrmFormsController.php

I'm just cleaning up a bit. I merged two checks into a `! empty` to simplify a condition. I also added a strict equals check.

Add some comments to forms controller

---

classes/controllers/FrmFormsController.php
classes/views/frm-forms/add_form_style_options.php
classes/views/frm-forms/settings-buttons.php

Fixes https://github.com/Strategy11/formidable-pro/issues/5058
This update does a few things,
- It updates the buttons settings page to just look like Pro now instead of showing a placeholder input that doesn't exist in Pro anymore. This page isn't terribly marketable and it will be removed soon so I think this is all we need to bother with doing right now.
- I removed an old deprecated `FrmFormsController::add_new` function that I confirmed isn't being referenced anywhere.
- Added some `@return void` comments.
- Removed some variables that aren't being used anymore in `FrmFormsController::buttons_settings`.

Pro issue 5058 update form button settings

---

classes/models/fields/FrmFieldType.php
css/font_icons.css

In my form with 1,004 fields, where 214 of which have options, this saves approximately 1.926 seconds from the load time.
This is at a rate of saving `0.009` seconds for each of the `214` fields that need to get this field selection data. `0.009 * 214 = 1.926`.
So it loads in 33.27 seconds instead of 35.196 seconds.
For a 5% reduction in overall page load time.

Store and reuse field selection data when displaying field type in options

---

classes/helpers/FrmFormsHelper.php
classes/views/frm-forms/actions-dropdown.php

I noticed this code is totally unused.
So I'm officially marking it as deprecated so we can remove it.

Dreprecate FrmFormsHelper::actions_dropdown

---

css/_single_theme.css.php
css/custom_theme.css.php

These haven't been used since before Pro version 6.4.2, released last August.
`frm_icon_font` is no longer used on the front end so none of these styles should be necessary any longer.

Remove old styles for pro features using icon fonts

---

classes/views/shared/images-dropdown.php

I noticed when viewing my HTML that there was no space between `data-value="buttons"` and `data-medium="builder"`. This update fixes that.

Small html formatting fix

---

classes/views/frm-entries/direct.php

I caught this issue when validating our form preview HTML.
The WP theme adds a title attribute, and we're adding a second one.
This update checks if the theme supports the `title-tag` option. If it doesn't, we show a title tag. If it does, we use the `document_title` filter to overwrite the text.
Also, to avoid `|` and nothing (when there is no title), I've added a `(no title)` fallback to the title.

Avoid double title attributes when previewing form

---

classes/helpers/FrmFieldsHelper.php

See https://github.com/Strategy11/formidable-forms/pull/1773/
When removing a field type, something like
```
add_filter(
'frm_pro_available_fields',
function( $fields ) {
unset( $fields['date'] );
return $fields;
}
);
```
A warning will be thrown in the form builder
> PHP Warning:  Undefined array key "date" in /var/www/src/wp-content/plugins/formidable/classes/helpers/FrmFieldsHelper.php on line 1208
And a blank option will appear when trying to change field type.

Alt solution to PR 1773

---

classes/views/form-templates/categories.php
classes/views/form-templates/template.php

Fixes HTML errors on the Form Templates page.
https://qa.formidableforms.com/sherv4/wp-admin/admin.php?page=formidable-form-templates
https://github.com/Strategy11/formidable-pro/issues/5114
1. Open the QA URL.
2. Right-click and select "View Page Source."
3. Copy all the HTML of the source page and paste it into [W3C Validator](https://validator.w3.org/#validate_by_input).
4. Verify that the new HTML errors after releasing the Form Templates are no longer present.

Fix the Form Templates page new HTML errors

---

css/custom_theme.css.php

This was only necessary for old versions of IE and should be safe to remove now.

Drop old css rule ms-pointer-events

---

css/_single_theme.css.php

This is covered now by `box-sizing:border-box;` and was only required for old versions of IE.

Drop old ms box sizing css rule

---

classes/controllers/FrmFormsController.php

The issue: When running a API form action with a repeater entry, other field shortcodes don't work.
You can use this form to test:
[repeater-actions-form.xml.zip](https://github.com/Strategy11/formidable-forms/files/15427173/repeater-actions-form.xml.zip)
That form contains Text, Repeater 1, and Repeater 2 fields. It has the API form action that sends the request to itself. I use this code to log the request:
```
add_action( 'init', function() {
if ( isset( $_GET['repeater-actions-test'] ) ) {
error_log( print_r( file_get_contents('php://input'), true ) );
}
} );
```
When set the `Run this action for` to `Repeater 1`, the shortcodes for other fields should work.

Fix frm_content filter doesn't work with repeater actions

---

css/frm_admin.css

These styles are no longer used by the form templates list.
These are also not used for the New View modal.
So I'm removing them since they aren't applying to anything any longer.
🚀

Drop some old form templates styles

---

css/frm_admin.css

It looks like `.frm-help-tabs` don't exist anymore.
And `frm_no_bg` is only used for a bootstrap setting. Removing it doesn't make an impact.

Drop more unused CSS

---

classes/controllers/FrmEntriesAJAXSubmitController.php
js/formidable.js
tests/phpunit/entries/test_FrmEntriesAJAXSubmitController.php

Related ticket https://github.com/Strategy11/formidable-pro/pull/5131
Related PR for AJAX validation issues when Pro is active https://github.com/Strategy11/formidable-pro/pull/5131
This fixes the issue when JS validation is on.
I also dropped some repeater logic from `maybe_modify_ajax_error` since this code is never reached when Pro is active so there's no reason to check for repeaters.
**Pre-release,**
[formidable-6.11b.zip](https://github.com/user-attachments/files/15805493/formidable-6.11b.zip)

Use field keys not ids for js validation errors

---

classes/helpers/FrmStylesHelper.php
classes/views/frm-fields/back-end/settings.php

Related issue https://github.com/Strategy11/formidable-pro/issues/3849
Required for https://github.com/Strategy11/formidable-pro/pull/4947

Add a filter that allows updating label positions

---

.github/workflows/cypress.yml
package.json
tests/cypress/e2e/validate-css.cy.js

This update uses Cypress to load CSS files and validate them using https://jigsaw.w3.org/css-validator/.
I initially tried doing this with PHP and WordPress using PHPUnit, but calling the API with curl was always resulting in an error from the API that I couldn't figure out even though it worked fine in Postman.
For now this covers the two main CSS files that get changed the most often and cover most of the styling - `frm_admin.css` and our generated `formidableforms.css` files.
For now this only throws errors if there is a CSS error, ignoring warnings. I also ignore one specific CSS error type which is getting flagged for a false positive.
If our CSS is ever invalid, this should catch that ahead of time.

Add automated CSS validation with Cypress

---

classes/helpers/FrmAppHelper.php
js/formidable.js

People should be on the newer versions of Pro by now. v6.9.2 came out on May 8, making this over a month ago now, and a few versions behind as we're currently on v6.10.1 and this will be introduced in v6.11.

Drop deprecated frmUpdateField front end function

---

classes/views/frm-form-actions/_email_settings.php
css/frm_admin.css

Related issue https://github.com/Strategy11/formidable-pro/issues/5063
This update updates some old font icon code to use `FrmAppHelper::icon_by_class` instead.

Stop using font icons for email bcc/cc/reply to remove icons

---

classes/views/frm-fields/back-end/field-options.php
css/frm_admin.css

Related issue https://github.com/Strategy11/formidable-pro/issues/5063
Related Pro PR https://github.com/Strategy11/formidable-pro/pull/5137

Stop using font icons for add option icon

---

classes/views/frm-fields/single-option.php
css/frm_admin.css

Related issue https://github.com/Strategy11/formidable-pro/issues/5063
This update changes the `-` icon on the right of an option which triggers removing the option.

Stop using font icons for removing radio/checkbox/dropdown options

---

classes/controllers/FrmAppController.php

4.0 is really old. This hasn't been updated in some time. The last update was 5 years ago.

Bump minimum pro version

---

psalm.xml

These are no longer required because a lot of deprecated code has been removed.

Remove psalm exceptions

---

classes/models/FrmEmail.php

Fix https://github.com/Strategy11/formidable-pro/issues/1970
**Before**
**After**
1. Create a form and adda an RTE field to it.
2. Create an email action, checking `Send Emails in Plain Text`.
3. Preview the form, switch to "Visual" mode and fill the RTE with a text that has line breaks.
4. View the email sent and confirm that there are no `&nbsp;` strings displayed in the email body.

Replace nbsp from plain email content

---

classes/views/frm-forms/insert_form_popup.php

This just gets rid of a non-functional icon that just causes confusion.

Drop down arrow icon from insert form pop up

---

css/frm_admin.css

This is a design update from Razvan,
With this update, the close icon in modals is now a lighter shade of gray, and darkens on hover, to a color that is still slightly lighter than it was before.
This is part of the AI generated forms design https://www.figma.com/design/3v8h3KPhiT8wVULnQNAY1p/Create-Form-with-AI?node-id=3-21&t=TQVW3ShqEQ6Deggw-0

Update modal close icon color styling

---

classes/controllers/FrmFormsController.php
classes/helpers/FrmEntriesListHelper.php
classes/helpers/FrmFormsListHelper.php
classes/helpers/FrmListHelper.php
stripe/helpers/FrmTransLiteListHelper.php

Fix https://github.com/Strategy11/formidable-pro/issues/4901

Output screen reader texts on forms and entries list pages

---

.gitattributes
.github/workflows/typos.yml
_typos.toml
bin/zip-plugin.sh
changelog.txt
classes/models/fields/FrmFieldType.php

This PR adds automated typo checking using the typos CLI (See https://github.com/crate-ci/typos).
I've added a baseline for the things to ignore as well.

Define typos CLI baseline and fix more typos

---

classes/models/FrmRecaptchaSettings.php

The reCaptcha type name was showing up as an empty string.
**Before**
**After**

Fix recaptcha name function is returning empty string

---

classes/controllers/FrmOnboardingWizardController.php

This PR addresses the PHP warning errors reported on the Onboarding Wizard page when using the PRO basic license.
[Formidable Forms Pro Issue #5143](https://github.com/Strategy11/formidable-pro/issues/5143)
1. Install Formidable Forms PRO with basic license activation.
2. Navigate to the Onboarding Wizard page.
3. Verify that no PHP warnings appear in the PHP error log or on the page itself.

Fix: Onboarding Wizard Page PHP Warning Error for PRO Basic License

---

classes/helpers/FrmEntriesListHelper.php

I was seeing this on some forms.
All of the column names are prefixed with `0_`. Removing that fixes the issue.

Fix entries list appears empty when item meta with 0 field ID exists

---

js/formidable.js

Fix https://github.com/Strategy11/formidable-pro/issues/5194
The issue happens because of an outdated element selector in `enableSaveDraft` function.
**Before**
**After**:
1. Create a simple form and enable draft saving
2. Add a lookup field to get value from another form
3. Add another lookup field to watch the first field
4. Save the form and preview the form
5. Change the value of the first Lookup field and confirm that the draft button is enabled back when the lookup is done

Fix issue with enabling draft button after lookup is finished

---

classes/helpers/FrmEmailSummaryHelper.php

Fixes https://github.com/Strategy11/formidable-pro/issues/5205
To test:
- Use `FrmEmailSummaryHelper::send_monthly();` to send the monthly email. Make sure that there is no repeaters in the top forms list.
- Choose a form with a repeater, then submit an entry with some repeater items.
- Use the above function to send the monthly email again.
- Make sure that the `Entries created` increases by 1.

Exclude repeater forms and entries from summary email

---

classes/helpers/FrmEntriesListHelper.php
languages/formidable.pot
tests/cypress/e2e/admin-a11y.cy.js

This is a small accessibility improvement to remove the `select-name` exception in our Cypress tests.
The views list test here is also incorrect, checking the entries page instead. But since views isn't part of core this test doesn't really fit the scope either way and won't work with just Lite active.

Add screen reader label for form dropdown filter

---

classes/controllers/FrmEntriesController.php

I just noticed this error and that it wasn't up-to-date.
This update calls the the `FrmAppController::show_error_modal` function introduced in v6.7.
**Before**
**After**

Update error handling when viewing an entry that does not exist

---

js/formidable.js

This PR addresses the issue with the international phone field not correctly validating phone numbers.
[Strategy11/formidable-pro/issues/5208](https://github.com/Strategy11/formidable-pro/issues/5208)
1. Create a form with a phone field.
2. Ensure it uses the international format.
3. Enable the "Validate this form with JavaScript" setting in the form settings.
4. Open the form and choose Egypt (as an example).
5. Enter the following number: `01011140`.
6. You will see that it's marked as valid, but it isn't. The correct number is `01011140144`.

Fix International Phone Field Validation Issue

---

css/frm_admin.css

Fixes https://github.com/Strategy11/formidable-pro/issues/5192
The submit field button shouldn't show in the field type search result.

Hide submit field button from field search result

---

classes/helpers/FrmAppHelper.php
classes/views/frm-settings/license_box.php

Related issue: https://github.com/Strategy11/formidable-pro/issues/5186

Make license messages translatable

---

classes/models/FrmField.php

Some pro unit tests are failing because of this code.
Old versions of WordPress (prior to v6.5), can return other types, not just arrays.

Add array check to input shortcode sanitize fix

---

js/formidable_admin.js

Fix https://github.com/Strategy11/formidable-pro/issues/2909
1. Create a Product field with some product options.
2. Add another field that conditionally shows based off the product field's value and save.
3. Go the the Product field and rename an option.
4. Go back to the conditional field and confirm that there is no new option added in the conditional logic row. The existing options should have been renamed instead.

Do not add a new option to conditional logic if renaming an option

---

.github/workflows/phpstan.yml

Fixes https://github.com/Strategy11/formidable-pro/issues/5243
The workflow is segfaulting.
Related issue https://github.com/phpstan/phpstan/issues/6646
They recommend not running PHPStan with opcache in that issue.

Stop using jit/opcache in phpstan workflow

---

js/formidable_admin.js

Fix https://github.com/Strategy11/formidable-pro/issues/5225

Prevent user id field from being dragged into field group

---

js/formidable_admin.js

Fixes an error introduced in https://github.com/Strategy11/formidable-forms/commit/9e1b2cda5e40a26472158811f1a522d970883c36

Fix undefined function: groupIncludesBreakOrHidden

---

js/formidable.js

This update removes our only use of `.first()`. It also removes a `.find()`.
The `scrollMsg` function still appears to require a `jQuery` object for the time being. That can be addressed separately though. I'm trying to minimize the size of this change.

Use less jQuery to scroll to first field

---

js/formidable.js

This update changes our only use a the jQuery `.prepend()` function to vanilla JS.

Stop using jQuery `.prepend` function

---

js/admin/entries.js
js/formidable.js
js/formidable_admin.js

This `frmtoggle` logic is only used on the entries list admin page. It isn't part of the front end form logic so it shouldn't be included in this file. It adds bulk to this file that should be as small as possible.
It's also causing funny issues because there are multiple scripts trying to load on this page to handle this attribute. This update fixes the admin code slightly so we can remove the other code.
It also uses some jQuery functions that are difficult to replace.

Move frmtoggle logic from front end scripts to admin entries JS

---

classes/helpers/FrmAppHelper.php
js/formidable.js

This update removes the only uses of `.html()` in this file.
This only needed to be around for a version or two.
This was deprecated in v6.10, so it will be two big version bumps.
This is now in Pro as part of the entries.js admin script.

Drop resend email JS

---

js/formidable.js

This update stops the use of the jQuery `.removeClass()` function in one place.

Remove error classes from field using vanilla JS

---

classes/controllers/FrmAppController.php

The API add-on is now on version 1.15.
The deprecated function reference was removed in v1.14. That version was released Sep 11, 2023, nearly a year ago.

Remove more deprecated code

---

classes/views/frm-form-actions/form_action.php
css/frm_admin.css

Fix https://github.com/Strategy11/formidable-pro/issues/5249

Stop using font icons for form actions collapsible

---

classes/models/fields/FrmFieldCaptcha.php

Fixes https://github.com/Strategy11/formidable-pro/issues/5237
I added a `str_replace` to remove the extra param that could happen if someone used the hook to fix the bug.
The issue is that we're rendering explicitly and implicitly. This update gets rid of the implicit rendering.

Fix issue with duplicate turnstile renders

---

css/frm_admin.css

Fixes https://github.com/Strategy11/formidable-pro/issues/5178
To replicate, I modified the plugin code to always show their notices.

Hide notice from some plugins

---

classes/helpers/FrmAppHelper.php
classes/views/frm-forms/settings-advanced.php
classes/views/frm-forms/spam-settings/antispam.php
classes/views/frm-forms/spam-settings/honeypot.php
classes/views/frm-settings/captcha/captcha.php
classes/views/frm-settings/general.php
classes/views/frm-settings/messages.php
classes/views/styles/_buttons.php
classes/views/styles/_field-sizes.php
css/frm_admin.css
js/formidable_admin.js
stripe/helpers/FrmTransLiteListHelper.php
stripe/views/settings/messages.php

Related issue: https://github.com/Strategy11/formidable-pro/issues/5250

Use SVG for tooltip icon

---

js/formidable.js

Related ticket https://secure.helpscout.net/conversation/2686690712/207983/
This is essentially the same issue as https://github.com/Strategy11/formidable-forms/pull/1932. I just missed another place where the `object` variable might be an HTMLElement or a jQuery object.
**Patch release**
[formidable-6.12.1b.zip](https://github.com/user-attachments/files/16711283/formidable-6.12.1b.zip)

Fix issue when scrolling to first field when handling stripe error

---

classes/helpers/FrmAppHelper.php
classes/helpers/FrmStylesHelper.php
css/_single_theme.css.php
css/custom_theme.css.php

Ensure the `FrmProAppHelper::use_chosen_js` is called only if it callable.
https://github.com/Strategy11/formidable-pro/issues/5309

Fix: Improve compatibility with old versions of Lite when checking for Chosen

---

classes/helpers/FrmFieldsHelper.php

Fix https://github.com/Strategy11/formidable-pro/issues/5248
0. Download the XML from https://drive.google.com/file/d/1zJL2dhe0XdbIZ8K_3xBp2_nsYgfOni8C/view?usp=sharing and import it.
1. Try duplicating the form with title: `Towards Accessible Waterways 2023 Exhibitor Form`
2. Preview the duplicate
3. Confirm that there is no `[if field_ix]...` shortcodes in place of the field descriptions like below:
4. Try updating the field descriptions for the imported field and check everything works as expected on the form preview.

Avoid corrupted custom html when duplicating field

---

classes/views/addons/settings.php
css/frm_admin.css
js/formidable_admin.js

Fix https://github.com/Strategy11/formidable-pro/issues/5251
Enhancements:
- Switched from using font icons to SVGs.
- User can add/remove license without refreshing the page.
- The activate/deactivate button is disabled until response is received for the prior request
1. Go to the Plugin Licenses tab in the Global Settings and try adding and removing add-on licenses.
2. Confirm that the icons reflect the action of success/error action as expected.
3. Also confirm that, a user can add/remove a license for an add-on without leaving the page, since the 'Activate' and 'Deactivate' elements toggle after few seconds of action.

Replace font icons with SVGs for edd license status

---

js/formidable.js

Fixes https://github.com/Strategy11/formidable-pro/issues/4447
`getFieldId` can return a `0`.
If it does, it triggers a JS error because numbers don't have a `.replace` function.

Fix JS error when trying to validate readonly time field

---

tests/cypress/e2e/admin-a11y.cy.js

We don't need this test since it just covers the global settings page since the payments are not actually set up in the tests.

Drop payments page a11y test

---

classes/helpers/FrmEntriesHelper.php

**Related ticket** https://secure.helpscout.net/conversation/2541877641/193518
This prevents the following fatal PHP error when `$field->field_options` is not in the expected format.
> Error Message: Une erreur de type E_ERROR a été causée dans la ligne 294 du fichier /home/artxterra_app/webapps/artxterra_app/wp-content/plugins/formidable/classes/helpers/FrmEntriesHelper.php. Message d’erreur : Uncaught TypeError: Cannot access offset of type string on string in /home/artxterra_app/webapps/artxterra_app/wp-content/plugins/formidable/classes/helpers/FrmEntriesHelper.php:294 Stack trace: #0 /home/artxterra_app/webapps/artxterra_app/wp-content/plugins/formidable/classes/helpers/FrmEntriesHelper.php(210): FrmEntriesHelper::display_value() #1 …

Add type check before populating field options

---

js/formidable.js

This is required to add JS validation for minimum selections.

Add frm_get_ajax_form_errors event

---

js/formidable_admin.js

Related issue: https://github.com/Strategy11/formidable-pro/issues/4254
Requires: https://github.com/Strategy11/formidable-pro/pull/5313
1. Add one of those fields mentioned in the title and add some options/choices
2. Add another field to the form and create a conditional logic that uses one of those option fields mentioned in the title
3. Select the option field in Step 1 and delete some of options
4. Go back to the field dependent on this ( the one created in Step 2 ), and confirm the conditional logic, the deleted options should not be available anymore.

Sync conditional logic options after field option deletion

---

js/formidable.js

In a customer's site we found a case where on the same page we may have one form twice, one for desktop and the other for mobile and this can be customized in the page builder (SiteOrigin page builder in our case)
Here we will have only one visible form but if the form contains Cloudflare Turnstile captcha, we will have two captcha fields visible.
Here I'm checking if the captcha field is visible before initiating the captcha field.
https://github.com/user-attachments/assets/60f80ccd-9354-4135-8900-532e722e7f59
https://secure.helpscout.net/conversation/2685885705/207895/

Only add Cloudflare Turnstile captcha for visible elements

---

classes/helpers/FrmOnSubmitHelper.php
phpcs.xml
stripe/models/FrmTransLiteAction.php

This way we don't need to manage the translation.

Drop textdomain for common WP string

---

classes/controllers/FrmStylesController.php
classes/helpers/FrmOnSubmitHelper.php

Fix https://github.com/Strategy11/formidable-pro/issues/5324
1. Delete all forms from your site and try going to the Styles page.
2. Confirm that the error message makes more sense and shows in modal on this branch differently from master branch.

Enhance error messages in Visual Styler page

---

classes/helpers/FrmXMLHelper.php

I had added these in another PR that I ended up closing (https://github.com/Strategy11/formidable-forms/pull/1954/files).
This update just copies over those comments.

Add type comments to xml helper

---

classes/models/FrmEntryValidate.php

Fixes #1782 
We did the same thing for comment content. I don't know how to tell Garret to test. I use `error_log()` to test this.

Do not pass non-customizable fields to Akismet guest info

---

classes/controllers/FrmFormsController.php
phpstan.neon
rector.php

This `$all_templates` var is never referenced.
Removing this appears to have no issue while removing a db query on every form builder load.

Drop unused var/db query for all templates

---

phpstan.neon

This update changes a lot of global exceptions so they only apply to a couple of problematic files.

Reduce file scope of some phpstan exceptions

---

css/custom_theme.css.php
css/frm_admin.css

This PR fixes the missing checkbox marker in the backend when editing a checkbox. It also resolves a frontend issue where themes apply a margin to the checkbox `input::before` selector.
https://github.com/Strategy11/formidable-pro/issues/5353
1. Activate the **Twenty Twenty** theme.
2. Add a checkbox to a form and preview the form.
3. Ensure the checkbox displays without any style issues.
1. Go to an **entry** that contains a checkbox.
2. Ensure the checkbox displays without any style issues.

Fix missing checkbox marker in backend

---

classes/controllers/FrmStylesController.php
classes/views/frm-settings/general.php
classes/views/styles/manage.php

Fixes: https://github.com/Strategy11/formidable-pro/issues/5187
This PR will move 2 settings mentioned in the issue to the Manage Styles tab. We will move the `Fade in forms with conditional logic on page load` setting to Other section in General Settings tab in another PR in Pro.

Move Styles & Scripts settings to Manage Styles tab

---

css/custom_theme.css.php

This PR resolves an issue where checkboxes with longer text, including `<br>` and `<a>` tags, were not rendering correctly, causing misalignment.
https://github.com/Strategy11/formidable-pro/issues/5363
1. Create a checkbox field with long text and include `<br>`, `<a>` tags in the text.
2. Verify that the issue is fixed and ensure your output matches the "After" section screenshot.

Fix HTML display issue for checkbox with text and links

---

css/custom_theme.css.php

Fix: Radio button theme conflict issue

---

js/formidable.js

Fixes https://github.com/Strategy11/formidable-chat/issues/180
Instead of checking if the field is invisible, this update checks the form.
A conversational form hides fields until they are active. Checking if the form is visible is more reliable.

Skip rendering captcha only if closest form is hidden

---

classes/helpers/FrmAppHelper.php
classes/helpers/FrmDashboardHelper.php
classes/views/dashboard/templates/pro-features-list.php
classes/views/frm-settings/license_box.php

Fixes https://github.com/Strategy11/formidable-pro/issues/5385

Add utm content to upgrade ctas

---

css/frm_admin.css

Fixes Pro upgrade CTA being cut off at the bottom of the global settings page.
https://github.com/Strategy11/formidable-pro/issues/5386
1. Go to the global settings page.
2. Scroll to the bottom and check if the Pro upgrade CTA is fully visible.

Fix cut-off issue for Pro upgrade CTA at the bottom of the global settings page

---

classes/helpers/FrmCurrencyHelper.php
classes/helpers/FrmFieldsHelper.php
classes/models/FrmEntryValidate.php
stripe/models/FrmStrpLitePaymentTypeHandler.php
stripe/models/FrmTransLiteDb.php

It looks like the big difference here is that `__FUNCTION__` excludes the class name. In all of cases I think we want to know the class as well.

Prefer method over function when calling doing it wrong

---

js/formidable.js

Fixes https://github.com/Strategy11/formidable-pro/issues/4733
**Steps to replicate:**
- Create a form with a password field and enable the password confirmation.
- Enable `Validate this form with javascript` for this form.
- Preview the form, fill in a password then click outside of the field, the confirm password error shows.
(this happens with any fields support confirmation field)
https://github.com/user-attachments/assets/809a7105-42ce-443d-b4bc-4c5d71bbb7b9
**After this fix:**
The confirmation validation only triggers when submit form or when the value of the confirmation field changes and then loses focus.
https://github.com/user-attachments/assets/54cd1b07-ecb8-4159-8e78-d6d2e61a58d9

Do not validate confirmation field when main field loses focus

---

classes/controllers/FrmAppController.php
classes/controllers/FrmHooksController.php
css/frm_admin.css

Closes https://github.com/Strategy11/formidable-pro/issues/5178
Here we are removing all admin notices that was added by third parties in our admin pages only.
Use the following snippet:
```
add_action( 'admin_notices', 'test_ahmed' );
function test_ahmed() {
?>
<div class="tesssssssssssssst" style="background-color: red;color: white;">
<h1>This is a test notice.</h1>
</div>
<?php
}
```
And visit any form settings page or any formidable page, you will see this notice and this causes some UI problems.
With the above code activated, you shouldn't see the admin notice in our pages at all.

Hide all admin notices that wasn't added by our code (core and addons) from our pages

---

classes/models/FrmField.php

Fixes https://github.com/Strategy11/formidable-pro/issues/5064
Following up from a previous PR https://github.com/Strategy11/formidable-forms/pull/1746. That solution wasn't ideal as it didn't fix the problem and just changed how fields were queried in the form builder to avoid the problem.
The issue here is that the cached object has only a single backslash and then gets passed through `wp_unslash` in `FrmField::getAll`.
In the database, the backslash is already saved as two backslashes (`\\`). When `field_options` are unserialized, the two backslashes become one `\`.
This update makes sure that if the field options have already been unserialized, that we add slashes to the object before it is cached, so the cached result includes the expected double backslashes (`\\`).
The data should …

Fix pro issue 5064 / Fix format unslashing issue in field cache

---

js/formidable_admin.js

Laura noted this in QA https://github.com/Strategy11/formidable-forms/pull/1963#issuecomment-2371697547
If you search for "signatures", it won't match "signature".
This update adds a little check for basic plural matches. I basically do a second check if the `item's value + 's'` matches.
I have a couple small checks in place so searching `'s'` on its own wont return every field, and if you search `ss` it won't match everything with a single `s`.

Allow field search to also match plural

---

classes/models/FrmFieldFormHtml.php

Fix https://github.com/Strategy11/formidable-pro/issues/5395
The changes made in this pull request involve a modification to the add_field_div_classes method in the FrmFieldFormHtml class. A conditional check is introduced to determine if the field type is 'summary'. If true, the method updates the HTML output by appending additional classes to the existing class string. This adjustment specifically targets how classes are rendered for summary fields within the form.
1. Create a form and add few fields and then a Summary to field to it.
2. Add a class to the Summary field using the field options. Ex. `frm_half`
3. Save and Preview the form.
4. Confirm that the classes added are effectively styling the field.

Add css classes to summary field

---

classes/models/FrmFieldFormHtml.php

Reverts Strategy11/formidable-forms#2005
I merged this before really looking at https://github.com/Strategy11/formidable-pro/pull/5396
I'm concerned this will drop labels from all summary fields for all forms.
I think we might need to come up with a migration or something to fix the data issue.

Revert "Add css classes to summary field"

---

classes/controllers/FrmSimpleBlocksController.php

**Related ticket** https://secure.helpscout.net/conversation/2723585835/211506
This just adds a small check in case the query for add-ons data fails and the views data is unavailable.
```
PHP Warning:  Trying to access array offset on value of type bool in /var/www/src/wp-content/plugins/formidable/classes/controllers/FrmSimpleBlocksController.php on line 55
PHP Warning:  Trying to access array offset on value of type null in /var/www/src/wp-content/plugins/formidable/classes/controllers/FrmSimpleBlocksController.php on line 55
```

Add type check to avoid php warning

---

classes/helpers/FrmFieldsHelper.php
classes/views/frm-form-actions/email_action.php

**Related Slack conversation** https://strategy11.slack.com/archives/C799A2R61/p1727465741085109
New email actions now use `[default-email]` and `[default-from-email]` shortcodes.
These settings are currently only set in the onboarding wizard. You can find them at the `/wp-admin/admin.php?page=formidable-onboarding-wizard` URL.
When these settings are empty or not valid emails, the admin email is used instead.

Fix default email setting is never used

---

classes/controllers/FrmAppController.php
css/admin/frm_admin_global.css

Fixes https://github.com/Strategy11/formidable-pro/issues/5404

Pro issue 5404 / Black friday

---

css/admin/deactivation-feedback.css
css/frm_grids.css

**Related issue** https://github.com/Strategy11/formidable-pro/issues/4839
This just removes some old CSS that we no longer need. This is already covered by the other `clip-path: inset(50%);` line.

Drop old vendor prefix webkit clip path

---

css/admin/deactivation-feedback.css
css/frm_grids.css

Fixes https://github.com/Strategy11/formidable-pro/issues/4839
`clip` is now deprecated. The current `clip-path: inset(50%);` should cover this already. Just removing this should be fine.
It's only used in screen reader text, which I didn't see any issues with.

Drop old clip css

---

css/frm_admin.css

Related issue: https://github.com/Strategy11/formidable-ai/issues/73
The tooltip icon color is overridden by `.frm_has_shortcodes .frmsvg` and this update just fixes that.
**Before**
**After**:

Make tooltip icon color used in shortcode inputs consistent

---

classes/helpers/FrmAppHelper.php

This cleans up some logic. Now `php_version_notice` actually just checks for the PHP version.
I don't think we need an IE notice anymore. We should assume no one is using it.

Remove IE notice

---

js/formidable.js

Fixes https://github.com/Strategy11/formidable-pro/issues/5427
[formidable-6.15.1b.zip](https://github.com/user-attachments/files/17346333/formidable-6.15.1b.zip)
It looks like this would have been interested in v6.12 when a change to use vanilla JS from jQuery was made. I didn't know the field container might not always exist here.

Fix pro issue 5427

---

classes/controllers/FrmOnboardingWizardController.php
formidable.php

…sient
Fixes https://github.com/Strategy11/formidable-pro/issues/5411
Now we only avoid redirecting immediately when we are not bulk-activating. If the plugin is activated when bulk-activating, we fallback to the old behaviour, where we check for a Formidable admin page.

Redirect immediately to onboarding when activating a single plugin

---

classes/controllers/FrmAppController.php
classes/controllers/FrmOnboardingWizardController.php
cypress.config.js
js/packages/floating-links/s11-floating-links.js
tests/cypress/e2e/Applications/validateApplicationsPage.cy.js

- Path checks in applications tests have been modified to remove the `formidable-forms` slug from the check. In many cases, the `formidable` name is used instead.
- The alert role has been added to the slidein message to improve accessibility. A new slidein message appearing when running e2e tests is catching an accessibility issue with the slidein popup that we don't have in our exception list.
- `experimentalRunAllSpecs` is now set. This allows you to run all specs when using Chrome.

Get cypress passing

---

css/frm_admin.css

Related update: https://github.com/Strategy11/formidable-pro/issues/5297
**Design reference**: https://github.com/Strategy11/formidable-pro/issues/5297#issuecomment-2352925483
**Before**:
**After**:

Change the UI/UX of conditional logic elements

---

classes/models/FrmEntryMeta.php

Default inner joins are more efficient and we have no reason to do a left outer join in this case since we're querying by field key, so we expect the field row to exist.
I also added some comments to make this all easier to read/follow.

Stop using left outer join for meta query

---

classes/helpers/FrmStylesHelper.php
classes/views/styles/_quick-settings.php
classes/views/styles/_style-options.php
css/admin/style-components.css

Fixes https://github.com/Strategy11/formidable-pro/issues/5377

improve primary color from quick settings style editor

---

js/formidable.js

Related Slack conversation https://strategy11.slack.com/archives/C799A2R61/p1729107464507059
Now if the form immediately becomes visible (within the next second), the captcha will still render.

Try to render captcha a second time on a timeout

---

classes/controllers/FrmAppController.php
classes/models/FrmSettings.php

I think these warnings have been in the plugin for long enough and don't need to be here long term.
It goes back to v6.1, from Feb 23, 2023.

Drop IP warning from settings

---

classes/controllers/FrmInboxController.php
classes/views/frm-form-actions/_email_settings.php
js/formidable_admin.js

This code is still used for the dashboard inbox.
I'm just removing the references to the inbox page. The footer listeners here seem like they are best removed.
I also fixed an issue where the active campaign sign up wouldn't actually work after dismissing every inbox item.

Drop more inbox page code

---

classes/controllers/FrmAddonsController.php
classes/controllers/FrmAppController.php
classes/models/FrmReviews.php
js/admin/applications.js
js/admin/embed.js
js/admin/style.js
js/formidable_admin.js
stripe/helpers/FrmTransLiteListHelper.php

Hi,
This PR improves the JavaScript i18n of the plugin with the below items:
<hr>
Here is a screenshot of the dropdown as currently is:
Here is a screenshot after adding `wp_set_script_translations( 'formidable_admin', 'formidable' );`
<hr>
Fixes #2033

[I18n] Fix issues and add improvements to JavaScript internationalization

---

classes/controllers/FrmAddonsController.php
classes/controllers/FrmAppController.php

This fixes issues with the "headers already sent" PHP warning when trying to redirect using the submenu links.

Fix redirect issues for upgrade and black friday

---

classes/helpers/FrmFieldsHelper.php

Related ticket https://secure.helpscout.net/conversation/2744881693/213579?
They didn't include a full message, but if I pass null to `$subject`, I get this message (in PHP 8.3) which matches what they sent.
> Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated
This is called in various places. Rather than trying to handle the null check everywhere this is called, it's easier to just put a null check in this function.
If the value is null, we don't need to modify it in this function.
[formidable-6.16.1b.zip](https://github.com/user-attachments/files/17523318/formidable-6.16.1b.zip)

Check for null in sanitize_embedded_shortcodes

---

classes/controllers/FrmStylesController.php

I'm using a PHP 8.4 release candidate now.
This update keeps `$css` as an array, to help avoid conflicts with code like our Authorize.Net add-on that expects `$css` to be an array.
> PHP Deprecated:  Automatic conversion of false to array is deprecated in /var/www/src/wp-content/plugins/formidable-authorize-net/controllers/FrmAuthNetController.php on line 78

Disable form CSS in visual styler more safely

---

classes/views/frm-forms/add_field_links.php
css/frm_admin.css

We have this "NEW" text in our payments submenu.
But I was think we might draw more attention to payments as well if we put a "NEW" flag directly beside the Payment field as well.
I put this behind a check so it doesn't appear if you have a payments table already installed. This would apply to anyone using the PayPal add-on, Authorize.Net, or anyone who has used Stripe already.

Add "NEW" to payment field

---

classes/controllers/FrmFormsController.php
classes/helpers/FrmAppHelper.php
classes/helpers/FrmFormsHelper.php
classes/helpers/FrmFormsListHelper.php
classes/views/frm-entries/direct.php
classes/views/styles/_manage-styles-row.php
classes/views/xml/import_form.php
classes/widgets/FrmElementorWidget.php
js/formidable_admin.js

Fix https://github.com/Strategy11/formidable-pro/issues/5442
1. Create a form from Template, Formidable > Forms > Add New and pick a template clicking on 'Use template'.
2. Try saving the form and confirm that the form name modal doesn't appear as the form is already named by the template name.

Add a check for current form name (no title) to show the form name modal

---

classes/controllers/FrmApplicationsController.php
classes/models/FrmApplicationTemplate.php
classes/models/FrmStyle.php

Now if a template is missing both `url` and a required license, it is omitted from the Applications page.
This helps avoid this "requires false plan" message.

Exclude invalid applications on applications page

---

css/admin/applications.css
js/admin/applications.js

Fix https://github.com/Strategy11/formidable-pro/issues/5328
**Design** by Razvan: https://github.com/Strategy11/formidable-pro/issues/5328#issuecomment-2332233644
1. Go to Formidable -> Applications and confirm that the 'NEW' badge and Add/Learn more buttons are inline with the Application title and hovering on the cards would switch between the badge and buttons.
2. Confirm that Applications with a really long name are truncated with `...` but the buttons are always appear inline with it.

Enhance UI/UX of Application cards

---

classes/helpers/FrmAppHelper.php
classes/helpers/FrmFieldsHelper.php
classes/models/fields/FrmFieldType.php

Related ticket https://secure.helpscout.net/conversation/2744881693/213579/
If an array contains arrays and it is passed to the second parameter of `implode` an "Array to string conversion" warning is logged.
[formidable-6.16.1b.zip](https://github.com/user-attachments/files/17557272/formidable-6.16.1b.zip)

Make implode code safer

---

classes/controllers/FrmHooksController.php

Some of these were registered in the wrong place.
This should help cut back on the number of hooks on a normal admin page load, slightly.

Move AJAX hooks into load_ajax_hooks function

---

js/formidable_admin.js

I noticed this error that happens in the visual views editor when you click the conditional tab and there are no fields or no form is selected.

Check tab content exists before making visible

---

changelog.txt
classes/controllers/FrmFormsController.php
classes/helpers/FrmSubmitHelper.php
classes/models/FrmForm.php
readme.txt

Fix https://github.com/Strategy11/formidable-pro/issues/5459
1. Create a form and add a field to it.
2. Then click on the Submit button in the builder page and then click on "Update" button at the top right.
3. When the page reloads, confirm that the Submit button's position/order is not changed.
**Before**:
**After**

Fix submit button auto order change

---

classes/views/frm-entries/form.php

Related Slack conversation https://strategy11.slack.com/archives/C799A2R61/p1731506429943149
Payment forms by Paystack has a global `input` shortcode, which is a pretty horrible practice 😅.
This update unregisters `[input]` before we render our form fields which rely on this internal shortcode. Then we re-apply it back after so it doesn't break Paystack.

Temporarily remove input shortcodes when rendering forms fix

---

changelog.txt
readme.txt

It looks like I need a new stable tag to bump the tested to version now.

Prepare for v6.16.1.2

---

js/formidable.js

This chips away at some jQuery code. It removes a use of `.find` and a use of `.filter`.

Stop using jQuery for required field validation

---

js/formidable.js

The goal of this update is to make it easier to tell where jQuery is being used and where it isn't. This code can be a bit hard to get the type from at a glance.

Add some JS doc type comments

---

classes/models/FrmFieldValueSelector.php

This update adds a `truncate` option to field selectors so you can overwrite the default `25`.
Related PR https://github.com/Strategy11/formidable-pro/pull/5485

Add truncate option to FrmFieldValueSelector

---

js/formidable_admin.js

I noticed an error when I tried to bulk delete a group of fields that included a field I had just deleted.

Make frm_after_delete_field hook safer

---

classes/controllers/FrmFieldsController.php

The code right above this sets `'data-placeholder' => 'true',`, so setting it again is just extra code that doesn't add anything.

Remove some redundant code

---

classes/controllers/FrmFormsController.php
classes/models/FrmForm.php

This exits early if it tries to trash a form that is already trash, and prevents it from showing a message again if you try to refresh the page.

Improve bulk form trash

---

classes/models/FrmField.php
classes/models/fields/FrmFieldType.php

Fixes https://github.com/Strategy11/formidable-pro/issues/5296

Pro issue 5296 / stop decoding default values for non-array types

---

classes/models/fields/FrmFieldRadio.php

Since this is getting checked more aggressively, we want this property to be more leniant.
Checkboxes can be changed to Radio buttons, so it's possible we might run into array-like data that we want to decode for a radio button.

Allow arrays for radio type

---

css/admin/dashboard.css

I had a long entry, and it caused the table to pretty much break.

Allow word breaking on dashboard entries table

---

classes/helpers/FrmStylesHelper.php

Related Slack conversation https://strategy11.slack.com/archives/C799A2R61/p1732218176807229
This should help prevent broken CSS issues.

Strip unexpected characters from CSS output var names

---

classes/helpers/FrmAppHelper.php
classes/views/frm-entries/_sidebar-shared-pub.php
tests/cypress/e2e/Entries/EntriesPageDataValidations.cy.js

Fixes https://github.com/Strategy11/formidable-pro/issues/5418
Now I'm using our more commonly used `get_formatted_time` function that adds the time data, and some custom logic for the date format (I change long month names to the short month name so if you have it set to show "November", it will show "Nov" instead to save space).
This generally uses the WordPress setting, and not our global setting in Pro, as the Pro settings are all formats like `Y/m/d` and `Y-m-d`, none of which look as good as the more verbose format options that you can use in the WordPress date setting.
The `@` is now `at` by default, but I think that's okay. It makes it more consistent with our other dates with times which is more important than the possible space saved.
**Using the following settings** _These are …

Pro issue 5418 / Use WordPress date and time settings for entry timestamp in edit/view entry sidebar

---

css/frm_admin.css

It looks like the others marked as deprecated are all still used somewhere.

Drop unused deprecated CSS var

---

css/frm_admin.css

I can see references to this back in v4.0, but not in newer versions.

Remove CSS for frm_right_addon

---

classes/controllers/FrmAppController.php
classes/controllers/FrmFormsController.php
classes/controllers/FrmHooksController.php
classes/views/frm-forms/add_form_style_options.php

This `frm_add_form_style_tab_options` hook is now deprecated.
This update stops calling `FrmFormsController::add_form_style_tab_options` on this hook.
I also deprecated and cleared out the view file it renders.

Deprecate more code

---

classes/helpers/FrmFieldsHelper.php

**Related ticket** https://secure.helpscout.net/conversation/2774027191/216280
[formidable-6.16.3b.zip](https://github.com/user-attachments/files/17925759/formidable-6.16.3b.zip)
> Unsupported operand types: array + string in /var/web/site/public_html/wp-content/plugins/formidable/classes/helpers/FrmFieldsHelper.php:2117 PHP Stacktrace:

Fix fatal error when field options is a string fix

---

classes/controllers/FrmHooksController.php
tests/phpunit/misc/test_FrmMisc.php

Related WP update https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/
After reading into this, it sounds like `init` is the right hook, not `plugins_loaded`, for loading translations.
I used `0` here because translations need to load before we register form actions.

Load lang on init hook

---

classes/models/fields/FrmFieldType.php

Fixes this message I was seeing in my logs.
> PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/src/wp-content/plugins/formidable/classes/models/fields/FrmFieldType.php on line 1094

Improve support for null when preparing esc value

---

classes/helpers/FrmAppHelper.php
classes/models/FrmMigrate.php

This significantly improves the queries for entry count, which happen a lot.
From 0.2021 to 0.0651 is a 68% reduction.
**Before**
**After**

Add another index to entry items table

---

classes/models/FrmEntry.php
classes/models/FrmEntryMeta.php
js/formidable.js

**Related ticket** https://secure.helpscout.net/conversation/2765614867/215349/
**The issue**
Reopening a page on an iPhone re-submits the POST request. Our duplicate check defaults to 60 seconds, but it's likely someone will open a page again hours later, maybe even days later.
**The solution**
I'm adding a unique string that gets added right before the form is submitted.
If this string is detected, it is checked in the duplicate check, and saved to entry meta under field 0, serialized as an array like `a:1:{s:9:"unique_id";s:9:"a34d2ypgn";}`.
When this exact item meta row is detected, during the duplicate check, it will return true immediately if there is a match.
The refresh events don't re-trigger the JavaScript, so all of these requests will send the same unique string. …

New duplicate check

---

classes/controllers/FrmUsageController.php
classes/models/FrmUsage.php

Fixes https://github.com/Strategy11/formidable-pro/issues/4291
To test, you can use the WP Crontrol to see the list of scheduled events, turn on and off the Send usage feature in the Miscellaneous tab in the Global settings and check if the `formidable_send_usage` event is added or removed.

Unschedule send usage event if it is disabled

---

classes/models/FrmEntry.php
classes/models/FrmEntryMeta.php

This fixes an issue with repeater entries failing to validate after merging the new unique ID validation check.

Memoize unique match result and stop adding meta for repeater entries

---

css/frm_admin.css

The pagination inputs are all off because of this padding. The bulk action dropdown also looks better without this rule.
It looks like this was added in v6.0. I'm not sure what it was trying to fix, but I don't think we need this, and having Firefox-specific styles isn't something we really want either.

Drop padding top firefox-specific style

---

js/formidable.js

I noticed this while trying to replace jQuery code. This line isn't required at all.
This logic should have been setting `action =`, but instead just gets the value and does nothing with it.
Since this has always been this way, I don't think we need this code. This function is really only called by `checkFormErrors` which isn't referenced in our documentation or other plugins, and it uses the same logic more-or-less to get the action before it gets sent to this function.

Remove some code that does nothing

---

js/formidable.js

I could only find references to this in old Lite code (pre 3.0). It looks like it was really used to toggle elements in the back end.
I think we should be good to remove these functions. For now, I'm deprecating them just in case.

Deprecate old JS functions

---

js/formidable.js

It doesn't look like there's any reason for this variable to be declared for the whole function wrapper.

Remove action var from wrapper function scope

---

js/formidable.js

This removes a reference to `.closest()` and `.hasClass`.

Remove jquery when validating on change

---

css/_single_theme.css.php

These were referenced when we were using font icons on the front end.
When we removed the references, the variables were left behind.

Drop unused vars minus icons and arrow icons

---

css/font_icons.css

It looks like this hasn't been referenced in a long time.

Drop references to old class frm_dashicon_font

---

classes/controllers/FrmApplicationsController.php
classes/views/frm-forms/add_field.php
css/frm_admin.css

Fix https://github.com/Strategy11/formidable-pro/issues/5504

Stop using font icon in section field icons in form builder

---

classes/models/FrmSettings.php
classes/models/FrmUsage.php
classes/views/frm-settings/misc.php

As well as "Accordion JS" and "Old CSS", which were removed even longer ago.
There's also a small database query optimization.

Drop old references to use HTML and jQuery CSS settings

---

classes/models/FrmUsage.php

Two small tracking updates related to our Bootstrap add-on.
1. `btsp_errors` is old and has been removed for some time.
2. `btsp_version` is newer, and isn't being tracked yet.

Update tracking for bootstrap settings

---

classes/views/frm-form-actions/_action_inside.php
classes/views/frm-form-actions/_email_settings.php
css/frm_admin.css
js/formidable_admin.js

Fix https://github.com/Strategy11/formidable-pro/issues/5103
Quoting the third item in the checklist from the issue:
> 3. Tooltip appears outside the input field when sending email (https://imgur.com/95zn8IO / https://imgur.com/WWApGOX). It can be confusing when wanting to remove CC or BCC and hovering over the remove icon where it shows the add CC/BCC tooltip (https://imgur.com/6LfXmsy). See https://github.com/Strategy11/formidable-pro/issues/5103#issuecomment-2488774002 for a new design update
**Design reference:**
https://github.com/Strategy11/formidable-pro/issues/5103#issuecomment-2488774002

Use tooltip icons to show tooltips rather than label/input elements

---

classes/controllers/FrmAppController.php

This ends today. We don't need this code anymore.

Remove some black friday code

---

classes/models/FrmUsage.php

Fixes https://github.com/Strategy11/formidable-pro/issues/5519

Include license type in usage data

---

classes/helpers/FrmFieldsHelper.php
classes/helpers/FrmFormsHelper.php

Related ticket https://secure.helpscout.net/conversation/2784288062/217416
[formidable-6.16.3b.zip](https://github.com/user-attachments/files/18062348/formidable-6.16.3b.zip)

Fix string offset access of string issue

---

classes/controllers/FrmSimpleBlocksController.php

Related issue https://github.com/Strategy11/formidable-chat/issues/111
When title/description are disabled from the Gutenberg block, it would fallback to the form settings. This update passes the `false` so it doesn't use a default instead.

Fix simple block title/description options not working properly when off

---

js/formidable.js

I found this being used in old v2.0 code. But it hasn't been used since v3.0+.

Deprecate unused function frmFrontForm.escapeHtml

---

stripe/controllers/FrmStrpLiteEventsController.php

I don't think this message benefits us at all.

Remove Stripe subscription webhook log message

---

classes/controllers/FrmFormsController.php

**Related ticket** https://secure.helpscout.net/conversation/2790635195/217940
[formidable-6.16.4b.zip](https://github.com/user-attachments/files/18127914/formidable-6.16.4b.zip)
This just prevents some PHP warnings. It doesn't fix a bug (that there is no form getting created).

Add object checks to form variables

---

classes/helpers/FrmFormsListHelper.php

I added a null in my database when testing and now I see this deprecated message.
> PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/src/wp-content/plugins/formidable/classes/helpers/FrmFormsListHelper.php on line 410

Add null check for form name

---

js/formidable.js

This update removes a use of the jQuery `.hide()` function, as well as `.find()`, and 2 uses of `.closest()`.
This also updates a lot of uses of `let` to `const`, removes some quotes around object keys, and I added some type comments. I also optimized the rendered check, so it happens before we do everything else.
And it fixes a bug. The code was intended to hide the invisible captcha field's label, but the `.closest()` call was incorrect and it would never select anything.

Stop using jQuery in captcha render code

---

classes/models/fields/FrmFieldType.php

Fixes https://github.com/Strategy11/formidable-pro/issues/5559
[formidable-6.16.4b.zip](https://github.com/user-attachments/files/18276385/formidable-6.16.4b.zip)

Avoid stripping data from radio button/checkbox options

---

classes/models/FrmField.php

This simplifies/optimized a query by checking only for the relevant `id` or `field_key`, since field keys are always alphanumeric.

Optimize field type queries

---

classes/models/FrmField.php

I don't believe we need these `LEFT OUTER` joins since we should always expect the forms to exist when querying for fields. The `LEFT OUTER` joins are much slower than the default join.

Optimize field queries

---

classes/controllers/FrmAppController.php
classes/controllers/FrmEntriesController.php

The issue is that the hooks are not getting added properly when there are inbox items.

Fix broken e2e tests

---

classes/helpers/FrmCSVExportHelper.php

**Related ticket** https://secure.helpscout.net/conversation/2809125713/219105
```
add_filter(
'frm_csv_export_batch_size',
function() {
return 100;
}
);
```
**The issue**
- CSV Exports are slow.
**The solution**
- I added a filter to allow for a custom batch size. I was seeing a ~13% speed improvement by using 100 instead of 20.
- I optimized the entry query when Pro is not installed since "parent item ids" are not relevant in a Lite form.
**The result**
CSV Exports for the Locations List (50k+ entries, 7 fields) decreased from 55s to 46s, when Pro is not active.

Add CSV export batch size filter and optimize entries query when Pro is not installed

---

classes/controllers/FrmInboxController.php
classes/models/FrmAddon.php
classes/models/FrmInbox.php
classes/views/form-templates/modals/leave-email-modal.php
tests/cypress/e2e/Form Templates/FormTemplates.cy.js

This PR ensures that the Dashboard Inbox refreshes correctly under the following scenarios:
- When the Pro plugin is activated or deactivated.
- When the license is connected or disconnected.
Additionally, this fix updates the number of free templates displayed from 20+ to 30+ where applicable.
https://github.com/Strategy11/formidable-pro/issues/4909
https://github.com/Strategy11/formidable-pro/pull/5566
1. Activate and deactivate the Pro plugin and confirm the Dashboard Inbox refreshes as expected.
2. Connect and disconnect the license and confirm the Dashboard Inbox refreshes properly.
3. Verify that the number of free templates updates from 20+ to 30+ after the changes.
https://share.cleanshot.com/DVQySkxc

Dashboard Inbox doesn't refresh properly

---

classes/helpers/FrmStylesHelper.php
css/_single_theme.css.php
tests/phpunit/styles/test_FrmStylesHelper.php

Fix https://github.com/Strategy11/formidable-pro/issues/5557
Quoting Mike's workaround the issue implemented in this PR:
> We should check for this, and use the bottom value.
> 
> So if the submit_margin has 2 units (vertical, horizontal), we want to use the first value (10px in this case). If there are 4 (top, right, bottom, left), we'll want to use the bottom value (the 3rd one).

Fix centered submit button bottom margin value with modern dark theme

---

classes/helpers/FrmCSVExportHelper.php

Related Slack conversation https://strategy11.slack.com/archives/C799A2R61/p1736421684781099

Add utf8 with bom csv export option

---

classes/models/fields/FrmFieldEmail.php

Fix https://github.com/Strategy11/formidable-pro/issues/5527
This update just adds an extra check to valid email values so that if there is a `.` at the end of the email local part (just before `@`), it would be treated as an invalid value.
1. Create a form and add an email field to it.
2. Preview the form and fill the email field with a value that has `.` just before the `@` symbol.
3. Try submitting the form and confirm that an error is thrown indicating an invalid email value.

Improve email validation

---

classes/controllers/FrmFormsController.php

Fixes a failing unit test in php 7.4: https://github.com/Strategy11/formidable-pro/actions/runs/12711625531/job/35435346578?pr=5544. I noticed it while running unit tests in this PR: https://github.com/Strategy11/formidable-pro/pull/5544

fix failling unit test in php 7.4

---

classes/controllers/FrmFormsController.php

This update unsets the `content` if neither condition is hit. This way the output is more consistent with the previous versions.
Related Pro tests failing.

Unset empty response content

---

.github/workflows/push-deploy.yml

New issue with ubuntu latest https://github.com/10up/action-wordpress-plugin-deploy/issues/158#issuecomment-2564633557
SVN is no longer included.

Update deploy workflow

---

classes/controllers/FrmEntriesController.php

With the new inbox counts it's possible to see the screen options on some pages where we're trying to hide them (View/Edit entry).
This issue isn't major but it's good to fix.

Remove screen options on entry edit page

---

classes/controllers/FrmSimpleBlocksController.php
css/_single_theme.css.php

Fix https://github.com/Strategy11/formidable-pro/issues/5552

Output custom css classes when rendering forms

---

classes/views/frm-settings/general.php
classes/views/frm-settings/misc.php

According to our tracking this setting is enabled about 1% of the time, so it's being moved to Misc settings.

Move admin bar global setting to misc

---

js/formidable.js

Related ticket https://secure.helpscout.net/conversation/2825361874/220419
[formidable-6.17.2b.zip](https://github.com/user-attachments/files/18496525/formidable-6.17.2b.zip)
> Uncaught TypeError: response.replace is not a function
This would imply `response` was `null`, and `defaultResponse` was being used instead.

Fix response replace is not a function error

---

stripe/models/FrmTransLiteAction.php

This was reported in https://github.com/Strategy11/formidable-acf/pull/80#pullrequestreview-2565740712

Remove submit field from payment settings

---

classes/models/FrmUsage.php

This was reported by Mike via private message in Slack.
In Lite and Pro plugins, we send the `Message Defaults` settings to the usage endpoint. But in the new usage tracking endpoint, I skipped those settings because they are long and I didn't think we wanted to track them.
Our purpose is to track when those settings are changed. So I created this PR. I will send `changed-{$message_key}` to the endpoint. It has the value `0` (not changed) or `1` (changed).
In the usage endpoint, I removed the code that skips the messages: https://github.com/Strategy11/ff-usage-2/pull/2
The similar PR in Pro: https://github.com/Strategy11/formidable-pro/pull/5603

Track when message settings changed

---

phpstan.neon

This helps to improve our coverage in other files that do not have these issues.

Move some phpstan exceptions to problematic files only

---

js/formidable_admin.js

I noticed when searching fields, the section titles were disappearing.
It was because of this JS error introduced in v6.16.3.

Fix JS error when searching fields

---

css/_single_theme.css.php

Fix https://github.com/Strategy11/formidable-pro/issues/5564
Before:
After:

Add error style to checkbox and radio fields when there is error with them

---

js/formidable_admin.js

Fix https://github.com/Strategy11/formidable-pro/issues/5224
This is just an implementation improvement than a feature to test. We have been unselecting selected text after fields are multiselected but we are now preventing text selection at the first place.

Avoid selecting text when multiselecting fields

---

classes/helpers/FrmAppHelper.php
css/frm_admin.css
js/admin/applications.js

Razvan left some design improvements in https://github.com/Strategy11/formidable-forms/pull/2173#issuecomment-2589264588
This fixes https://github.com/Strategy11/formidable-pro/issues/5596.

Lite to pro design update

---

tests/cypress/e2e/Forms/formPageDataValidation.cy.js

This is related to the Lite to Pro changes. The anchor tag is no longer a direct children, but a child of a new wrapper element.

Fix cypress upgrade bar issue

---

classes/models/fields/FrmFieldNumber.php

**Pro PR:**
https://github.com/Strategy11/formidable-pro/pull/5618

Lite Version: Fix number field step validation

---

changelog.txt
readme.txt

Add more change log items

---

classes/models/FrmSettings.php
js/formidable.js
psalm.xml

These extra checks were only really required for supporting IE and can now be removed.

Simplify tab event logic

---

js/formidable.js

This update removes a use of `.find()` and `.length`.
I also dropped a lot of variables. Using `.forEach`, we don't need to handle all of the loop variables ourselves.

Use less jquery when validating

---

classes/models/fields/FrmFieldUserID.php

Fixes https://github.com/Strategy11/formidable-views/issues/28
The issue, is that this call to `intval` changes `''` to `0`, which we don't want. Keeping it blank is better.
I tested with this basic CSV. My form has a "Text" field, and a User ID field. The User ID field isn't in the CSV, since we're trying to import empty.
[250218182012_user-id-test_formidable_entries.csv](https://github.com/user-attachments/files/18851714/250218182012_user-id-test_formidable_entries.csv)

Fix views issue 28

---

js/formidable.js

Fixes https://secure.helpscout.net/conversation/2854926075/223538
[formidable-6.18.1b.zip](https://github.com/user-attachments/files/18888672/formidable-6.18.1b.zip)

Fix turnstile does not properly reset on AJAX error

---

js/formidable.js

Fixes https://secure.helpscout.net/conversation/2855293169/223561
[formidable-6.18.1b.zip](https://github.com/user-attachments/files/18893607/formidable-6.18.1b.zip)

Fix js error when triggering change event on hidden field

---

classes/helpers/FrmAppHelper.php

Suggestion by Mike in https://github.com/Strategy11/formidable-views/pull/625#discussion_r1963812162

Only localize scripts once

---

css/admin/style.css

Fix https://github.com/Strategy11/formidable-pro/issues/5659
There seems to be a forced style in the latest core (`common.css`) which affected this.
I have also moved a Views editor style from here to a Views editor style file in https://github.com/Strategy11/formidable-views/pull/628
```
.accordion-container h3.accordion-section-title {
padding: 0 !important;
}
```
**After**:

Fix accordion style

---

classes/models/FrmField.php

> PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /Users/mikeletellier/Local Sites/dev-site/app/public/wp-content/plugins/formidable/classes/models/FrmField.php on line 1099
This comes up with GDPR fields because the default value is `null` but this check expected a `non-array` to be a string.
This just tweaks the type check so it's safer.

Fix deprecated message when loading gdpr field settings

---

classes/controllers/FrmFormsController.php
classes/helpers/FrmFormsHelper.php
classes/views/frm-forms/settings-advanced.php

We don't need the old checks anymore. v6.2 is old enough, going back to Apr 6, 2023.

Remove old ajax submit compatibillty code

---

css/frm_admin.css

Fixes this styling issue that Goncalo was seeing on our site.

Hide extra accordion arrows

---

classes/helpers/FrmAppHelper.php
classes/helpers/FrmSerializedStringParserHelper.php

Related ticket https://secure.helpscout.net/conversation/2881045066/225606
The serialized data just isn't valid, and the parsing is getting it partially right but it's problematic.
This update filters the data if it looks invalid, and only uses what appears to be valid.
This update checks for 2 substrings that appear in the customer's data. When using `unserialize`, I just get back `false`.
There's also a small deprectred messaged fix for if your form `description` is `null` as well. I'm seeing this because I inserted the row into the DB manually and didn't add a value.
[formidable-6.19.1b.zip](https://github.com/user-attachments/files/19435518/formidable-6.19.1b.zip)
**_Tested and confirmed by Dimitris_**

Validate serialized data that appears to be broken

---

classes/controllers/FrmHooksController.php
classes/helpers/FrmAppHelper.php
classes/models/fields/FrmFieldGdpr.php
classes/views/frm-fields/back-end/settings.php

Fixes the customer's issue in https://github.com/Strategy11/formidable-pro/issues/5708
It is possible for the GDPR field to not be required. I can at least replicate this by adding a field, disabling the GDPR setting, save the field, and then enabling it again. Since it is read only you end up with a checkbox that is uncheckable and unchecked.
This update always sets the checkbox to appear as checked if the `readonly_required` setting is on. When this is on, we expect it to always be checked. I don't see us requiring a readonly disabled checkbox since we would likely just hide the setting in those cases.
I also added a check so it always does the required validation even when unchecked, and the required asterisk will still show even when unchecked. …

Make gdpr field required even if the setting is disabled

---

classes/views/frm-fields/front-end/gdpr/gdpr-field.php

Related ticket https://secure.helpscout.net/conversation/2891604879/226396
It's common to link to Terms and Conditions in a field like our GDPR one.
However, because this was using `esc_html`, links were not working.
[formidable-6.19.1b.zip](https://github.com/user-attachments/files/19534949/formidable-6.19.1b.zip)

Allow links in GDPR agreement text

---

classes/controllers/FrmFormActionsController.php
classes/controllers/FrmHooksController.php

Related ticket https://secure.helpscout.net/conversation/2885530761/225900
[formidable-6.19.1b.zip](https://github.com/user-attachments/files/19540029/formidable-6.19.1b.zip)
This update helps to prevent WPML from filtering our form actions, so they work as expected.

Fix wpml compatibility issue

---

classes/controllers/FrmFormActionsController.php

- Stop trying to run actions if the form is not an object after calling `FrmForm::maybe_get_form`.
- Simplifying the `$child_entry` declaration line. It has an `isset &&` check that is now reduced to a `! empty`. I also dropped the `Is_object` check, as it now happens earlier and this could would never be reached with an invalid form object.

Fix up some action code

---

js/formidable.js

This update removes another use of `.find()`, `.closest`, and `.each()`.

Use less jquery when validating required radios

---

js/formidable.js

This drops some more complicated jQuery, removing `.scrollTop`, and `.animate`.

Stop using jQuery when changing window scroll positions

---

classes/controllers/FrmUsageController.php
classes/helpers/FrmAppHelper.php

Fixes https://github.com/Strategy11/formidable-pro/issues/5722
This function was all messed up. It was copied from the usage controller, but that has a different context.
1. It was checking for the trash page and returning false, so sorting on the trash page was not possible.
2. It was missing the delete action.
I also fixed the usage controller logic, so it doesn't miss the delete action either.

Fix sorting issues

---

classes/controllers/FrmFormsController.php
css/frm_admin.css

Fix https://github.com/Strategy11/formidable-pro/issues/5728
Go to different WP admin pages that are not Formidable pages and confirm the 'More on bigger devices' message does not appear anywhere on the page.

Limit pages small device message appears in

---

changelog.txt
readme.txt

Drop some changelog items

---

js/formidable_admin.js

Related ticket https://secure.helpscout.net/conversation/2911273467/227892
> Javascript Message: Uncaught TypeError: Cannot set properties of null (setting \’value\’) – URL: https://mywebsite.com/wp-content/plugins/formidable/js/formidable_admin.js?ver=6.20 – Line: 2239
No clue how to replicate this since any field allowed in a field group supports layout classes.
[formidable-6.21b.zip](https://github.com/user-attachments/files/19794945/formidable-6.21b.zip)

Check classes input exists before setting value

---

classes/controllers/FrmFormsController.php

Fix https://github.com/Strategy11/formidable-pro/issues/5760
1. Delete a form
2. Go to trash list and confirm that 'Actions' tab is not available.

Hide Actions column from trashed forms page

---

classes/helpers/FrmEntriesListHelper.php

Fixes https://github.com/Strategy11/formidable-pro/issues/5751
This broke with the QoL update. This code that adds the `+0` is important, but get overwritten when `FrmAppController::apply_saved_sort_preference` is called.
I moved this after so it still happens.

Fix issue 5751

---

css/frm_admin.css

This update just prevents this from being 100% width.

Fix new pill styling on payment field

---

stripe/controllers/FrmStrpLiteActionsController.php

Fabio brought this up in Slack https://strategy11.slack.com/archives/CJFQ599V5/p1745604846742759
This update tries to make the Stripe Link label styling more consistent.
I'm also introducing a `frm_stripe_appearance_rules` filter to make it easier to get things perfect.
Example snippet.
```
add_filter(
'frm_stripe_appearance_rules',
function ( $rules ) {
$rules['.Label']['lineHeight'] = 1;
return $rules;
}
);
```

Adjust stripe link label styles

---

classes/controllers/FrmAppController.php
js/admin/legacy-views.js
js/formidable_admin.js

This update moves over 400 lines of code out of the `frm_admin.js`, loading it only when we're loading scripts for the legacy views editor now instead.
This code won't likely get touched again. I may eventually move this to the Legacy Views add-on, but it isn't currently in my plans to update Legacy Views again.
[formidable-beta.zip](https://github.com/user-attachments/files/19943818/formidable-beta.zip)

Split out legacy views from admin JS

---

js/formidable_admin.js

This is causing issues with conditional logic setting all being empty. Reverting this change.
I'll need to figure out a better way.

Stop trigger change when showing field options

---

classes/models/FrmSalesApi.php

This is to prevent it from appearing for users who can't really act on the sale.

Avoid showing sales banner to user without the proper role

---

tests/cypress/e2e/Forms/formPageDataValidation.cy.js

This one is breaking because of the new sale banner.

Update banner CTA Check (e2e)

---

classes/helpers/FrmFormsHelper.php

I'm also changing the `0` `strpos` check because I'm testing with WPML and I'm seeing `/fr/` in the front of some URLs which breaks that check.

Also print honeypot css on gutenberg editor

---

classes/models/FrmSpamCheckDenylist.php

If denylist spam is disabled, the get fields call should not be run.

Denylist spam performance improvement

---

classes/models/FrmEntryValidate.php
classes/models/FrmSettings.php
classes/models/FrmSpamCheckDenylist.php
classes/models/FrmUsage.php
classes/views/frm-settings/captcha/captcha.php

Fixes https://github.com/Strategy11/formidable-pro/issues/5801
Changes:
- Added a toggle to disable denylist spam check.
- All spam checks now don't run when importing.
- Denylist spam check doesn't check password, captcha, signature, radio, checkbox, select field types. But it still check the Other value of radio, checkbox, select field types. To skip for Other value, add `other` to the `skip_field_types` of denylist.

Denylist spam check improvements

---

classes/models/FrmEntryValidate.php

This should already be fine because of the `options_are_dynamic_based_on_hook` check, but for some reason it's still an issue in this ticket https://secure.helpscout.net/conversation/2943441570/230308
This extra check should help.

Add exception for post field setting when validation options

---

classes/models/FrmEntryValidate.php

Related Slack comment https://strategy11.slack.com/archives/C799A2R61/p1747926380511749?thread_ts=1747901832.697259&cid=C799A2R61
If I have spaces at the end of my options in my database, it throws errors because the value getting sent is trimmed and the options are not.

Add trim check when checking for valid option match

---

js/formidable.js

Fixes https://github.com/Strategy11/formidable-pro/issues/5819
[formidable-6.21.2b.zip](https://github.com/user-attachments/files/20492687/formidable-6.21.2b.zip)

Fix pro issue 5819 / focus first input in option container with error

---

classes/controllers/FrmFormsController.php
classes/controllers/FrmHooksController.php
classes/models/FrmHoneypot.php

Mike reported this via Slack.
To replicate it locally:
- Install this plugin https://github.com/Strategy11/s11-audience-identification.
- Create a form, set the form key to `s11-audience-identification`.
- Log in using an account that isn't admin.
- View the frontend, you will see the honeypot field show in the form in the popup.
The problem is that the script to hide the honeypot field is called before the audience identification form.

Fix honeypot field shows in audience identification popup

---

classes/models/fields/FrmFieldType.php
classes/views/frm-fields/front-end/checkbox-field.php

Related ticket https://secure.helpscout.net/conversation/2957477608/231494
The issue is that it would print out all of these hidden inputs when using `opt=2`, etc, which it shouldn't be doing. There were a TON of `undefined` strings getting sent, that broke validation.
[formidable-6.21.2b.zip](https://github.com/user-attachments/files/20573969/formidable-6.21.2b.zip)

Stop showing hidden inputs when using opt option in input shortcode

---

classes/models/FrmEntryValidate.php

Related ticket https://secure.helpscout.net/conversation/2960874142/231770
[formidable-6.21.3b.zip](https://github.com/user-attachments/files/20615053/formidable-6.21.3b.zip)

Fix option validation where separate values has been turned off

---

classes/views/form-templates/template.php

This PR addresses the styling inconsistency in the Custom Templates section where the "Created [date]" text was incorrectly displayed in italic format. The changes ensure that:
https://github.com/Strategy11/formidable-pro/issues/5849

Fix: Remove italic styling from Custom Templates creation date text

---

js/formidable_admin.js

I was working on a Google Sheets release, but noticed that the autocomplete dropdown was always empty for a new form action.
This update fixes it, and makes some of the calls more consistent.
I added a temporary workaround in the Google Sheets code as well so I could still get a release out https://github.com/Strategy11/formidable-googlespreadsheet/pull/66

Autocomplete does not init for files dropdown for new action

---

classes/models/FrmDb.php

This is in case the cache is doing something weird.
A lot of code expects these to be arrays, so it's best that we just always return arrays.

Make get col and get result functions always return array

---

classes/models/FrmDb.php

Related ticket https://secure.helpscout.net/conversation/2996345861/234022
The previous fix didn't really catch everything. Other code calls `check_cache` directly.
[formidable-6.22.3b.zip](https://github.com/user-attachments/files/21149412/formidable-6.22.3b.zip)

Fix false values coming from cache at cache level

---

css/admin/deactivation-feedback.css

Fix can't deactivate plugin when popup has limited height

---

classes/helpers/FrmFormsHelper.php
css/custom_theme.css.php
tests/phpunit/forms/test_FrmFormsController.php

Fixes https://github.com/Strategy11/formidable-pro/issues/5901

Fix front end message spacing issues

---

js/formidable_admin.js

This fixes an issue I was seeing, where "Currency"/"Number" would stay selected after the format options were selected and the upgrade modal was shown.

Fix currency format stays selected

---

classes/models/fields/FrmFieldUrl.php
js/formidable.js

Related ticket https://secure.helpscout.net/conversation/3014270403/235068
Related feature request https://fr.strategy11.com/formidable/2021/04/30/add-option-for-https-instead-of-http-in-url-fields/
[formidable-6.22.4b.zip](https://github.com/user-attachments/files/21434245/formidable-6.22.4b.zip)

Add https instead of http to URLs missing a protocol

---

classes/helpers/FrmAppHelper.php

Fix https://github.com/Strategy11/formidable-pro/issues/5871
**Before**:
**After**:

Update 'to address' field tooltip in email action

---

classes/models/FrmMigrate.php
classes/models/FrmSettings.php

Fixes https://github.com/Strategy11/formidable-pro/issues/5875

Enable denylist spam check by default

---

classes/helpers/FrmStylesHelper.php

Related ticket https://secure.helpscout.net/conversation/3016541817/235193
In case `$var` is something unexpected, like an array, we can skip it.

Make css valid check more type safe

---

square/controllers/FrmSquareLiteAppController.php
square/js/frontend.js

This may help with this related ticket https://secure.helpscout.net/conversation/3025312291/235710
And this related Square issue https://developer.squareup.com/forums/t/verifybuyer-function-locks-up-the-second-time-it-is-called/13218/12
As long as none of the verification data changes, we should be good to re-use the token we had before. Avoiding the duplicate call should prevent the Square error, though I didn't have luck actually triggering the error myself.
[formidable-6.23b.zip](https://github.com/user-attachments/files/21621693/formidable-6.23b.zip)

Reuse verified buyer token if details match hash

---

css/admin/style.css

Fixes https://github.com/Strategy11/formidable-pro/issues/5963
This line was added originally was `line-height: normal` along with the comment `Avoid a line-height: 1.4rem rule defined in common.css WordPress admin rules`.
I'm not sure if I see the 1.4rem rule anymore. This seems more consistent if I just drop the CSS.

Drop label line height styling on styler

---

classes/helpers/FrmStylesHelper.php

Related PR https://github.com/Strategy11/formidable-forms/pull/2456
Fixes https://github.com/Strategy11/formidable-pro/issues/5929
I don't love the list of hard coded keys. I think we really just want to check the prepared values instead of the other value.
I tried this out on Emma's QA site and it looks like it works well.

issue 5929 alternative fix

---

css/admin/style.css

This came up in Slack. Goncalo didn't think he could assign the default style because there was no Apply option.

Show assign button for default style

---

classes/helpers/FrmHtmlHelper.php

This fixes a bug I'm seeing with the unit dropdowns and the new field options redesign.
On load, I have a field width of 100px. When I save, the hidden input only has "100" as its value, and the units are lost. You can see this in the preview for the password field with a confirmation because it shows the field size setting at the moment. The dropdown still looks like "px", because it reverts to this by default.
https://github.com/user-attachments/assets/a99814a4-43d0-434d-928a-2485f5517340

Fix invalid hidden field size input value on load

---

classes/controllers/FrmEmailStylesController.php
classes/models/FrmUsage.php

This PR adds this data to the snapshot:
- 'email_style' in 'settings'.
- Number of times send test email is used for each style, this is in the `flows` table:
```
'send_test_email' => array(
'classic' => 2,
'modern'  => 5,
...
)
```
Related issue: https://github.com/Strategy11/formidable-pro/issues/6020

Pro issue 6020 email style tracking
