classes/controllers/FrmAppController.php, classes/controllers/FrmEntriesController.php, classes/controllers/FrmFieldsController.php, classes/controllers/FrmFormActionsController.php
@stephywells requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/Strategy11/formidable-forms/
=> Scrutinizer Auto-Fixes

js/formidable.js
Fixing the issue https://github.com/Strategy11/formidable/issues/1369.
Change the way to initialize the chosen jquery plugin when are load in edit in place, in this case it would load all chose inside the container
=> Fixing the issue 1369

classes/controllers/FrmFormsController.php
https://github.com/Strategy11/formidable/issues/1329
Forcing the form to send with ajax and validate in the client side with js if edit in place.
=> Fixing issues/1329

css/frm_admin.css
Reverts Strategy11/formidable-forms#33
=> Revert "Fixing the issues/1455"

js/formidable_admin.js
https://github.com/Strategy11/formidable/issues/536
Fixing the switch view to the key into the toolbox when is created a view
=> Fixing issue/536

classes/controllers/FrmEntriesController.php
https://github.com/Strategy11/formidable/issues/1374
Adding the post status validation
=> Fixing issue 1374

classes/helpers/FrmFieldsHelper.php, classes/views/frm-forms/add_field.php, css/custom_theme.css.php, js/formidable.js
https://github.com/Strategy11/formidable/issues/1448
=> Add invisible recaptcha

js/formidable.js
=> Removes autoclear from masks.

classes/views/frm-form-actions/form_action.php, classes/views/frm-forms/add_field.php, css/font_icons.css, css/frm_admin.css, js/formidable_admin.js
reference https://github.com/Strategy11/formidable/issues/1614
* added recommendations from issue tracking (above)
* changed **widget-title** h4 to h3
* updated css to fix down arrow not rotating when dropdown is open
* fixed vertical alignment on action icons left of title
=> Issues #1614/Arrows missing in WP 4.8

readme.txt
spped > speed
compatibiliy > compatibility
=> Spelling Fixes

classes/helpers/FrmAppHelper.php, classes/models/FrmEntryFormatter.php, tests/base/FrmUnitTest.php, tests/emails/test_FrmProEmailWithAttachment.php, tests/entries/test_FrmProShowEntryShortcode.php, tests/entries/test_FrmShowEntryShortcode.php, tests/fields/test_FrmProFieldsControllerAjax.php, tests/fields/test_FrmProFieldsHelper.php, tests/fields/test_FrmProFormActionLogicRow.php, tests/fields/test_FrmProfieldLogicRow.php
3.0 version of the changes in PR #75.
=> Fix unit tests in 3.0 (Work In Progress)

classes/helpers/FrmEntriesListHelper.php, classes/models/FrmDb.php, tests/database/test_FrmDb.php
Fixes https://github.com/Strategy11/formidable/issues/1881.
=> Fix sort by a number/scale/star on entries page

classes/models/FrmEntryFormatter.php
Fixes Pro issue https://github.com/Strategy11/formidable/issues/1873.
=> Make array output for fields with separate values consistent

classes/controllers/FrmFormActionsController.php, classes/models/FrmFormAction.php
I didn't want to change this much out of concern that something else somewhere would break.  Do you think this approach is okay?  Would you prefer a different one?
=> Resend and other single action types only fire if toggled on.

classes/models/fields/FrmFieldCaptcha.php, classes/models/fields/FrmFieldCheckbox.php, classes/models/fields/FrmFieldEmail.php, classes/models/fields/FrmFieldHidden.php, classes/models/fields/FrmFieldNumber.php, classes/models/fields/FrmFieldPhone.php, classes/models/fields/FrmFieldRadio.php, classes/models/fields/FrmFieldSelect.php, classes/models/fields/FrmFieldText.php, classes/models/fields/FrmFieldType.php, classes/models/fields/FrmFieldUrl.php, classes/models/fields/FrmFieldUserID.php, tests/fields/test_FrmFieldType.php
,change their @since doc tag to 4.0.04 & add more tests
=> Enhance field type sanitizer functions

css/_single_theme.css.php, css/custom_theme.css.php, js/formidable.js
In a multi-page form, when the prev and next buttons are pushed, the loading icon shows on the button that was pushed.
https://github.com/Strategy11/formidable-pro/issues/2314
=> Shows loading indicator on prev button when prev button pushed

css/frm_admin.css
https://github.com/Strategy11/formidable-pro/issues/2348
=> Locks links on top of sidebar in form builder in place

classes/views/frm-forms/settings-advanced.php, classes/views/frm-settings/messages.php, css/frm_admin.css, js/formidable_admin.js
Changes tooltips to use bootstrap tooltips
Updates tooltip design
Adds icons to tooltips that didn't have them
https://github.com/Strategy11/formidable-pro/issues/2371
=> Better admin tooltips

css/_single_theme.css.php, css/custom_theme.css.php, js/formidable.js
fix new js error (not yet released)
=> Allow empty font style for theme inheritance

classes/views/frm-form-actions/_email_settings.php, js/formidable_admin.js
https://github.com/Strategy11/formidable-pro/issues/2469
=> Add message box for warning and js to hide/show it for #2469

classes/controllers/FrmAppController.php, classes/controllers/FrmHooksController.php, classes/controllers/FrmSettingsController.php, classes/controllers/FrmStylesController.php, classes/controllers/FrmXMLController.php, classes/helpers/FrmAppHelper.php, classes/helpers/FrmFormMigratorsHelper.php, classes/models/FrmInbox.php, classes/models/FrmNotification.php, classes/models/FrmReviews.php, classes/views/frm-settings/form.php, classes/views/frm-settings/inbox.php, classes/views/frm-settings/tabs.php, classes/views/shared/errors.php, classes/views/shared/review.php, css/frm_admin.css
Include form styles under appearance
=> add inbox in global settings for better communication

classes/views/frm-entries/new.php
Sets default value for $message_placement in new.php.
https://github.com/Strategy11/formidable-pro/issues/2522
=> Sets a default value for $message_placement in new.php

classes/helpers/FrmEntriesHelper.php
https://github.com/Strategy11/formidable-pro/issues/2533
=> don't show commas in entry listing table

classes/models/fields/FrmFieldUserID.php, js/formidable_admin.js
fix https://github.com/Strategy11/formidable-pro/issues/2523
Remove a few js vars we don't really need
=> Add frm_user_id_display hook

classes/models/FrmEmail.php
=> feat: add post content settings to filter

classes/controllers/FrmSMTPController.php
=> WP 5.5 fix

phpunit.xml
I never bothered to mention this, but for the version of phpunit I'm on (7.5.6), I need these changes in my xml file as well.
The changes aren't too crazy. [According to travis](https://travis-ci.org/github/Strategy11/formidable-forms/builds/717015894) it seems legit.
=> support phpunit 7.5.6

tests/base/FrmUnitTest.php
=> undo frm unit test constructor

js/bootstrap-multiselect.js, js/formidable_admin.js
Noticed that we seem to be behind 2 versions with our bootstrap multiselect.
https://github.com/davidstutz/bootstrap-multiselect/releases/tag/v0.9.15
It's not very clear on all of what was updated but in bold it states `Updating from v0.9.13 is recommended.`.
I was hoping maybe it would have an impact but it doesn't seem to make us more compliant for accessibility though.
=> update bootstrap multiselect

js/formidable.js
Working toward https://github.com/Strategy11/formidable-pro/issues/2584 I've added url validation on the JavaScript side using the same regex from validate in `FrmFieldUrl.php`.
Without this, we only supported url validation through AJAX, so this gets us one step closer to supporting every field.
This probably does not close the ticket. It's just one small step closer as I continue to look for gaps.
=> Add JavaScript side url validation

css/frm_admin.css
https://github.com/Strategy11/formidable-pro/issues/2622
=> multiselect filter dropdown is broken fix

js/formidable_admin.js
I found one side-effect of https://github.com/Strategy11/formidable-forms/pull/240
When you save the form, it will still say you have unsaved changes. I clear the flag on save and it does the trick :)
=> clear fieldsUpdated value on save

classes/helpers/FrmEntriesListHelper.php, classes/helpers/FrmFormsListHelper.php, classes/helpers/FrmListHelper.php, js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/1034
=> confirm bulk delete

classes/controllers/FrmFormActionsController.php, classes/views/frm-form-actions/default_actions.php
https://github.com/Strategy11/formidable-pro/issues/2623
=> make zapier easier to install in form actions

classes/models/FrmEntryValidate.php
Following up on https://github.com/Strategy11/formidable-forms/pull/256/files just starting from scratch as it went in a different direction.
Fixes https://github.com/Strategy11/formidable-pro/issues/2636
=> remove value clear on placeholder match

classes/views/frm-fields/back-end/field-captcha.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2612
=> add target blank to captcha setup link

js/formidable_admin.js
This update should be enough to close https://github.com/Strategy11/formidable-pro/issues/2621
There are basically 2 conditions, if everyone is selected, or if everyone was selected. Pretty simple.
=> add custom everyone logic for field visibility multiselect

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/2659
Didn't really know this input was there, cool feature!
=> search triggers fieldUpdated fix

classes/models/FrmEntryValidate.php, tests/entries/test_FrmEntryValidate.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2656
=> spam check empty values fix

classes/helpers/FrmAppHelper.php
https://github.com/Strategy11/formidable-pro/issues/2716
=> fix turkish datepicker

classes/controllers/FrmAddonsController.php, classes/controllers/FrmAppController.php, classes/controllers/FrmFormsController.php, classes/controllers/FrmHooksController.php, classes/helpers/FrmAppHelper.php, classes/views/addons/list.php, classes/views/frm-entries/list.php, classes/views/frm-forms/form.php, classes/views/frm-forms/list.php, classes/views/frm-forms/new-form-overlay.php, classes/views/frm-forms/settings.php, deprecated/FrmDeprecated.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2742
This is all tested and reviewed. Just waiting on unit tests to merge.
=> Pro updater

classes/helpers/FrmCSVExportHelper.php, tests/misc/test_FrmCSVExportHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2736
The issue here was that a field in an embedded section is really similar looking to a field in a repeater, so the check was getting both of those when it should only be getting the one.
I had to move some of the repeater logic higher up, and then I moved it into a function to made this all a little easier to follow.
=> embedded section field export fix

classes/helpers/FrmEntriesListHelper.php, classes/helpers/FrmFormsHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2732
Also cleaned it up a bit :)
=> remove edit form link from entries list if user cannot edit form

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/2764
=> add warning when leaving form settings

js/formidable.js
Fixes https://github.com/Strategy11/formidable-pro/issues/2844 but this time in the lite plugin.
I wasn't really considering that Honeypot was a free thing, so the fix didn't target free.
I also plan to remove this fix from pro code, but having it twice doesn't really cause any problems.
=> honeypot autofill fix

changelog.txt, readme.txt
Adding in the change log for 4.09.05.
Leaving out the copies update as it still hasn't merged, and I feel like this update is important (and the copies update isn't too necessary).
=> add 4.09.05 changelog

classes/models/FrmInbox.php
Continuing from https://github.com/Strategy11/formidable-forms/pull/344
Fixes https://github.com/Strategy11/formidable-pro/issues/2879 using Steph's suggestions instead of my original validate/filter in different parts of this code.
=> check for empty message keys

changelog.txt, readme.txt
I'm including a few unmerged items in this list since I want to get all of these things into this release.
Also bumping the tested WordPress version. I set it to 5.6.1 since that's the latest stable version. I'm not sure if setting it to 5.7 early makes sense - technically it's what I've been mostly testing with.
=> update 4.09.06 readme

classes/helpers/FrmFormsHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2762
=> fix "default" == "form" form style check

classes/views/welcome/show.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2913
=> Fix typo on welcome page

classes/controllers/FrmAppController.php, classes/views/frm-settings/settings_cta.php, classes/views/inbox/list.php, classes/views/shared/admin-header.php, classes/views/xml/import_form.php, css/frm_admin.css
- show an upgrade message when lite is running
- when expired, let people know
=> Add a bit of Education

js/formidable_admin.js
This is related to this issue https://github.com/Strategy11/formidable-pro/issues/2943
=> Add JS code to dynamic show/hide Post Time option in pro version

classes/models/FrmEmail.php
This fixes this pro version issue https://github.com/Strategy11/formidable-pro/issues/2825
=> Improve the mail header when using mail() function

classes/models/fields/FrmFieldType.php, classes/views/frm-entries/errors.php
This might fix this issue https://github.com/Strategy11/formidable-pro/issues/2862
=> Improve accessibility for screen readers

js/formidable_admin.js
Reverts Strategy11/formidable-forms#373
=> Revert "Add JS code to dynamic show/hide Post Time option in pro version"

classes/controllers/FrmSimpleBlocksController.php, tests/misc/test_FrmSimpleBlocksController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3001
=> only remove frm_logic_class when wp_is_json_request

classes/controllers/FrmInboxController.php, classes/models/FrmFormTemplateApi.php, js/formidable_admin.js
This fixes issue https://github.com/Strategy11/formidable-pro/issues/2885
=> Add "free template" opportunity to inbox

js/formidable_admin.js
This fix https://github.com/Strategy11/formidable-pro/issues/3018
=> Upload image button in Radio field should show only images

classes/helpers/FrmXMLHelper.php, tests/misc/test_FrmXMLHelper.php
This fixes issue https://github.com/Strategy11/formidable-pro/issues/2999
=> Fix PHP notice with array_diff_assoc() when exporting form

changelog.txt, readme.txt
@stephywells I know you've been updating this file as well, but I don't see those updates here. Not sure where you're updating them, if it's in SVN or something?
Also, I feel like I'm really not celebrating the name file enough here with my short little description. I'm just not sure what to say about it.
=> Update readme for 4.11

classes/models/fields/FrmFieldCombo.php
This fixes https://github.com/Strategy11/formidable-pro/issues/3026
=> Add visibility option to the Name field

css/frm_grids.css
Based off of the conversation in https://github.com/Strategy11/formidable-views/issues/111
=> change grid column value instead of display for frm_no_grid_750

classes/helpers/FrmAppHelper.php, classes/views/shared/views-info.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3032
I think this is really all we need to do here.
The only other views upsell I can remember is for creating post actions, and it links to the views-info page that this update is targeting.
=> include plan=view in upgrade link for views

classes/views/frm-form-actions/form_action.php
Just another tiny one.
```
------ -----------------------------------------------------------
Line   formidable/classes/views/frm-form-actions/form_action.php
------ -----------------------------------------------------------
25     Function esc_attr invoked with 2 parameters, 1 required.
------ -----------------------------------------------------------
```
=> Use esc_attr_e in form_action.php view fix

changelog.txt, readme.txt
There are other updates in here but I don't really think any of them are easy to describe and might not really go noticed by a user as much (https://github.com/Strategy11/formidable-forms/milestone/9?closed=1).
So I'm keeping it simple.
=> Update 4.11.02 readme

classes/helpers/FrmEntriesHelper.php
This fixes issue https://github.com/Strategy11/formidable-pro/issues/3069
=> Fix the entries list does not show value 0 inside repeater field

classes/models/fields/FrmFieldName.php
This fixes https://github.com/Strategy11/formidable-pro/issues/3083
=> Fix name field not working in the From and To options of Send mail action

changelog.txt, readme.txt
Think this is it. Not sure if we want to mention the deprecation at all? Doesn't seem significant.
=> update readme and changelog

changelog.txt, readme.txt
Included https://github.com/Strategy11/formidable-forms/pull/462 in the readme as well, which still needs review.
=> Update readme for 4.11.04

classes/helpers/FrmXMLHelper.php, tests/misc/test_FrmXMLHelper.php
Export/import should now all be JSON based for views.
Should be tested with https://github.com/Strategy11/formidable-views/pull/210
=> Stop using serialization for views in import

classes/helpers/FrmAppHelper.php, classes/models/FrmAddon.php
This fixes https://github.com/Strategy11/formidable-pro/issues/3068
=> Fix permissions are not updated until Global Settings saved

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3121
Page toggle logic had to change a bit since it uses nextUntil but I have the pages wrapped like everything else for consistency.
=> Fix issues with toggling pages

.github/workflows/push-deploy.yml
Still having issues with auto-deploy.
I'm wondering if it's the old version that's the issue?
=> Try plugin deploy 1.5.0

classes/controllers/FrmEntriesController.php, classes/models/FrmEntry.php
Adding two filters in order to support https://github.com/Strategy11/formidable-pro/pull/3183
=> Add filters for handling entries table column sorting

changelog.txt, readme.txt
@stephywells what do you think about the filters? There's a ton of them, I'm not sure if we want to list them?
Should I just go with something like "Added several new filters required to support our new surveys add on" or something instead?
=> Update readme for 5.0.04

classes/controllers/FrmFieldsController.php
This is required for the Surveys add-on
=> Add frm_after_duplicate_field hook

bin/zip-plugin.sh
For the surveys plugin release process.
=> Exclude scss from zip

classes/models/FrmEntryValidate.php
This is required by Surveys add-on
=> Add frm_fields_to_validate hook

.github/workflows/phpunit.yml
Still working out some kinks here.
I think I'll add some higher PHP versions soon once I know they're working as well, but for now I'm scaling back to only officially supported versions.
=> Only set supported phpunit versions for now, add multisite tests

changelog.txt, classes/helpers/FrmFormsHelper.php, readme.txt
Just adding the new filter that was also merged
=> Include new submit button filter in changelog

classes/helpers/FrmFormsHelper.php
As I document this filter, I realize it would benefit from passing the form as an argument, so adding that in quickly to include with the release.
=> Include form as arg for submit button html filter

classes/helpers/FrmAppHelper.php, formidable.php
Just merging this so it matches properly. Accidentally missed committing this in the release.
=> Bump plugin version to 5.0.07

classes/models/FrmFormApi.php, classes/models/FrmInbox.php
Following up from https://github.com/Strategy11/formidable-forms/pull/601
=> Make inbox messages static

classes/models/FrmEntryValidate.php, tests/entries/test_FrmEntryValidate.php, tests/fields/test_FrmFieldValidate.php
This fixes https://github.com/Strategy11/formidable-pro/issues/3265
=> Name field is not used as commenter name in Akismet spam check

classes/models/FrmEntryValidate.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3278
=> Only check Akismet spam if form is submitted

classes/helpers/FrmEntriesListHelper.php, classes/helpers/FrmListHelper.php
Removing a phpcs exception. The function outputs HTML, the echo is unnecessary.
=> Remove echo from forms dropdown

classes/models/FrmEntryValidate.php, tests/fields/test_FrmFieldValidate.php
This fixes https://github.com/Strategy11/formidable-pro/issues/3313
=> Fix error on blacklist check

changelog.txt, readme.txt
Got the order wrong one of the times I typed out Akismet.
=> Readme typo fix 5.0.13

bin/zip-plugin.sh
Just removing the non-minified chat js on zip.
=> Exclude chat js from zip

.github/workflows/phpunit.yml
Adding a PHP 8.0 unit test. I tried 8.1 but I was hitting an error on the WordPress end so skipping it for now.
=> Try php unit with php8

js/formidable_admin.js
This adds the js to watch for the image uploader on the form settings page. Pretty simple copy and paste from the styler.
=> Landing pages js

classes/controllers/FrmSettingsController.php, classes/helpers/FrmEntriesHelper.php, classes/models/FrmEntry.php, classes/models/FrmSettings.php, classes/models/fields/FrmFieldCaptcha.php, classes/views/frm-entries/sidebar-shared.php, classes/views/frm-settings/recaptcha.php, js/formidable_admin.js
_Grammar is a bit off in screenshot but I pushed a tweak to fix that._
_I've also fixed the capitalization of captcha so it's "reCAPTCHA" now_
=> reCaptcha v3

classes/helpers/FrmEntriesListHelper.php
=> Add frm_entries_column_value filter

.github/workflows/phpstan.yml, phpstan.stubs.php
I missed this but it looks like I'm missing the WordPress composer package here which is causing it to silently break in the GitHub action
=> PHPStan workflow not running in github fix

.github/workflows/phpstan.yml, phpstan.neon, phpstan.stubs.php
I missed that it's now showing it as successful but logging errors.
=> Remove continue on error from phpstan workflow

css/_single_theme.css.php, css/custom_theme.css.php, css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/3374
=> Remove margin-bottom of combo child fields

classes/controllers/FrmFormActionsController.php, classes/views/frm-form-actions/default_actions.php
This adds quizzes in the form actions in the lite version.
=> Show quizzes in default form actions

classes/controllers/FrmAddonsController.php, classes/helpers/FrmFormsHelper.php, classes/views/frm-forms/list-templates.php, css/frm_admin.css
Separate from #705 
How can I see the template in the list? And now we have 7 items the top section of modal, we need to add or remove one item.
=> Add Quiz template category and ID

classes/helpers/FrmAppHelper.php, classes/views/frm-forms/landing-page-preview-option.php, classes/views/frm-forms/list-template.php, css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/3454
=> Use NEW tag for new templates

classes/controllers/FrmFormsController.php
This is required for Stripe fix
=> Add frm_saved_errors filter

classes/models/FrmEntryValidate.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3498
=> Replace array_key_last() function

classes/models/fields/FrmFieldNumber.php
Related issue: https://github.com/Strategy11/formidable-pro/issues/3509
I'm not sure about the `$frm_settings->use_html` check. Maybe the new check should be inside that check.
=> Validate number step

classes/helpers/FrmAppHelper.php, classes/models/fields/FrmFieldNumber.php, tests/fields/test_FrmFieldNumber.php, tests/misc/test_FrmAppHelper.php
=> Fix incorrect step validation with float value #760

classes/helpers/FrmFieldsHelper.php
Related issue: https://github.com/Strategy11/formidable-pro/issues/3513
I want to fix the Default value that is not updated in another PR because this PR is enough to fix the reported issue, and the Default value issue is a bigger different story.
=> Fix Deadline Calculator template does not work

classes/models/FrmForm.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3539
=> Replace field ID in fields after duplicating

js/admin/dom.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3556
=> Stop scrolling to top when opening modal, remove body overflow instead

classes/helpers/FrmTipsHelper.php, classes/models/FrmStyle.php, classes/views/styles/_general.php, css/frm_admin.css, images/icons.svg
- Restyle pro tip
- Set font to blank by default to use theme font
=> Small CSS changes

classes/models/fields/FrmFieldType.php, js/formidable.js, tests/fields/test_FrmFieldType.php
[issue-3548](https://github.com/Strategy11/formidable-pro/issues/3548)
**Missing**
=> Merge aria describedby attributes from description and custom HTML

classes/models/FrmForm.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3624
=> Fix Switching field IDs could break the serialize data

classes/controllers/FrmFieldsController.php, classes/models/FrmFieldFormHtml.php, css/custom_theme.css.php, js/formidable.js, tests/fields/test_FrmFieldsController.php
Inline documentation is in progress.
Fixes https://github.com/Strategy11/formidable-pro/issues/3617
=> Add floating labels effect to "inside" label position

classes/controllers/FrmAppController.php, classes/controllers/FrmFormsController.php, classes/views/frm-forms/list-template.php, classes/views/shared/errors.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3161
=> redirect page to form edit page after form is duplicated.

classes/models/FrmFieldFormHtml.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3669
=> Fix section labels are always display

classes/models/FrmAddon.php
The conversation for this: https://github.com/Strategy11/formidable-pdfs/pull/22#discussion_r920437309
=> Add new static() to FrmAddon::load_hooks()

classes/views/styles/_sample_form.php, js/formidable.js, js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3680
=> Fix floating label doesn't work well on Styles page

js/formidable.js, js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3702
=> Improve JS code when changing label position on Styles page

changelog.txt, readme.txt
=> Add aria describedby item to changelog

tests/entries/test_FrmShowEntryShortcode.php
=> Add repeater child class to unit test

classes/views/frm-fields/back-end/bulk-options-overlay.php, classes/views/frm-fields/back-end/inline-modal.php, classes/views/frm-settings/settings_cta.php, classes/views/shared/confirm-overlay.php, classes/views/shared/info-overlay.php, classes/views/shared/upgrade_overlay.php, css/frm_admin.css
Start consolidating a few modals
- Switch the bulk edit modal to match others
- Get rid of the blue x in a circle in some modals
=> More consistent modal styling

js/formidable.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3731
@stephywells I couldn't replicate this error. Can you test this on the BD site?
=> Fix floating label js error

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3734
=> Check target input id in duplicate option check

classes/views/frm-form-actions/_action_inside.php, css/frm_admin.css, js/formidable_admin.js
- Clean up the pro tips and notices
- Signature images were overlapping in listing table
- Add a message for the email attachment
=> Tweaks and clean up

classes/helpers/FrmXMLHelper.php
Fixes https://github.com/Strategy11/formidable-views/issues/327
=> Support frm_param meta value in view import

classes/models/fields/FrmFieldText.php, classes/views/frm-fields/back-end/max.php, classes/views/frm-fields/back-end/settings.php, classes/views/frm-fields/back-end/value-format.php, js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3753
=> Add max length PHP validation for Text field

readme.txt
=> Revert readme update

js/formidable_admin.js
Just cleaning up. I stopped using IDs but forgot to remove the comment.
=> Remove old todo comment in admin.js

classes/controllers/FrmElementorController.php, classes/controllers/FrmHooksController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3788
That code is deprecated in v3.5, the current version of Elementor is 3.7.2 so I think we don't need to check if new code exists.
=> Update deprecated code

classes/models/FrmEntryValues.php
Fixes https://github.com/Strategy11/formidable-user-tracking/issues/9
This update adds a new filter that allows users to modify the referrer info of a user tracking.
=> add a new filter to modify referrer info

classes/controllers/FrmEntriesController.php
This prevents errors in the sidebar with the user tracking plugin installed
@AbdiTolesa is there already something for this that I missed?
=> Add hook for user tracking

css/custom_theme.css.php, css/frm_admin.css
This update just fixes some style issues found in radio fields.
=> fix radio button field style issues

classes/models/FrmEntryValues.php
This update just adds another argument to the filter for user info referrer data.
=> add entry to filter arguments

css/custom_theme.css.php
This fixes https://github.com/Strategy11/formidable-pro/issues/3844
Thanks @stephywells for the CSS code.
=> Reduce space between fields using Inside position

classes/helpers/FrmAppHelper.php, js/formidable_admin.js
This is used in the ACF addon.
=> Make a JS string translatable

classes/helpers/FrmAppHelper.php, js/formidable.js
I decided not to fix the issue I mentioned here https://github.com/Strategy11/formidable-pro/issues/3823#issuecomment-1271677233. Because it can be solved easily by setting the Password field required.
=> Add JS validation for password strength

js/formidable_admin.js
Part of https://github.com/Strategy11/formidable-pro/issues/3818
=> Toggle section holder after duplicating section

classes/controllers/FrmAppController.php, classes/helpers/FrmAppHelper.php, classes/helpers/FrmEntriesHelper.php, classes/helpers/FrmEntriesListHelper.php, classes/views/frm-entries/list.php, classes/views/shared/admin-header.php, css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/2389
Always use full screen for View builder
Don't use full screen of listing pages, reports page, or editing entries.
=> Full screen consistency

classes/controllers/FrmFormActionsController.php, classes/views/frm-form-actions/default_actions.php
Add placeholder icon for google sheets add-on.
Fixes https://github.com/Strategy11/formidable-pro/issues/3882
=> Placeholder icon for google sheets addon

classes/views/frm-form-actions/default_actions.php
Changes placeholder icon of google sheets in action, Related PR https://github.com/Strategy11/formidable-forms/pull/962
=> Color to placeholder icon of google sheets action

classes/controllers/FrmApplicationsController.php, classes/views/frm-forms/landing-page-preview-option.php
These aren't too new anymore. I figure it's time to remove them.
=> Remove "new" from applications and landing pages

changelog.txt, readme.txt
=> Update readme for 5.5.3

readme.txt
I think this is keeping it from updating.
=> Update stable tag in readme

js/formidable_admin.js
This is used for the ACF addon.
=> Make infoModal() global

js/formidable.js
This is a quick fix to make sure errors are not thrown from our script in IE,
=> change let and const to var

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3024
=> Fix in_section value is unreliable

classes/controllers/FrmAddonsController.php, classes/helpers/FrmTipsHelper.php, classes/models/FrmFieldValueSelector.php, classes/views/frm-form-actions/default_actions.php, classes/views/frm-forms/new-form-overlay/upgrade-body.php, readme.md, readme.txt
Fix https://github.com/Strategy11/formidable-pro/issues/3899
=> Issue 3899

readme.txt
=> Add new features in readme

classes/controllers/FrmFormsController.php, classes/controllers/FrmHooksController.php, classes/models/FrmStyle.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3914
I think we can hook into `frm_submit_button_class` and `frm_back_button_class` to add extra classes if twenty twenty-one theme is active.
=> Issue 3914

classes/controllers/FrmXMLController.php, classes/views/xml/import_form.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3988
=> exclude repeaters from exportable forms list

css/frm_admin.css
This update would ideally be kept in pro had there been admin css file there. It is adding to https://github.com/Strategy11/formidable-pro/pull/3976/files that pertains to making the required updates to match the new design (https://www.figma.com/file/ILeT8x5Ks4cxEUzRix1ma8/Form-Actions?node-id=801%3A2184&t=cR37l3v540PtR2tO-0).
=> Logic styling

classes/helpers/FrmTipsHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3982
@stephywells Please adjust the `link` param.
=> Add upgrade tip for ACF addon

classes/models/FrmForm.php
Related pull request https://github.com/Strategy11/formidable-pro/pull/4010
Required to fix the issue I mention in https://github.com/Strategy11/formidable-pro/pull/4007
=> Add a new filter frm_should_sanitize_field_opt_string

changelog.txt, readme.txt
Include https://github.com/Strategy11/formidable-forms/pull/1023
=> Update readme for 5.5.6

classes/controllers/FrmAppController.php, classes/helpers/FrmHtmlHelper.php, classes/views/frm-form-actions/form_action.php, classes/views/shared/mb_adv_info.php, classes/views/shared/toggle.php, css/frm_admin.css, js/admin/settings.js, js/formidable_admin.js
Moved from https://github.com/Strategy11/formidable-forms/commit/f5269f9ada5a22dc8dcd8876aa5d26dee3057886
Used in place of the toggle in the form actions
Added an option to remove the div on the toggle
=> Add new admin toggle element

css/frm_admin.css
Fixes https://www.figma.com/file/7Kwlv3H2ShYEI0wekWnPBb/Interface-Review-Fixes?node-id=454%3A141&t=9r2VojLOrRO6xId2-0
After:
=> Sidebar layout updates

classes/controllers/FrmFormsController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4068
=> Fix PHP notice with success_action

changelog.txt, readme.txt
**TODO**
- Update the name of the new action. It's Confirmation now, not On submit.
- Update the readme file too.
=> Start working on readme for 6.0

classes/controllers/FrmFormsController.php, classes/models/FrmSettings.php, classes/views/frm-forms/settings-advanced.php
Related issue: https://github.com/Strategy11/formidable-pro/issues/4042
=> Fix PHP 8.2 notices

classes/controllers/FrmFormsController.php
This fixes the issue with saving draft in https://github.com/Strategy11/formidable-pro/pull/4084#issuecomment-1439956381
=> Apply frm_success_filter for confirmation actions

classes/controllers/FrmFormsController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4086
=> Fix confirmation update message doesn't work

changelog.txt, readme.txt
Still missing https://github.com/Strategy11/formidable-pro/issues/4067
=> Update readme for v6.1

classes/controllers/FrmFormsController.php
This works with https://github.com/Strategy11/formidable-pro/pull/4102
Related to https://github.com/Strategy11/formidable-pro/issues/4101
=> Let the pro version use the run_on_submit_actions function

classes/controllers/FrmFormsController.php
This requires https://github.com/Strategy11/formidable-pro/pull/4126 to fix https://github.com/Strategy11/formidable-pro/issues/4120
=> Run frontend editing code from Pro plugin

css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/4113
[issuse-4113.webm](https://user-images.githubusercontent.com/41271840/223715540-b289cdeb-1353-4c2a-82ea-19ba3fb7007e.webm)
=> overwrite frm_page_container overflow style for translate page

classes/controllers/FrmAppController.php, css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/4098
BEFORE:
NOW:
=> overwrite .columns-2 styles for view page

css/frm_admin.css
Keep date input type consistent too
=> Add css for input date fields

classes/models/FrmField.php
@Crabcyborg did you have a good way of not showing this field until the plugin is released?
=> Add AI field in Lite

changelog.txt, readme.txt
**TODO**
- Include https://github.com/Strategy11/formidable-pro/issues/4136
=> Begin working on readme for v6.2

tests/forms/test_FrmFormsController.php
This covers the issue from yesterday https://github.com/Strategy11/formidable-forms/pull/1142
=> Add a shortcode to redirect_after_submit unit test

classes/controllers/FrmFormsController.php, tests/forms/test_FrmFormsController.php
Fixes https://github.com/Strategy11/formidable-paypal/issues/42
=> Fix PayPal action redirecting to a blank page

classes/helpers/FrmStylesCardHelper.php, css/admin/style.css
Fixes https://github.com/Strategy11/formidable-pro/issues/4123
=> Include input border radius in style card samples

classes/helpers/FrmAppHelper.php
Got one of the details wrong in a comment in https://github.com/Strategy11/formidable-forms/pull/1152.
=> Correct comment in new function

classes/controllers/FrmAppController.php
Noticed this while testing an update.
Just cleaning up my notes and taking care of this.
🚀
=> Fix a typo on warning comment

js/formidable.js
Trying to come up with something faster than https://github.com/Strategy11/formidable-forms/pull/1144
See https://github.com/Strategy11/formidable-forms/pull/1144#discussion_r1176725717 for more information.
=> Try a more optimized version of issue 4150

classes/helpers/FrmHtmlHelper.php, classes/views/frm-fields/front-end/dropdown-field.php, stubs.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4184
=> avoid whitespaces for dropdown field options

classes/controllers/FrmAppController.php, classes/controllers/FrmHooksController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4273
=> use admin_enqueue_scripts hook instead of admin_init

classes/models/FrmSettings.php
@Crabcyborg I'm not sure if I should link this to the issue as the issue is public but I have updated the captcha secrets so that they are trimmed before save.
=> trim captcha secrets before save

js/formidable_admin.js
Fix https://github.com/Strategy11/formidable-pro/issues/4322
=> show confirmation box on field choices modification

changelog.txt, readme.txt
**Other things to include in 6.4.1:**
- https://github.com/Strategy11/formidable-forms/pull/1199
- https://github.com/Strategy11/formidable-forms/pull/1241
=> Begin readme updates for 6.4.1

classes/controllers/FrmAddonsController.php, classes/controllers/FrmAppController.php
- Switch upgrade link on plugins page to green
- Switch add-ons menu to green
=> Use a couple green links

classes/controllers/FrmEntriesController.php, classes/controllers/FrmFormActionsController.php, classes/helpers/FrmCSVExportHelper.php, classes/helpers/FrmEntriesHelper.php, classes/helpers/FrmEntriesListHelper.php, classes/models/FrmEntry.php, classes/views/frm-entries/_sidebar-shared-pub.php, css/frm_admin.css, images/icons.svg, tests/misc/test_FrmCSVExportHelper.php
This PR modifies is_draft column in entries list table and also add entry status to [entry details](https://gyazo.com/f9a2eaaf9c779b4a3f61205b5f6d75ba).
https://github.com/Strategy11/formidable-pro/pull/4352
https://github.com/Strategy11/formidable-abandonment/pull/27
=> Entry statuses

changelog.txt, readme.txt
So far there isn't much in Lite for next week.
What will also be included:
- https://github.com/Strategy11/formidable-forms/pull/1262
=> Update changelog for 6.4.2

classes/controllers/FrmAddonsController.php, classes/controllers/FrmAppController.php, classes/helpers/FrmAppHelper.php, classes/helpers/FrmCurrencyHelper.php, classes/helpers/FrmEntriesHelper.php, stripe/controllers/FrmStrpLiteActionsController.php, stripe/controllers/FrmStrpLiteAppController.php, stripe/controllers/FrmStrpLiteEventsController.php, stripe/controllers/FrmStrpLiteLinkController.php, stripe/controllers/FrmTransLiteActionsController.php, stripe/controllers/FrmTransLiteListsController.php, stripe/controllers/FrmTransLiteSubscriptionsController.php, stripe/helpers/FrmStrpLiteConnectApiAdapter.php, stripe/helpers/FrmStrpLiteConnectHelper.php, stripe/helpers/FrmStrpLiteLinkRedirectHelper.php, stripe/helpers/FrmStrpLiteSubscriptionHelper.php, stripe/helpers/FrmTransLiteAppHelper.php, stripe/helpers/FrmTransLiteListHelper.php, stripe/js/frmstrp.js, stripe/models/FrmStrpLiteAuth.php, stripe/models/FrmStrpLitePaymentTypeHandler.php, stripe/models/FrmTransLiteAction.php, stripe/views/action-settings/payments-options.php
=> Update since versions

stripe/models/FrmStrpLiteAuth.php
I just noticed that Stripe Lite was missing https://github.com/Strategy11/formidable-stripe/pull/271/files when looking through code.
=> Add conditional redirect fix

stripe/controllers/FrmStrpLiteLinkController.php
This update includes the https://github.com/Strategy11/formidable-stripe/pull/290 and https://github.com/Strategy11/formidable-stripe/pull/291 fixes but for Stripe Lite.
=> Apply Stripe PRs 290 and 291

classes/controllers/FrmAddonsController.php, classes/views/shared/views-info.php
Pass params like class to FrmAddonsController::conditional_action_button
See related pr https://github.com/Strategy11/formidable-pro/pull/4455
=> Fix Views page content button size and position

stripe/controllers/FrmStrpLiteLinkController.php, stripe/helpers/FrmStrpLiteConnectHelper.php, stripe/helpers/FrmStrpLiteSubscriptionHelper.php
I'm mirroring this recent Stripe fix into Stripe Lite.
https://github.com/Strategy11/formidable-stripe/pull/294
🚀
=> Apply Stripe fix 294

stripe/controllers/FrmStrpLiteAppController.php, stripe/controllers/FrmStrpLiteHooksController.php, stripe/controllers/FrmStrpLiteLinkController.php, stripe/controllers/FrmTransLiteActionsController.php, stripe/helpers/FrmStrpLiteUrlParamHelper.php, stripe/models/FrmStrpLiteAuth.php, tests/misc/test_FrmSerializedStringParserHelper.php
This requires a small Connect API update to work with subscriptions.
Related update https://github.com/Strategy11/formidable-stripe/pull/298
=> Apply Stripe fix 298

classes/controllers/FrmAppController.php, classes/helpers/FrmAppHelper.php, classes/helpers/FrmTipsHelper.php, classes/views/shared/upgrade_overlay.php, js/formidable_admin.js
- a sentance in a modal was incomplete
See https://github.com/Strategy11/formidable-pro/pull/4461
=> Fix partial phrase

stripe/controllers/FrmStrpLiteLinkController.php
Related update https://github.com/Strategy11/formidable-stripe/pull/301
=> Apply Stripe fix 301

classes/controllers/FrmAppController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4446
=> Check that wp_set_script_translations exists

classes/controllers/FrmFormsController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4223
=> form preview - block theme padding

css/frm_admin.css
This PR focuses on implementing UI improvements and rectifying inconsistencies identified by Razvan, including button hover states, cursor pointers, shadow consistencies, and enhancing chevron behavior in the form builder.
https://github.com/Strategy11/formidable-pro/tree/issue-4301
[UI enhancements and inconsistencies #4301](https://github.com/Strategy11/formidable-pro/issues/4301)
https://qa.formidableforms.com/sherv12/wp-admin/?page=formidable-views-editor&view=19
1. Check that disabled buttons no longer show hover styling.
2. Verify 'cursor:pointer' appears on the "Insert view into application" chevron and similar elements.
3. Confirm shadow consistency on the Application page and ensure it matches the style templates.
4. Evaluate the improved chevron behavior when …
=> Address UI Enhancements and Inconsistencies

tests/fields/test_FrmFieldFormHtml.php
With https://github.com/Strategy11/formidable-forms/pull/1372/ we no longer want to expect these things for checkboxes.
I'm just updating the test to reflect that.
=> Fix checkbox group role unit tests

classes/helpers/FrmEntriesHelper.php
Fix https://github.com/Strategy11/formidable-pro/issues/4519 along with https://github.com/Strategy11/formidable-pro/pull/4544
=> Change function visibility to public

classes/helpers/FrmAppHelper.php, stripe/controllers/FrmStrpLiteEventsController.php, stripe/controllers/FrmStrpLiteLinkController.php, stripe/controllers/FrmTransLiteAppController.php, stripe/controllers/FrmTransLiteHooksController.php, stripe/controllers/FrmTransLiteListsController.php, stripe/helpers/FrmStrpLiteSubscriptionHelper.php, stripe/helpers/FrmTransLiteAppHelper.php, stripe/helpers/FrmTransLiteListHelper.php, stripe/models/FrmTransLiteDb.php, stripe/models/FrmTransLitePayment.php, stripe/models/FrmTransLiteSubscription.php, stripe/views/payments/show.php, stripe/views/subscriptions/show.php
Fixes https://github.com/Strategy11/formidable-pro
=> Add a test flag for stripe lite payments

classes/models/FrmDb.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4616
Casting to an `NCHAR` seems a bit more straight forward than using `DATE_FORMAT`.
=> Use cast to char instead of date format

classes/models/FrmEmailSummary.php, classes/views/summary-emails/base-plain.php, classes/views/summary-emails/stats-plain.php
Steph reported in https://github.com/Strategy11/formidable-forms/pull/1248#pullrequestreview-1775782787
=> Summary emails improvements

changelog.txt, readme.txt
I'm requesting review because everything needs an approval now.
I also need https://github.com/Strategy11/formidable-forms/pull/1409 and https://github.com/Strategy11/formidable-forms/pull/1413 reviewed.
=> Update readme for v6.7

changelog.txt, readme.txt
=> Remove dashboard from 6.7 change log

js/formidable_admin.js
This is required for a Surveys fix.
I also fixed some variables aren't declared before using.
=> Add new JS filter for getFieldList()

classes/models/FrmForm.php
Fix https://github.com/Strategy11/formidable-pro/issues/4652
=> Only count parent forms in permanently deleted forms message

classes/helpers/FrmAppHelper.php, classes/models/FrmEntryFormatter.php, classes/models/FrmEntryValidate.php, classes/models/fields/FrmFieldType.php, js/admin/dom.js, js/formidable_admin.js, tests/fields/test_FrmFieldType.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4647
=> Pro issue 4647

classes/views/frm-settings/permissions.php
Kristine caught this and posted a comment in ClickUp https://app.clickup.com/t/8686wyxww?comment=90110034928743&threadedComment=90110035146292
I updated the name of the permission but there's a note that mentions the permission as well that I missed.
=> Mention "View Forms List" in permission description as well

changelog.txt, readme.txt
I changed a was to a would and the getting seemed off afterward.
=> Adjust readme grammar

classes/helpers/FrmFormsHelper.php, tests/forms/test_FrmFormsHelper.php
This is to cover the regression introduced with v6.7.1 so it doesn't happen again.
=> Add tests for FrmFormsHelper::get_form_style

classes/helpers/FrmEntriesListHelper.php, css/frm_admin.css
=> Use meta tag for entry status

classes/helpers/FrmStylesHelper.php
I missed running PHPCS on https://github.com/Strategy11/formidable-forms/pull/1473.
This moves the logic into a new function to avoid the long if.
=> PHP fix (long if in styleshelper

stripe/controllers/FrmStrpLiteAppController.php, stripe/controllers/FrmStrpLiteLinkController.php, stripe/helpers/FrmStrpLiteConnectHelper.php, stripe/helpers/FrmStrpLiteLinkRedirectHelper.php, stripe/helpers/FrmStrpLiteSubscriptionHelper.php, stripe/js/frmstrp.js, stripe/models/FrmStrpLiteAuth.php
This includes 3 Stripe Add-on Updates,
- https://github.com/Strategy11/formidable-stripe/pull/315
- https://github.com/Strategy11/formidable-stripe/pull/316
- https://github.com/Strategy11/formidable-stripe/pull/318
=> Add Stripe PRs 315, 316, and 318

classes/helpers/FrmEmailSummaryHelper.php, classes/models/FrmEmailSummary.php, classes/views/summary-emails/base-plain.php, classes/views/summary-emails/stats-plain.php
Related comment https://github.com/Strategy11/formidable-forms/pull/1457#discussion_r1455855184
=> New function FrmEmailSummaryHelper::plain_text_echo

js/formidable_admin.js
=> Resolve Display Issue of Install Add-On Buttons in Formidable Forms (Lite Version PR)

js/formidable_admin.js
Related comment chain https://github.com/Strategy11/formidable-forms/pull/1442#discussion_r1465235449
=> Clean up issue 4672

css/frm_admin.css
Add `#permissions_settings_settings .frm_primary_label` to the frm_admin.css, Original issue https://github.com/Strategy11/formidable-abandonment/pull/35#discussion_r1466353480
=> Add frm primary label style

classes/models/FrmUsage.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4781
FrmUsage's new `/snapshot` URL is https://usage.formidableforms.com/app/snapshot
=> Update FrmUsage's `/snapshot` URL

js/formidable.js
This is required for https://github.com/Strategy11/formidable-stripe/pull/324
=> Pass response content to frmSubmitEvent event

classes/controllers/FrmSettingsController.php, js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/4753
=> Fix Pro issue 4753

classes/controllers/FrmAddonsController.php, classes/models/FrmFormApi.php
Related issue https://github.com/Strategy11/formidable-pro/issues/4825
I'm branching off of https://github.com/Strategy11/formidable-forms/pull/1517 as it includes related requirements.
=> Stop sending license expired email if rate limited

js/formidable_admin.js
Fix https://github.com/Strategy11/formidable-pro/issues/4796
This is an alternative fix to https://github.com/Strategy11/formidable-pro/pull/4816 suggested by Mike.
=> Try using a placeholder element and replacing it with ajax response

classes/models/FrmFieldCaptchaSettings.php, classes/models/FrmRecaptchaSettings.php, classes/models/FrmSettings.php
I forgot to run this workflow and there were a couple small errors.
=> Turnstile phpcs fixes

css/codemirror.css, css/frm_old_grids.css
These have been deprecated for a little while.
I think it should be fine to remove them.
=> Drop old css files

classes/views/frm-forms/add_form_style_options.php
Jonathan just pointed this out in Slack.
=> Fix typo horizonally

js/formidable.js
Related PR https://github.com/Strategy11/formidable-views/pull/492
=> New js event frmFormCompleteBeforeReplace

classes/controllers/FrmFormsController.php, classes/helpers/FrmAppHelper.php, classes/models/FrmDb.php, classes/models/FrmEntry.php, classes/models/FrmEntryMeta.php, classes/models/FrmField.php, classes/models/FrmForm.php
As I was adding stubs to views, I added in some missing type comments.
=> Add more type comments

classes/helpers/FrmAppHelper.php, deprecated/FrmDeprecated.php
Some functions I'm just bumping down to the bottom of the file.
=> Drop some old deprecated functions

.gitignore, bin/zip-plugin.sh, classes/controllers/FrmAddonsController.php
I'm going to ignore these files since this isn't going to ever make it into Git but I plan to keep this locally.
=> Ignore sonar files in zip

cypress.config.js, tests/cypress/e2e/formidable-admin.cy.js
This update adds a few more checks.
It confirms you can save a form name in form settings, preview a form, and submit it.
🚀
=> Improve e2e tests

classes/controllers/FrmAppController.php
The string "Global Settings" in FrmAppController.php is not displayed translated
=> The string "Global Settings" in FrmAppController.php is not displayed translated

classes/controllers/FrmStylesController.php
Fix: [i18n] The strings in Style are not displayed translated
=> Fix: [i18n] The strings in Style are not displayed translated

classes/controllers/FrmFormActionsController.php, classes/helpers/FrmAppHelper.php
I was adding some of these functions as stubs and added the missing types as I went.
=> Add some missing type comments

.eslintrc.json, js/formidable.js, js/formidable_admin.js, package-lock.json, package.json
See https://github.com/SonarSource/eslint-plugin-sonarjs
This update adds additional eslint rules based on the Sonar JS eslint plugin.
=> Add sonar js eslint ruleset

js/formidable.js
This helps reduce the JS slightly.
=> Update hasClass function to use a more modern classList.contains check

js/formidable.js
This update drops the additional code that was only there to support IE.
=> Simplify trigger custom event function

classes/helpers/FrmXMLHelper.php
This is similar to https://github.com/Strategy11/formidable-views/issues/512 but for the Map views address field setting.
=> Map new address field ids on map view import

css/frm_admin.css
This makes the border change in a more meaningful way I think.
=> Update no fields border styling

classes/helpers/FrmAppHelper.php
Ticket URL: https://secure.helpscout.net/conversation/2599522042/199655
=> Fix deprecated notice when calling trim

classes/models/FrmEmailSummary.php
Ahmed reported this issue in https://strategy11.slack.com/archives/C799A2R61/p1716581430220459?thread_ts=1716579657.158929&cid=C799A2R61
=> Move summary_email_content_args filter to get_content_args()

classes/helpers/FrmAppHelper.php
I'm just removing an old deprecated function that was doing nothing, and added some type comments. I also made a use of `apply_filters` return a more guaranteed boolean value.
=> Do some small FrmAppHelper tweaks

classes/controllers/FrmFormsController.php
On my form with 1,004 fields, 66 of them are HTML fields.
Each field calling this code takes 0.008 seconds. `0.008 * 65 = 0.52`, so just over a second is saved here.
=> Store and reuse tinymce formdiable button optimization

classes/helpers/FrmAppHelper.php, classes/helpers/FrmFormsHelper.php, classes/views/frm-fields/back-end/settings.php
This helps reduce white space and some duplicate logic slightly.
=> Small tweaks/cleanup

classes/controllers/FrmFieldsController.php
This update just adds some type comments and remove some useless braces.
=> Clean up FrmFieldsController.php

classes/helpers/FrmEntriesHelper.php
This is just some tiny tweaks.
I reduced 2 checks into a `! empty` and made one check strict.
=> Clean up FrmEntriesHelper

css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/4946
=> Pro issue 4946 / Hide notices on import/export page

css/frm_admin.css
This is just a small tweak. The same style opens/closes here. This update merges it so it's all in one selector.
=> Merge duplicate style selectors

classes/helpers/FrmXMLHelper.php, psalm.xml
This update aims to improve our Psalm coverage for a few errors.
=> Ignore psalm errors in fewer files

classes/models/FrmFieldValueSelector.php, stubs.php
=> Use the right class name in comment fix

stripe/controllers/FrmTransLitePaymentsController.php
Fix https://github.com/Strategy11/formidable-pro/issues/5177
=> Show new pill beside payments menu item

languages/formidable.pot
Some line numbers changed after an update was merged.
=> Update pot file for v6.11.1 release

classes/controllers/FrmAppController.php
=> Update since version

classes/helpers/FrmAppHelper.php
This just remove useless parentheses, makes some checks strict, and removes a comment that doesn't add anything.
=> Clean up `FrmAppHelper::is_true` function

classes/models/FrmField.php, languages/formidable.pot
This is part of the Crowdin LQAs.
I'm also updating several other upgrade messages. None of these were translating.
=> Translate ranking field upsell message

classes/helpers/FrmStylesPreviewHelper.php
Fix https://github.com/Strategy11/formidable-pro/issues/5171
**Before**
**After**
=> Simplify preview note in Visual Styler

classes/views/frm-entries/sidebar-show.php, classes/views/frm-fields/radio.php, classes/views/frm-fields/show-build.php, classes/views/frm-forms/_embed_form_icons.php, classes/views/frm-forms/create-template-from-an-existing-form.php, classes/views/frm-forms/list-template.php, classes/views/frm-forms/list-templates.php, classes/views/frm-forms/multiselect-accessibility.php, classes/views/frm-forms/new-form-overlay/code-from-email.php, classes/views/frm-forms/new-form-overlay/upgrade-body.php, classes/views/frm-forms/new.php, classes/views/frm-forms/sidebar-settings.php, classes/views/frm-settings/recaptcha.php, classes/views/styles/_upsell-multiple-styles.php, classes/views/styles/header-buttons.php
Most of these have no content and have been deprecated for a while.
I'm just cleaning up a bit.
=> Drop old deprecated view files

stripe/controllers/FrmTransLitePaymentsController.php
Related issue: https://github.com/Strategy11/formidable-payments/issues/91
=> Translate Payments submenu page title

classes/models/FrmField.php, js/formidable_admin.js, languages/formidable.pot
Fix https://github.com/Strategy11/formidable-pro/issues/5183
=> Translate upsell popup messages

classes/models/FrmEntryValidate.php
Fixing formatting from https://github.com/Strategy11/formidable-forms/pull/1866
I'm also adding some comments to provide more context.
=> Fix pr 1866 formatting

classes/controllers/FrmFormActionsController.php
Fixes https://github.com/Strategy11/formidable-forms/issues/1881
I also added some comments for more context.
=> Fix issue 1881 / pass $filter_args to frm_trigger_create_action filter

js/formidable_admin.js
Related issue: https://github.com/Strategy11/formidable-pro/issues/5202
=> Trigger a new action hook after field is deleted

classes/helpers/FrmFormsHelper.php
Fix https://github.com/Strategy11/formidable-pro/issues/5244
=> Improve frm_button_submit class check in `FrmFormsHelper::get_custom_submit` function

classes/models/FrmEntryFormatter.php
Fixes https://github.com/Strategy11/formidable-pro/issues/5253
=> Exclude submit field from entry table

classes/helpers/FrmEntriesListHelper.php, classes/helpers/FrmFormsListHelper.php, tests/cypress/e2e/admin-a11y.cy.js
Fix https://github.com/Strategy11/formidable-pro/issues/5239
=> Add label to entries list checkboxes

classes/models/FrmFormState.php
Related issue: https://github.com/Strategy11/formidable-pro/issues/5234
=> Check if openssl_encrypt function is defined before attempt to call it

js/formidable.js
=> Stop using jQuery hasClass to check if JS validation is enabled

classes/controllers/FrmAppController.php, classes/controllers/FrmEntriesController.php
The old check for the nested views inside of Pro is no longer required, so I'm simplifying these checks.
=> Simplify views checks

stripe/controllers/FrmTransLiteAppController.php, stripe/models/FrmTransLiteLog.php
Related issue https://github.com/Strategy11/formidable-pro/issues/5200
=> Pro issue 5200 / Stop logging overdue cron count as an error

js/formidable.js
I believe this is related to https://github.com/Strategy11/formidable-forms/pull/1912/
My Stripe form was failing.
=> Make hasClass function safer

stripe/views/payments/entry_sidebar.php
This was copied over from the Payments submodule.
It is never actually used though.
=> Deprecate unused view

classes/models/fields/FrmFieldText.php
Fix https://github.com/Strategy11/formidable-pro/issues/5295
=> Use FrmAppHelper::mb_function to use mb_strlen when it is available

js/formidable.js
I'm just trying to read this code and having the type comment would have helped.
=> Add type comments to front end js

css/frm_admin.css
Fix https://github.com/Strategy11/formidable-pro/issues/5227
=> Make merge into row popup appear on top of section styling

css/custom_theme.css.php
This PR resolves style issues with radio buttons and checkboxes that appeared after the recent style update.
https://github.com/Strategy11/formidable-pro/pull/5323
[208510](https://secure.helpscout.net/conversation/2691959080/208510?folderId=2445391), [208405](https://secure.helpscout.net/conversation/2690942720/208405?folderId=2445394), [208389](https://secure.helpscout.net/conversation/2690874071/208389/)
https://www.loom.com/share/ff2125f4e30b426e8159ffc9f2190b6c
=> Checkbox and Radio Button Style Issues After New Style Update

phpstan.neon, stubs.php
I'm cleaning up the php stan exceptions a bit.
=> Add stubs for cache plugins

js/formidable.js
Reverts Strategy11/formidable-forms#1961
I just tested this after merging.
This doesn't appear to really solve the issue.
See https://github.com/Strategy11/formidable-forms/pull/1961#issuecomment-2338545197
=> Revert "Support fields validation with captcha"

stripe/models/FrmTransLiteAction.php
Related issue https://github.com/Strategy11/formidable-pro/issues/3328
=> Include (first) and (last) when mapping name fields to stripe lite actions

tests/cypress/e2e/Forms/formPageDataValidation.cy.js
I updated this link and the e2e test broke.
=> Fix cypress upgrade link check

classes/models/FrmEmailSummary.php
See thread in https://github.com/Strategy11/formidable-ai/pull/74#discussion_r1763965021 for context.
=> Adapt `FrmEmailSummary` to support `FrmAIEmailCreditAlert`

classes/controllers/FrmDeactivationFeedbackController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/5417
This is a simple fix.
[formidable-6.15.1b.zip](https://github.com/user-attachments/files/17307931/formidable-6.15.1b.zip)
=> Fix white div at the bottom of plugins page

classes/controllers/FrmAppController.php, classes/models/FrmInbox.php, classes/models/FrmMigrate.php
More details in Slack https://strategy11.slack.com/archives/C07AXBKUX5X/p1728503937825869
=> Add first activation option

css/admin/addons-page.css
=> Fix some add-ons icons appearing greyed out

stripe/models/FrmStrpLitePaymentTypeHandler.php
The "string "automatic"" part of this isn't accurate. For automatic, we just expect an empty array.
=> Fix invalid doing it wrong message

classes/models/FrmEntryMeta.php
The Pro unit tests caught this issue.
=> Add isset check in `should_join_fields_table`

classes/controllers/FrmAddonsController.php, classes/controllers/FrmFormsController.php, classes/helpers/FrmAppHelper.php, classes/helpers/FrmFormActionsHelper.php, classes/helpers/FrmFormsHelper.php, classes/helpers/FrmStylesHelper.php, classes/models/fields/FrmFieldType.php
All of these should be low risk to remove.
=> Remove several deprecated functions

changelog.txt, classes/models/FrmFieldFormHtml.php, readme.txt
Related PR https://github.com/Strategy11/formidable-forms/pull/2005
Fixes https://github.com/Strategy11/formidable-pro/issues/5395
=> Re-apply PR 2005

stripe/controllers/FrmStrpLiteEventsController.php
Applies https://github.com/Strategy11/formidable-stripe/pull/378/files
=> Add stripe PR 378

readme.txt
=> Update tested to version

classes/views/frm-fields/front-end/dropdown-field.php, package-lock.json, package.json
Related PR https://github.com/Strategy11/formidable-pro/pull/5488/
=> Add new action frm_dropdown_field_after_no_placeholder_option

classes/helpers/FrmFieldsHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/5484
=> Pro issue 5484

css/_single_theme.css.php, css/custom_theme.css.php
I'm confident we don't need any of this anymore.
=> Remove old deprecated css

js/formidable.js
This update just simplifies the code a bit, removing some extra logic that just adds to the amount of code.
=> Remove extra function calls

css/_single_theme.css.php
The selectors were identical, so I'm just merging two styles.
=> Merge two style selectors

classes/views/frm-forms/add_field.php, css/frm_admin.css
Fix https://github.com/Strategy11/formidable-pro/issues/5522
Before:
After:
=> Fix repeater icon conflict with section icon

classes/models/FrmUsage.php
Related ticket https://secure.helpscout.net/conversation/2785831043/217529
[formidable-6.16.3b.zip](https://github.com/user-attachments/files/18062655/formidable-6.16.3b.zip)
=> Check if payments exist when running usage cron

stripe/controllers/FrmTransLiteCRUDController.php
Related issues: https://github.com/Strategy11/formidable-payments/issues/61 and https://github.com/Strategy11/formidable-payments/issues/61
=> Handle viewing payment that does not exist

classes/controllers/FrmFormActionsController.php, classes/models/FrmFormAction.php
This should help save our customers time troubleshooting, and reduce in the number of related support tickets.
=> Add form action limit warning

classes/helpers/FrmAppHelper.php, classes/models/FrmMigrate.php
I'm also dropping the `FrmAppHelper::$pro_db_version` variable. This shouldn't be used anywhere.
=> Add form_id type index to fields table

classes/controllers/FrmXMLController.php
This is required for a Pro PR.
=> Add url to frm_xml_response filter

css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/5624
=> Fix deactivation modal overlay doesn't show

classes/helpers/FrmFieldsHelper.php, classes/views/frm-forms/add_field.php
After importing some forms with Pro fields into Lite, after falling back, some of the Lite code is throwing warnings.
=> Fix php warnings

classes/models/FrmEmail.php
Fixes https://github.com/Strategy11/formidable-pro/issues/5696
=> Fix pro issue 5696

classes/models/fields/FrmFieldTextarea.php
Fixes https://github.com/Strategy11/formidable-pro/issues/5707
=> Show paragraph field placeholder in builder

js/formidable_admin.js
The submit button conditional logic all just uses regular field conditional logic files now.
=> Remove old unused admin JS

js/formidable_admin.js
Required for https://github.com/Strategy11/formidable-pro/pull/5725
This allows me to initialize datepickers when a date field option is selected for conditional logic.
=> Trigger new event when loading logic row data

stripe/controllers/FrmStrpLiteActionsController.php
[formidable-6.20.1b.zip](https://github.com/user-attachments/files/19914220/formidable-6.20.1b.zip)
=> Apply circle field shape to stripe link inputs

stripe/controllers/FrmStrpLiteActionsController.php, stripe/controllers/FrmTransLiteActionsController.php, stripe/js/frmstrp.js, stripe/views/action-settings/options.php
Fix https://github.com/Strategy11/formidable-stripe/issues/387
=> Add new layout option for Stripe link

stripe/models/FrmStrpLiteAuth.php
Related PR https://github.com/Strategy11/formidable-stripe/pull/401
=> Apply Stripe PR 401

tests/cypress/e2e/Form Templates/FormTemplates.cy.js
The check is looking for the old grammar error.
=> Fix e2e test on templates page

classes/models/FrmEntryValidate.php
Fixes https://github.com/Strategy11/formidable-pro/issues/5803
=> Fix issue with validating user defined product fields

classes/models/FrmHoneypot.php, classes/views/frm-entries/form.php
Related comment https://github.com/Strategy11/formidable-forms/pull/2364#issuecomment-2880759494
=> Use max field id for honeypot

classes/controllers/FrmInboxController.php
Related ticket https://secure.helpscout.net/conversation/2939846232/230052
=> Change required permission to dismiss inbox notices

classes/models/FrmEntryValidate.php
Related ticket https://secure.helpscout.net/conversation/2959537651/231657
In this case, the option is being modified by `the_content` filter.
[formidable-6.21.4b.zip](https://github.com/user-attachments/files/20628276/formidable-6.21.4b.zip)
=> Do another option validation check after applying the_content filter

stripe/helpers/FrmTransLiteListHelper.php
Related ticket https://secure.helpscout.net/conversation/2963601106/231978
[formidable-6.21.2b.zip](https://github.com/user-attachments/files/20677155/formidable-6.21.2b.zip)
=> Fix incorrect link to payment when filtering by form

classes/helpers/FrmXMLHelper.php
Fixes https://github.com/Strategy11/formidable-views/issues/650
=> fix the timeline view option on import

js/formidable_admin.js
Fix https://github.com/Strategy11/formidable-pro/issues/5851
=> Fix JS error when interacting with field options in builder

classes/models/FrmEntryValidate.php, classes/models/fields/FrmFieldType.php
Related ticket https://secure.helpscout.net/conversation/3001279551/234316
Somehow they have a Date and Text field with invalid option data.
[formidable-6.22.4b.zip](https://github.com/user-attachments/files/21221965/formidable-6.22.4b.zip)
=> Only validate expected field types

classes/models/fields/FrmFieldGdpr.php
Related ticket https://secure.helpscout.net/conversation/3000731375/234273
[formidable-6.22.4b.zip](https://github.com/user-attachments/files/21232495/formidable-6.22.4b.zip)
=> Add gdpr agreement text to translatable strings array for GDPR field

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/5230
=> Do not allow gdpr fields in repeaters and prevent new sections in field groups in sections

classes/models/FrmTableHTMLGenerator.php, tests/phpunit/entries/test_FrmShowEntryShortcode.php
Fix https://github.com/Strategy11/formidable-quizzes/issues/229
=> Improve tables accessibility

classes/helpers/FrmAppHelper.php
This was still using font icons and the size wasn't really consistent with the same input for searching entries.
=> Update search icon used in form search

css/admin/applications.css
Fixes https://github.com/Strategy11/formidable-pro/issues/6001
=> Set modal max height and allow for scroll on applications page

classes/helpers/FrmEntriesHelper.php, rector.php
This is another rector rule. For consistency it makes sense to enforce this automatically.
=> Use implode instead of join

square/controllers/FrmSquareLiteAppController.php
[formidable-6.24.2b.zip](https://github.com/user-attachments/files/22621123/formidable-6.24.2b.zip)
=> Stop sending empty address data when verifying Square buyer
