classes/controllers/FrmAppController.php, classes/controllers/FrmFormsController.php, classes/controllers/FrmHooksController.php, classes/controllers/FrmSettingsController.php, classes/controllers/FrmStatisticsController.php, classes/controllers/FrmStylesController.php, classes/controllers/FrmXMLController.php, classes/helpers/FrmAppHelper.php, classes/helpers/FrmFieldsHelper.php, classes/helpers/FrmFormActionsHelper.php, classes/helpers/FrmFormsHelper.php, classes/helpers/FrmFormsListHelper.php, classes/helpers/FrmStylesHelper.php, classes/helpers/FrmXMLHelper.php, classes/models/FrmDb.php, classes/models/FrmEntry.php, classes/models/FrmEntryMeta.php
@stephywells requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/Strategy11/formidable-forms/
=> Scrutinizer Auto-Fixes

css/frm_admin.css
https://github.com/Strategy11/formidable/issues/1455
This is problems with css to show the list of triggers.
=> Fixing the issues/1455

classes/widgets/FrmShowForm.php
Changed title processing to match WordPress core widgets. A blank title will output nothing, just like core widgets, instead of using the form title in the absence of a widget title. I think this is more predictable behaviour. WordPress core implementation can be found at `wp-includes/widgets/class-wp-widget-pages.php line 55`.
=> Blank Widget Title like WordPress Core

tests/base/FrmUnitTest.php
The WP-develop bootstrap file only hooks into `pre_option` for options added to the `wp_tests_options` array, but `pre_option` is not used by `get_site_option()`, which affects multisite testing. Even though Pro is installed and active, the `is_pro_active` var shared by all unit tests is set to `false` because of this, and producing some errors such as field counts not matching.
=> Workaround WP unit testing bootstrap issue for multisite

.travis.yml
Travis uses PHPUnit 7 on PHP 7.1, which results in this [compat code from WordPress-develop](https://github.com/WordPress/wordpress-develop/blob/master/tests/phpunit/includes/phpunit6-compat.php#L18) being executed:
```
class PHPUnit_Util_Test extends PHPUnit\Util\Test {
....
}
```
but `PHPUnit\Util\Test` is a **final** class on PHPUnit 7.0, which produces a fatal error and the failure of the build:
```
PHP Fatal error:  Class PHPUnit_Util_Test may not inherit from final class (PHPUnit\Util\Test) in /tmp/wordpress/tests/phpunit/includes/phpunit6-compat.php on line 18
```
=> Fix Travis build on PHP 7.1 + master

classes/models/FrmEntryFormatter.php
So we can choose which fields has to be hidden from [default-message] email content.
=> Add new frm_include_field_in_content filter in include_field_in_content method

classes/controllers/FrmFormsController.php
I'm not sure if it would be better for the do_shortcode to come before or after the URL filter.
What do you think?
=> Adds the ability to use shortcodes in a form's redirect URL.

classes/models/FrmSettings.php
There is an extra space in the default `failed_msg` text string.
=> Extra space in failed_msg text

js/formidable_admin.js
Thank you for this -- https://github.com/Strategy11/formidable/issues/2049.
I like this approach much more.  It should eliminate all or most of the false positives that annoy people.  
I've allowed more formats with created_at to trigger the warning.  Is that okay?  If not, I'd be happy to do just Y-m-d.  And make any other changes you'd like.
=> Reduces cases that trigger admin calculation warning.

css/_single_theme.css.php
This helps to give adequate spacing between a section and its immediate siblings (above and below) especially between a section that's the last item in a form and the submit button.
=> Add margin-bottom 15px to sections to match their margin-top value

classes/helpers/FrmFieldsHelper.php
@stephywells I hadn't pushed this change before you merged issue/pro/2189
=> Add support for '0' in 'other' field text input

classes/helpers/FrmAppHelper.php
So that it can be used anywhere in the plugin
=> Make FrmAppHelper::decode_specialchars public

classes/models/FrmForm.php
Hi,
Could we add this filter to the FrmForm::getOne method so we can hook on form attributes ? 
The `frm_pre_display_form` filter is not called on the `getOne` method which is called when autosaving drafts on multiple steps forms.
Thanks.
=> Adding a `frm_pre_get_one` filter 

classes/models/fields/FrmFieldType.php
https://github.com/Strategy11/formidable-pro/issues/2405
Before the explode, I'm checking for exact matches on the csv string, and removing the specific csv items.
This could possibly fall apart if we had too many similar looking options, like:
"red, green, blue"
"red, green, blue, white"
Where if red, green, blue was selected, it would also remove the red, green, blue from red, green, blue, white.
But I think this update will at least leave us in better shape without having to change much.
=> import fix for csv checkbox values

classes/models/fields/FrmFieldType.php
[The first commit](https://github.com/Strategy11/formidable-forms/pull/204) was merged pretty quickly, but I had actually made a second that changes the equals to a strpos check. I think the first fix would only work is there was one item selected.
May also be nice to add unit tests around this.
=> use strpos for partial matches

classes/models/fields/FrmFieldType.php, tests/fields/test_FrmFieldType.php
Another follow-up to https://github.com/Strategy11/formidable-forms/pull/207
I took some liberty here in reversing the array. I assume it's more likely that the options would appear as 
```
$field->options = array(
array( 'value' => 'a', 'label' => 'A' ),
array( 'value' => 'b', 'label' => 'B' ),
array( 'value' => 'c', 'label' => 'C' ),
array( 'value' => 'a,b', 'label' => 'A, B' ),
array( 'value' => 'a,b,c', 'label' => 'A, B, C' ),
array( 'value' => 'a, b, c', 'label' => 'A, B, C' ),
);
```
than as
```
$field->options = array(
array( 'value' => 'a,b', 'label' => 'A, B' ),
array( 'value' => 'a,b,c', 'label' => 'A, B, C' ),
array( 'value' => 'a, b, c', 'label' => 'A, B, C' ),
array( 'value' => 'a', 'label' => 'A' ),
array( 'value' => 'b', 'label' => 'B' ),
array( 'value' => 'c', 'label' => …
```
=> add unit testing for get multi opts for import

classes/helpers/FrmAppHelper.php, tests/base/FrmUnitTest.php, tests/forms/test_FrmFormsHelper.php
Follow-up from the broken tests in https://github.com/Strategy11/formidable-forms/pull/193
Took a couple of tries to get this working in travis (it was fine locally).
`Adminstrator should not be able to see a form without an exact array match`.
First thought was that the tests are checking for things that aren't valid settings, but that didn't seem to effect the test breaking.
Second thought, is that administrator might actually pass the "current_user_can" check for subscriber, so I'm switching to an exact array match.
It was still failing for custom roles though, so I fixed that as well by calling `set_user_by_role` like we do for other roles. I also think it's possible that the custom role would have originally passed an editor check, so I'm changing the test to check for exact matches …
=> loggedout is not a valid form visibility fix

tests/base/FrmUnitTest.php
One step closer to running unit tests normally in PHP 7.3 :)
=> load pro hooks in frm unit test constructor

tests/base/FrmUnitTest.php
I think this should fix the issue with https://travis-ci.com/github/Strategy11/formidable-pro/jobs/371232530 failing, but I'm not actually getting the error.
I just think that set_user_by_role might be getting another user then the one I just stripped, that has editor permissions for whatever reason.
This should be safer, guarantees we actually set the user we're modifying.
=> use frm role formidable custom role case logic update

tests/forms/test_FrmForm.php
Just a small thing. Noticed when the test was moved that the comment wasn't updated :)
=> frm form is visible to user comment wording update

classes/helpers/FrmXMLHelper.php
Working from Steph's commit [here](https://github.com/Strategy11/formidable-forms/commit/43bc0cd6f91ad3358ac4fcd014882125b57c4bdd) I have a branch that can successfully import the default calculator value in from [here](https://github.com/Strategy11/formidable-pro/issues/2566).
I don't know for sure if this encompasses the whole issue for https://github.com/Strategy11/formidable-pro/issues/1362
My issue seems mostly specific to the fact that these fields already existed and weren't being created new on import.
I have to do two replaces, one that changes their original expected id to their field key, and one that changes their field key to their new id. This way I can avoid issues of it changing my value into an id, and then changing that id into another id that wasn't the proper match. …
=> Xml field import fix for preexisting fields

classes/models/FrmFieldFormHtml.php
https://github.com/Strategy11/formidable-pro/issues/2584
This will not update in real time without JavaScript validation turned on. But it will always render `aria-invalid="false"` now for valid inputs.
This should be fine. Mozilla's documentation states:
```
Note that it is not necessary to validate the fields immediately on blur; the application could wait until the form is submitted (though this is not necessarily recommended).
```
=> always include aria invalid tag

js/formidable_admin.js
While checking if there were issues with pro disabled on https://github.com/Strategy11/formidable-forms/pull/241 I ran into this error that was totally unrelated to my own update.
Happens when I change the text for one of my radio options.
=> sep is null bug fix

classes/helpers/FrmAppHelper.php, js/formidable_admin.js
Resolves https://github.com/Strategy11/formidable-pro/issues/2564
I looked into customizing the text in the pop up but it's a no go these days.
From [a quote I found here](https://stackoverflow.com/questions/38879742/is-it-possible-to-display-a-custom-message-in-the-beforeunload-popup#answer-38880926)
> tl;dr - You can't set custom message anymore in most modern browsers
> A quick note (since this is an old answer) - these days all major browsers don't support custom message in the beforeunload popup. There is no new way to do this. In case you still do need to support old browsers - you can find the information below.
I don't know if we want to go above and beyond this. It seems to cover most cases at least. If you were to toggle a checkbox on and off for instance, it would still say …
=> confirm backend exit

css/frm_admin.css
This was kind of bugging me a couple of times. There's margin on the div but it's not actually being applied with the current styles.
**Before**
**After**
=> top bar updated message margin fix

js/formidable_admin.js
Didn't notice this in the first go, but on https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload they even mention
```
// Chrome requires returnValue to be set
e.returnValue = '';
```
Also adjusted the fieldsUpdated logic to avoid adding the event listener on every field update.
=> chrome does not confirm backend exit fix

classes/controllers/FrmAddonsController.php
I just totally uninstalled formidable and added my license key again, and after I confirmed my license, I refreshed the page.
This update redirects the url so instead of dying on a 403 page, it goes to formidable.
=> add pro redirect from pro upgrade page

js/formidable_admin.js
I'm not totally sure what happened in https://github.com/Strategy11/formidable-pro/issues/2633 but I think he must've triggered the hidden checkbox.
This one liner makes sure that the screen options are disabled on the views editor.
Of course, this update would make it more difficult to actually fix the issue if you had it hidden before updating. I played with forcing the checkbox as checked, but it seemed to lead to issues of the checkbox being checked with the content still hidden as well.
My simple QA method was just running `jQuery('#frm_dyncontent-hide').click();` in the JavaScript console. Before this update, the content would disappear/appear with each call. Now it says visible.
=> disable content checkbox in screen options

js/formidable.js
Tackling the checklist items `Email confirmation fields don't show error message` and `Validate password confirmation fields` from https://github.com/Strategy11/formidable-pro/issues/1392
It requires the message as well, which comes from pro code [here](https://github.com/Strategy11/formidable-pro/pull/2634)
Without it, it just won't display still.
This update also fixes some inconsistencies with the email validation. I tried to make the logic easier to follow/more consistent for the both fields.
Previously, if the confirm field was invalid, it wouldn't become valid if you changed the original email address only to match the confirmation address.
As for the last item on the list, I'm not familiar with the option (`Default value will NOT pass validation`). I see it's defined in …
=> Better email confirmation js validation (and password js validation)

classes/helpers/FrmAppHelper.php
=> adjust message for single day in license expiry reminder

classes/controllers/FrmStylesController.php, classes/helpers/FrmAppHelper.php, classes/views/frm-form-actions/email_action.php, css/_single_theme.css.php, phpcs.xml
Trying to slowly remove exclusions from our code sniffing. Extract only appears 4 times, and I figure it'd better to put the ignore on each of the 4 instances than to allow more in without the flag.
I looked at all 4 instances. I don't think any are too easy to write the extract out from.
Technically removes two rules because it seemed to have duplicates under different namespaces.
There were also duplicate exclusions for `WordPress.NamingConventions.ValidFunctionName.FunctionNameInvalid` which happens to be valid already, so I'm removing both.
=> cs fix, do not exclude extract rule

js/formidable.js
Fixes https://github.com/Strategy11/formidable-pro/issues/1392 for embedded forms
The issue was that the name didn't match the `'conf_' + strippedFieldID` pattern in embedded fields.
I've figured out how to improve the process a bit. I removed the requirement to pass along fields, and I check for exact expected field id values. Uses fewer variables, less jQuery, and it works for embedded forms no problem.
=> better confirm field validation for embedded forms

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/1025 again
Dropdowns just weren't in the scope of my update. I neglected that there were other types with options than radio and checkbox. I made it more generic, targeting the options themselves rather than specific types (it was hard coded to radios and checkboxes only, ignoring select).
I took out the hardcoding so this should catch anything else if there were another type I had missed.
=> dropdown types should also update conditional logic on option change

js/formidable_admin.js
@stephywells were you actually noticing this Everyone always getting selected behaviour on the protected files dropdown rather than the field visibility?
Because it seemed to be an issue here, but I was checking field visibility.
=> update everyone multiselect functionality for secure file roles

classes/controllers/FrmAddonsController.php, js/formidable_admin.js
When `define( 'FS_METHOD', 'ssh2' );` is defined:
I don't actually know how to connect to my local server with ftp so I don't actually know what happens if I submit this form successfully...
Since this is not supported right now, I think it might be better to just strip out all of the form code for now and revisit this next release?
=> Actually show error when ftp creds fail

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/2703
I also noticed that when the duplicate icon is clicked that it the value of `target.parentElement.className` is a [SVGAnimatedString](https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString) which does not have an indexOf function. It throws a JavaScript error, so I'm checking for a string value first.
=> Open an action before duplicate if it has not loaded yet

classes/models/FrmFormAction.php, classes/views/frm-form-actions/_action_inside.php, classes/views/frm-form-actions/email_action.php
I noticed in the aweber notes that you can use the plugin without pro.
I tried this out and there are some UI items that show up for emails for all of the other action types as well. It looks sort of messy, since none of the other types really support Attachments.
I made it so we can extend our FrmFormActions to handle custom text but for now most of the plugins will read as `Conditional form actions` instead of `Conditional emails` which is still a nice step up. I already extended email so it still says Condtional emails :)
This update also extends `data-medium` a bit, someone could click through now on `conditional-zapier` and `conditional-aweber` rather than all being marked as `conditional-email`. I figured this was useful to distinguish.
Otherwise the aweber plugin does work well …
=> better action conditional logic call to action

composer.json
Same issue on free as in pro, dropping php52 support as it's legacy and no longer necessary for anything, and breaking Travis builds.
Causing multiple of my recent pull requests to fail, as well as the latest master merge.
I've already merged it into those broken branches so that they can pass testing.
=> drop php52

classes/controllers/FrmAddonsController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2667
The fallback's don't specify this value, but the prepare function figures it out and just never sets it.
=> php warning when using fallback plugins fix

classes/controllers/FrmAddonsController.php, classes/controllers/FrmAppController.php, classes/controllers/FrmEntriesController.php, classes/helpers/FrmAppHelper.php, classes/views/addons/list.php, classes/views/shared/views-info.php, css/frm_admin.css
The new upsell updates for views require some tweaks in the free plugin
- Adds views to the fallback plugin list
- Add a few helper functions to make it easier to access certain API details when just looking for a single thing
- The views upsell page now uses the same button logic as the addons list page (which is now moved into two different helper functions, one that manages the rendering and one that connects the addon to the rendering function without exposing the whole addon api)
- Do the same css adjustment for the messages warning that I did in an earlier update to add padding for errors
=> use conditional addon button on views upsell page

classes/helpers/FrmAppHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2721
Since `FrmAppHelper::renewal_message` covers any actual expirations, the expiration warning has no need to ever remind about anything negative.
It's possible this should also be fixed at a server level but I don't believe anything actually relies on this for functionality. It is just so we can show a message, so this should really be enough.
Or, maybe for consistency we want to do a similar approach to this:
```
if ( $days_left > 30 ) {
return false;
}
```
Change it to
```
if ( $days_left > 30 || $days_left < 0 ) {
return false;
}
```
But maybe it's nice to know the difference here.
=> only show expiring message if days is greater than 0

classes/models/fields/FrmFieldType.php, tests/fields/test_FrmFieldType.php
Fixes https://github.com/Strategy11/formidable-pro/issues/1913
I used a global variable as the validation seems to happen with different field object instances despite validating the same field, so storing the variables on the object didn't work. I made some unit tests to reflect that (that two different field objects for the same field still track duplicates between one another, and that another unrelated field object doesn't).
=> unique repeaters post check fix

phpcs.xml, tests/base/FrmAjaxUnitTest.php, tests/base/FrmUnitTest.php, tests/base/frm_factory.php, tests/bootstrap.php, tests/database/test_FrmMigrate.php, tests/emails/test_FrmEmail.php, tests/entries/test_FrmEntriesController.php, tests/entries/test_FrmEntry.php, tests/entries/test_FrmEntryValidate.php, tests/entries/test_FrmShowEntryShortcode.php, tests/entries/test_FrmTableHTMLGenerator.php, tests/fields/test_FrmField.php, tests/fields/test_FrmFieldType.php, tests/fields/test_FrmFieldValidate.php, tests/fields/test_FrmFieldsAjax.php, tests/fields/test_FrmFieldsHelper.php, tests/forms/test_FrmForm.php, tests/forms/test_FrmFormActionsController.php, tests/forms/test_FrmFormsController.php, tests/forms/test_FrmFormsControllerAjax.php, tests/misc/test_FrmAddon.php, tests/misc/test_FrmAppController.php, tests/misc/test_FrmAppHelper.php, tests/misc/test_FrmCSVExportHelper.php, tests/misc/test_FrmDirectFileAccess.php, tests/misc/test_FrmHooksController.php, tests/test_ajax.php, tests/test_wordpress_plugin_tests.php, tests/views/shortcodes/test_FrmFieldShortcodes.php
Removing the full exclusion for code styling in our free unit tests. I think all of the actual code styling should be enforced still. My IDE uses these files to show me warnings or not, and I like the consistency.
I left several of the rules that can't be fixed automatically or easily, that relate to security and naming convention rather than code cleanliness. It adds some bulk to the cs rules but it's easy to follow.
As this only effects code styling in unit tests and none of the actual packages code I feel confident that it won't break anything. I've ran the pro unit tests against this branch and they were a success so it shouldn't break anything in Travis.
Also added a rule for `Squiz.Scope.StaticThisUsage` on everything we're checking as it doesn't hurt to check for that. We had no …
=> add code styling rules to free unit tests

phpcs.xml, tests/fields/test_FrmFieldType.php
After a little extra phpcs QA in free, I found a few rules that we don't need, and I was able to isolate a few exclusions to just a few small files.
And I had to update a new unit test that was added after the unit test standardization.
Looks pretty good now.
=> clean up phpcs more on free

classes/helpers/FrmCSVExportHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2766
The issue here is that the metas aren't saved in the database, so I need to look at the repeater's fields and fill in the blanks as I populate the repeater data. There's really only one place that's possible to set it, in this repeater fill function after the loop. Added several unit tests, but they're in a [separate PR in pro](https://github.com/Strategy11/formidable-pro/pull/2773)
=> repeater export fix

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-views/issues/46
I made a PR at one point to put this back but it had other updates. Meant to make another one with just this, didn't. Missed that this is also triggered from the listing page.
There's really no need for this line. I put it in here trying to fix the disappearing view sections issue, but this wasn't the final fix.
=> do not disable the screen options checkboxes

tests/forms/test_FrmForm.php
Adds a unit test for https://github.com/Strategy11/formidable-pro/issues/2759
I don't actually think there's an issue in free after I've isolated this. But this function is where I started, and it deserves a unit test too.
=> add a unit test to confirm that calculations do not get stripped when sanitized

classes/helpers/FrmEntriesHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2780
I'm not sure if there's a better place for this. It seems the new form / edit form stuff come through fairly differently and I wasn't finding a better place where they share a function.
=> remove formidable button filter before loading a form

classes/controllers/FrmAppController.php, classes/helpers/FrmFormsHelper.php, classes/models/FrmFormTemplateApi.php, js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/2774
I was getting some pretty odd behaviour before also clearing the caches. I noticed that the cache key wasn't accounting for the free license either.
But the main thing is the new `updateTemplateModalFreeUrls` function that updates every free template, setting the urls that we can get. I dropped the break from the template loop and set everything to an array if it's free and has a url. Then I check that array for the specific key. Since we require these urls, there's a bit involved but nothing too crazy.
One thing though, in this new update, the license getting saved isn't base 64 encoded in the options anymore. This would mean that any previous option would no longer work. Is that fine? Do we want to revert that?
=> unlock all templates on free code verification

js/formidable_admin.js
Got the scope of this logic wrong.
I was seeing `valueSelect is undefined` which would happen in there were no rows. It shouldn't be accessing a variable that gets created in the loop from outside of the loop.
This doesn't seem to be breaking JavaScript but it still logs an error to the console and it's likely missing rows where it is.
=> prepend option to select inside loop fix

css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/2814
I listened to the TODO comment and removed the `.branch` prefixes that were avoiding the new `branch-5-6`
This will possibly mean some funny padding in WordPress < 5.3 but I imagine we're okay with that.
=> fix select padding issue in WordPress 5.6

js/formidable_admin.js
This PR should do the trick to fix the JS error reported by @altoin 
https://sandbox.formidableforms.com/toyin/wp-admin/admin.php?page=formidable&frm_action=edit&id=936
=> Add condition to avoid js warnings for a null property

classes/helpers/FrmCSVExportHelper.php
Fixes 3 errors I was seeing in my pro unit tests on PHP 7.4:
1) test_FrmCSVExportHelper::test_prepare_csv_row
Trying to access array offset on value of type bool
/tmp/wordpress/src/wp-content/plugins/formidable/classes/helpers/FrmCSVExportHelper.php:508
2) test_FrmCSVExportHelper::test_prepare_csv_row_empty_fields_in_repeaters
Trying to access array offset on value of type bool
/tmp/wordpress/src/wp-content/plugins/formidable/classes/helpers/FrmCSVExportHelper.php:508
3) test_FrmCSVExportHelper::test_add_repeat_field_values_to_csv
Creating default object from empty value
/tmp/wordpress/src/wp-content/plugins/formidable/classes/helpers/FrmCSVExportHelper.php:300
=> fix php deprecation errors in csv export

css/custom_theme.css.php
This is a required part of the fix for https://github.com/Strategy11/formidable-pro/pull/2845
Without this, the autofilled field can't match the css check.
=> add inline box shadow to autofill input

js/formidable_admin.js
Fixes a vulnerability Steph mentions in https://github.com/Strategy11/formidable-pro/issues/2827#issuecomment-762478526
This can be exploited when someone creates an anchor tag that matches our expected attribute.
Also fixes https://github.com/Strategy11/formidable-pro/issues/2846
=> Avoid XSS from data-verify / data-caution attributes

js/bootstrap-multiselect.js, js/formidable.js, js/formidable_admin.js
We had a support ticket come in asking about some left behind shorthand warnings from jQuery migrate. I don't think these would ever actually be removed from jQuery, but we might as well change everything to drop the deprecation warnings.
Similar to some of the earlier deprecation updates made in https://github.com/Strategy11/formidable-forms/pull/315
=> remove jquery blur and focus shorthand

js/formidable_admin.js
This fixes the issue with the free templates form flagging emails as invalid.
=> do not fill frm_verify field when autofilling for free templates

classes/controllers/FrmAppController.php, tests/misc/test_FrmAppController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2865
I don't really think there's anything you can actually test for with this function. It doesn't return anything. But having the test here catches any errors, so I just bumped the assertion count.
I see that `network_upgrade_site` is called from 3 different places, and it's not very clear which one is the issue here.
I see some of the calls wrapped in conditions like `if ( ! FrmAppHelper::doing_ajax() && self::needs_update() ) {`. Maybe we need to put more of these conditions into the function itself?
=> Maybe add wp site health before calling rest_do_request

js/formidable.js, js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/2881
It looks like the newer jQuery in the latest versions of WordPress was breaking some of our checkbox logic here.
I found two new deprecation warnings I wasn't aware of (the same warning, but two types of attributes):
```
jQuery.fn.removeAttr no longer sets boolean properties: checked
jQuery.fn.removeAttr no longer sets boolean properties: disabled
```
=> use prop when removing disabled and checked attributes

js/formidable_admin.js
Nat just caught a bug from a recent update here - https://github.com/Strategy11/formidable-pro/issues/2878#issuecomment-779339042
The modal wasn't clearing, so the pop up could include old messages as well in it.
Best to slip this fix into the release as well 🚀
=> clean confirm message before appending text fix

classes/models/FrmInbox.php, tests/misc/test_FrmInbox.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2873
I didn't realize we were initially given much of the original error from the ticket.
It's cut off, but the first error is `Illegal string offset 'key'`.
Which points out the obvious issue that `$message` was coming through as a string, not an array at all.
We already cleaned up after the fact, but this prevents the issue from happening in the first place.
=> check if message is array before adding it fix

classes/views/frm-fields/single-option.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2878
I mention in my comment there more about the conflict.
This field needs a unique id. Adding `-label` makes sense to me, as the input targets the label, but maybe that's misleading, since it's not actually a label either.
I don't believe this id for the input label is actually used anywhere in particular. If it was relying on id before, it likely wouldn't have worked since it wasn't unique anyway.
=> add -label to single option label input id in order to make it unique

.github/workflows/phpunit.yml, js/formidable_admin.js
Noticed another jQuery deprecation warning coming from formidable.
`jQuery.fn.keyup() event shorthand is deprecated`
Also, using `ubuntu-latest` has finally caught up with formidable lite as well and no longer works for several versions of PHP we're testing so I'm forcing ubuntu 16.04 for now because it works with all of our tests.
=> change deprecated jquery keyup trigger event

classes/helpers/FrmAppHelper.php, tests/misc/test_FrmAppHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2855 and I believe it fixes https://github.com/Strategy11/formidable-pro/issues/2741 as well.
You can't duplicate a field if the key is over 100 characters because we have a size limit in our database. If the key is over 100 characters in length, I treat it like it's empty and generate a new one from scratch.
I check specifically for the `$field_key` column value as I realize this might not be limited to 100 for other columns.
The other update is just to remove a phpcs warning.
=> generate a new field key if the length is over 100

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/2907
I usually just check for changed fields, but that doesn't work to detect new or deleted actions.
I also noticed in my testing that the same issue applied to creating the action (add an action, leave the page, no warning).
=> Confirm before leaving a page with unsaved changes when a form action is added or removed

css/frm_admin.css
I noticed this was weird for a while, but never really knew when the issue was introduced.
The issue with the `:last-child` selector is because I introduced a hidden `optionmap` input on text focus in v4.08 (https://github.com/Strategy11/formidable-forms/commit/a35ac7848d9d6ee47c1c41efa8e19d52ae27abdc) for updating radio option conditional logic. This seems to somewhat apply to products as well, although I also noticed this small issue - https://github.com/Strategy11/formidable-pro/issues/2909
**Before**
**After**
=> fix product price input width

changelog.txt, readme.txt
WordPress 5.7 came out yesterday, which is tested against, but I missed that the style editor's update button was missing as a result of the new WordPress version.
That fix is here - https://github.com/Strategy11/formidable-forms/pull/361
I also intend to include this unmerged fix which would be nice to have in as soon as possible - https://github.com/Strategy11/formidable-forms/pull/359
I believe doing a release a week early makes sense. There are quite a few tickets coming through today about this.
=> add changelog for 4.09.08

css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/2914
It looks like WordPress 5.7 adds a new css rule in `wp-admin/css/nav-menus.css`:
```
#save_menu_header {
display: none;
}
```
Our update button on the views page has this id so it disappeared.
I'm just applying a style on top to undo this on our button.
=> make sure the style editor update button is not hidden (css fix)

classes/controllers/FrmFieldsController.php, classes/helpers/FrmFieldsHelper.php, tests/fields/test_FrmFieldsController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2916
To replicate, add a number field, set 0 as the placeholder (not the default value, the placeholder).
When you preview the form, the 0 does not appear without this fix.
=> allow 0 as a placeholder value

classes/controllers/FrmFormsController.php, classes/helpers/FrmEntriesHelper.php
I noticed something in my error log when I tried to preview a form with no fields.
```
PHP Warning:  Undefined array key "custom_style" in /var/www/src/wp-content/plugins/formidable/classes/controllers/FrmFormsController.php on line 1946
```
I also refactored some other custom style code to make this more consistent across formidable. There was already a helper function in `FrmAppHelper` that had this same logic in it.
=> undefined key custom style when there are no fields fix

classes/views/frm-forms/list-template.php, classes/views/frm-forms/list-templates.php, js/formidable_admin.js
I noticed in the new view modal that clicking the icons was not triggering the new form events because they were missing the `role="button"` code. Same applies to the new form modal, so I'm making an update here too.
I'm also auto-focusing the template name input if you're creating one with an empty name because I think there should be one. I've tried to type a name a few times and had to focus first. Just makes it easier.
And I'm changing a couple of label updates to use `textContent` since they come from data attributes and this could ultimately be manipulated a bit (though that would take a lot of hoops to jump through).
=> Make icons clickable in new form modal

changelog.txt, readme.txt
I plan to do a release tomorrow. I have everything in the free plugin already merged that I intend to include in this release.
Since there is a migration in pro, I'm bumping up to a new `4.10` version.
=> update readme for 4.10

js/formidable_admin.js
I was trying to push the editor to its limits to see if anything would break, and something did 😱
It turns out, that if you drag the same type of field really fast (which can happen from just barely dragging it as well, if you were clicking and moving around your mouse a lot like I was), it will break when it replaces the temporary loading spinner because the two fields that are being dragged have the same id. The value of `loadingID` is just the field type: "select", or "text", etc.
```
Uncaught TypeError: field is null
    afterAddField http://localhost:8889/wp-content/plugins/formidable/js/formidable_admin.js?ver=4.10:1259
    success http://localhost:8889/wp-content/plugins/formidable/js/formidable_admin.js?ver=4.10:1034
    jQuery 4
```
To fix this, I'm adding a function that just …
=> use unique ids when dragging a field to avoid replacement conflicts

classes/helpers/FrmFieldsHelper.php, js/formidable_admin.js
Another thing I noticed when trying to push the form editor, is that you can actually trigger the upgrade modals for fields that are not locked, by clicking in the corners where the `[data-upgrade]` listener is happening, where the inner `.frm_add_field` is not touching because of its border radius.
To fix this, I'm checking the value of `show_upgrade` now, and actually avoiding some of the upgrade message logic and page HTML, hopefully improving performance a bit in the process for people who are on pro.
And I also refactored the JavaScript a bit, moving any variable declarations to the top of the function. And aligned some spaces in PHP.
=> do not display upgrade modal if option is not disabled

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/2952
The issue actually begins as soon as you open the "Add Layout Classes" pop up. It removes the `ui-state-default` class, which is necessary for the event listener to register the click event.
The issue comes down to the line above the fix `classes = field.className.split( ' frmstart ' )[1].split( ' frmend ' )[0];`.
`.split( ' frmend ' )` is not finding our class because there is no leading space before our `frmend` class.
I do an additional check, for if the string begins with `'frmend '`, and set it to an empty string if it is. This is the effectively equivalent of checking at [0] after the implode, for this specific case.
=> do not remove ui-state-default from field when layout options open

js/formidable_admin.js
This isn't really anything crazy. I just noticed this `var link` was totally unused in this function. My syntax highlighter has it in another color, so it stands out a bit.
Doesn't hurt to clean up 🙂.
=> remove unused var link in doaction listener

classes/helpers/FrmListHelper.php
Fixes Strategy11/formidable-pro#2963
I don't think we can safely pass a nonce referer if we're passing the nonce through a $_GET request because the url will grow until it eventually hits a limit.
So I just don't pass it. It looks like we're not really checking for it, so everything still seems to work, just with a smaller URL.
=> Do not pass the nonce referer for bulk actions

classes/controllers/FrmSettingsController.php, classes/helpers/FrmAppHelper.php, classes/helpers/FrmXMLHelper.php, js/formidable_admin.js
This PR is prepared for this issue: https://github.com/Strategy11/formidable-pro/issues/61
What I did in this PR:
- Add `post_type` and `autocomplete_placeholder` to the arguments array of FrmAppHelper::maybe_autocomplete_pages_options() method
- Add container as second param to initAutocomplete() JS function
- Add JS code to dynamic load the post parent option in pro version
There are 3 main things needed to test here:
- Test if it does not break the current page select or autocomplete options
- Test if `post_type` and `autocomplete_placeholder` work as expected. Example code to test:
```
FrmAppHelper::maybe_autocomplete_pages_options(
array(
'field_name'  => 'options[success_page_id]',
'page_id'     => isset( $values['success_page_id'] ) ? $values['success_page_id'] : '',
'placeholder' …
```
=> Preparation for issue 61 of pro version

classes/controllers/FrmFormsController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/1880
I tried this out with Customizr only as the other plugins all seem to be paid ones that I don't have access to.
When there is no support a template part `get_template_part` actually returns `false`, so we can try calling a fallback method for rendering our form.
I skimmed over the customizr code quite a bit, and I think the right option is to just call `the_content()` to trigger the render event. I also added `get_header()` and `get_footer()` calls as well, to make it a little more page-like. But it still feels pretty ugly with Customizr.
Since this fix is so generic and simple, I think it should really work with every conflicting plugin.
Instead of nothing, I get a pretty plain, not-very-styled form, but it's better than …
=> add a fallback for the_content if get_template_part does not support page

changelog.txt, readme.txt
It also looks like there is a version 5.7.1 of WordPress now. I just updated to test it out, and everything seems good, so I bumped that.
It might have to do with our rank changing. I didn't catch that there was a new WordPress version.
=> update readme for 4.10.02

classes/helpers/FrmStylesHelper.php
I'm playing around with the style editor and caught this undefined variable warning every time it tries to preview the theme.
```
[30-Apr-2021 01:08:20 UTC] PHP Warning:  Undefined variable $repeat_icon in /var/www/src/wp-content/plugins/formidable/css/_single_theme.css.php on line 43
[30-Apr-2021 01:08:20 UTC] PHP Warning:  Undefined variable $repeat_icon in /var/www/src/wp-content/plugins/formidable/css/_single_theme.css.php on line 47
```
It looks like it doesn't effect functionality as it's just a warning.
=> Undefined variable repeat icon fix

js/formidable_admin.js
I noticed a bug the other day when my AJAX request to create an action took a moment, and I clicked it again.
It ended up creating two action elements with the same `actionId` value. Then causes some weird behaviours, like when I go to delete the bottom action, it actually goes and deletes the top one instead.
I'm adding an extra tracked variable here that makes sure that the value returned is always higher than the value previously returned.
I also refactored the js slightly so that the variables are all in one declaration in the addFormAction function.
=> Guarantee unique action id

classes/models/FrmEntry.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3013
These issues always mention the hook not working, but it's really just that the duplicate checks don't catch certain field types, so this is really just "duplicate checks don't work for date fields".
I missed that there are really two functions here.
`get_value_to_save` which I added in the last duplicate check, which caught signatures and some other fields.
But there is also a `set_value_before_save` that effects dates, numbers, times, credit cards.
I'm calling the new one afterward as it's meant for processing at the very end and the other function is intended for earlier in the processing.
=> Also call set_value_before_save for duplicate check

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-views/issues/116 by resetting the fieldsUpdated flag when the update button is clicked.
This was something I missed when I did https://github.com/Strategy11/formidable-forms/pull/357 as I didn't catch that the fade out logic was happening for multiple types of elements on various pages, not just actions on the settings page.
This page still doesn't really support the unsaved changes pop ups, but it might not be worth it since we're replacing this soon.
=> mark fields updated to 0 on publish button click

bin/zip-plugin.sh
Excluding the unminified JavaScript from views here. And also the composer.lock file, which I guess I committed into views when I did the separation.
I'm not sure how important that even is, but the exception is good to have here since we're doing the same for the other `composer.json` file.
=> Add more exceptions to zip plugin file

classes/views/frm-forms/form.php, js/formidable_admin.js
I'm starting to get into the side-by-side form editor requirements here, and I'm noticing some funny things with the current ways that the editor is adding stuff.
The replace here is not working when there are no classes because it looks like this double space check is being trimmed now.
I check first if the previous string exists, and if it doesn't, I do my replace instead to fix this issue.
There was that other layout class error happening here that I think probably broke for the same reason.
=> Fix class name replace issue for fields without classes already set

classes/views/frm-forms/spam-settings/honeypot.php
Fixes the issue Guga posted [here](https://strategy11.slack.com/archives/CJFQ599V5/p1621876733054200).
The honeypot option was working fine but the basic option would appear as selected if it was off. And then a subsequent save would likely turn it back on as a result.
My logic for the basic option was too much of a catch-all.
I don't think any of it the extra logic I had is really necessary now. The default is basic.
=> honeypot setting appears basic when off fix

css/frm_admin.css
The list that WPML adds to our views page looks off from everything else.
It's bothered me for a while as I've worked on views with WPML also on.
I'm just adding it to the same class definition that we use for the list above it (that toggles between All/Private) so it aligns consistently.
Before:
After:
=> add margin to wpml sub list

classes/models/FrmEntry.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3037
Using a filter like:
```
add_filter(
'frm_duplicate_check_val',
function( $check_val ) {
unset( $check_val['ip'] );
return $check_val;
}
);
```
or
```
add_filter(
'frm_duplicate_check_val',
function( $check_val ) {
if ( 9 == $check_val['form_id'] ) { 
unset( $check_val['ip'] );
}
return $check_val;
}
);
```
I'm not sure if we just want to take out IP by default so I'm leaving it for now.
Making it filterable makes this more customizable, and future-proof, and doesn't break anything in the process.
=> Make duplicate check val filterable

classes/views/shared/mb_adv_info.php
Playing with scanning our PHP code and caught this.
It's specifying a text domain but calling esc_attr which doesn't support that.
=> esc attr fix in mb adv info view

classes/controllers/FrmFormsController.php
```
ERROR: UndefinedVariable - classes/controllers/FrmFormsController.php:976:31 - Cannot find referenced variable $last_order (see https://psalm.dev/024)
unset( $end_section_values, $last_order, $open, $reset_fields );
ERROR: UndefinedVariable - classes/controllers/FrmFormsController.php:976:44 - Cannot find referenced variable $open (see https://psalm.dev/024)
unset( $end_section_values, $last_order, $open, $reset_fields );
ERROR: UndefinedVariable - classes/controllers/FrmFormsController.php:976:10 - Cannot find referenced variable $end_section_values (see https://psalm.dev/024)
unset( $end_section_values, $last_order, $open, $reset_fields );
```
Caught when running psalm.
Really not an issue since unsetting an undefined variable does nothing, but there's no reason to have this code …
=> remove undefined variables from unset in FrmFormsController.php

classes/models/FrmEntry.php
Caught with psalm.
```
ERROR: UndefinedVariable - classes/models/FrmEntry.php:408:18 - Cannot find referenced variable $entry_metas (see https://psalm.dev/024)
if ( ! isset( $entry_metas[ $meta_val->field_id ] ) ) {
```
I tried testing around this and couldn't see anything breaking as a result.
Since `entry_metas` should never be set it's possible there's a bug here that was overwriting the value of `$entry->metas[ $meta_val->field_id ]`.
=> undefined variable entry metas fix

classes/models/FrmAddon.php
Caught this with psalm.
```
ERROR: UndefinedVariable - classes/models/FrmAddon.php:363:21 - Cannot find referenced variable $addons (see https://psalm.dev/024)
} elseif ( isset( $addons['error'] ) ) {
```
This means that `is_expired_addon` was never really being flagged.
This might explain a lot of the weird license messages that people report.
=> addons typo when getting api info fix

classes/models/FrmStyle.php, css/_single_theme.css.php, css/custom_theme.css.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2944 alongside https://github.com/Strategy11/formidable-pro/pull/2964
I played with the preview stuff in the editor, which seems to require single_theme. I'm a little confused by the differences between the single and custom theme files. I don't want to add too much, so I left out the changes I had in single_theme. The preview doesn't update in real time, but it does work after save, which seems to be consistent with some of the things in the style editor and not others.
=> add repeat icon color to style settings

css/frm_admin.css
The "new" ribbon was hidden on the add-ons page.
After:
=> Fix ribbon position for new add-ons

classes/views/frm-fields/back-end/field-options.php
I was playing with lookup radio fields, saw this error. It was causing some stuff not to load in the back end of the form editor.
Without this I never see the submit button in the form editor's preview.
And it logs this huge error statement.
```
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, string given in /var/www/src/wp-content/plugins/formidable/classes/views/frm-fields/back-end/field-options.php:14
Stack trace:
#0 /var/www/src/wp-content/plugins/formidable/classes/models/fields/FrmFieldType.php(397): include()
#1 /var/www/src/wp-content/plugins/formidable/classes/views/frm-fields/back-end/field-choices.php(13): FrmFieldType->show_field_options(Array)
#2 /var/www/src/wp-content/plugins/formidable/classes/models/fields/FrmFieldType.php …
```
=> check that field options is an array before checking count

classes/controllers/FrmStylesController.php
I was seeing a bug with my css trying to load at a path missing a slash in it (http://example.org/wp-content/plugins/formidableimages/ajax_loader.gif)
Looks like we missed a slash with https://github.com/Strategy11/formidable-forms/pull/393
I think this is fine. Just running this by you @truongwp.
=> use trailingslash it to avoid formidableimages path issue

classes/controllers/FrmInboxController.php, classes/models/FrmSettings.php, classes/views/frm-settings/general.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3034
Do we want to change the wording? The double negative is a little funny.
And do we want to mention more about why we're doing this? Mention internet explorer? Should we refer to the upcoming WordPress deprecation?
=> Deprecate the old grid css setting

js/formidable_admin.js
Testing the new menu_order setting, I feel like it has to be dynamic like the post_parent options.
I refactored the post_parent logic as well since these both use almost entirely the same logic.
I wonder if we might want to use one action instead, but that might be weird with backward compatibility and having this in free and pro.
Also requires the AJAX action logic in the pro plugin [here](https://github.com/Strategy11/formidable-pro/pull/3089).
=> Make an ajax request for menu order field

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/2214
Pretty simple one. There was logic to hide it, and no logic to put it back again.
=> Put back the watch lookup option when switching away from single line text

classes/models/FrmEmail.php, tests/emails/test_FrmEmail.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2823
Quite simple. It was checking if the reply to was empty and then using the from name. But it wasn't check if the processed result was empty. So I flipped the logic a bit. First, we check if it's set, process it. Then if it's empty (which could have been true before, but it also matters if it is empty after), we use the from name.
=> Use email from from value when reply to value is a shortcode that returns empty

css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/2959
Here's what it looks like now:
=> fix autocomplete styling

js/formidable.js
I did some research on this topic. There's more we could probably do to make this even more accessible but I think this is a good start.
Fixes https://github.com/Strategy11/formidable-pro/issues/2897
I found some information on the issue at https://www.w3schools.com/accessibility/accessibility_errors.php
There's a section that reads:
> Move focus
> This is more important for server-side validations, compared to client-side validation. When the user submits a form, the focus moves to the first invalid field.
> In this example, all three fields have been invalid. The focus was moved to the first field.
So this checks out as a good best practice and it does make a form field easier to use when you mess it up, even if you're not blind 🥳.
I checked all of the many ways that errors are added …
=> Automatically focus on the first error input

tests/emails/test_FrmEmail.php
Fixes an annoying error coming up in pro unit tests causing them to fail now since I added this unit test.
```
1) test_FrmProEmail::test_set_reply_to
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'fromemail@example.com'
+'[free-email-field] <admin@example.org>'
```
The pro unit test inherits the free tests, so all of those run as well. But this time using a different `email_form_key` value, which means my field key has to change as well.
_(`[free-email-field]` is not processing in pro because the field doesn't exist)_
=> Update reply to unit test to avoid issues with pro unit tests breaking

css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/2276
I tested using "Nieuwe toevoegen" for the "Add New" button (Dutch), it looks like this was improved earlier and doesn't look so bad.
But the Aktualisieren (Update) and Vorschau (Preview) example (German) was still an issue. Now it looks like:
And I tested it in Dutch as well
I tried using the rest of the site in plugin in Dutch for a moment and nothing else really seemed off 🕺.
=> Allow for larger save/preview form button labels before wrapping

classes/helpers/FrmAppHelper.php
This prevents integers from being switched to a string when content is encoded for a json post
=> Prevent integers from being switched to a string

css/frm_admin.css
Continuing from https://github.com/Strategy11/formidable-forms/pull/469
I neglected how much additional space the button takes up once you click it in Dutch and the text changes to "Opties bijwerken" after it is clicked.
Just giving it a bit more max-width. 300 wasn't enough.
=> bump frm publishing max width a little more

js/formidable_admin.js
I came across this weird styling testing the side-by-side fields. Changing it so it displays as block instead of inline is really as we need to do here.
**Before**
**After**
I looked for other references to `data-frmcaution` and it looks like this "Heads up" it all it's ever used for at the moment.
=> Use a div for heads up caution in confirmModal

classes/helpers/FrmAppHelper.php, classes/helpers/FrmEntriesHelper.php, classes/helpers/FrmFormsHelper.php, classes/models/FrmEntry.php
I want to get psalm running as a workflow soon, but there are some errors still to fix before that.
This fixes 5/7 of the errors I'm seeing under my current configuration, mostly paradoxical code.
There's really no reason why you would ever check `if ( ! $var || empty( $var ) )` since the the second condition would never be true if the first is not.
```
ERROR: ParadoxicalCondition - classes/helpers/FrmFormsHelper.php:754:21 - Found a paradox when evaluating $submit of type non-empty-mixed and trying to reconcile it with a empty assertion (see https://psalm.dev/089)
if ( ! $submit || empty( $submit ) ) {
ERROR: InvalidParamDefault - classes/helpers/FrmFormsHelper.php:78:12 - Default value type false for argument 1 of method FrmFormsHelper::form_switcher does not match the given type …
```
=> Clean up paradoxical psalm errors

classes/controllers/FrmHooksController.php, classes/models/FrmPluginSearch.php, js/plugin-search.js
This helps people find our add-ons easier.
I'm updating the API end to include more search terms. Right now, the name of the add-on has to be exact in order to show up. For example "paypal standard" brings up our add-on and "paypal" doesn't. This part isn't included in the code here.
=> Include addons in wp search

css/custom_theme.css.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3116
Issue with the update to set custom repeater icon colors. It was applying to all of the repeated fields, not just the add/remove buttons.
I'm making this more specific. But for the style editor preview to work, I also need to add this target class to the sample form with https://github.com/Strategy11/formidable-pro/pull/3117
=> Make the style more specific to avoid other repeated field icons

.github/workflows/phpunit.yml, classes/models/FrmForm.php, tests/forms/test_FrmForm.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2977
I'm just normalizing the expression a bit before it goes through the other sanitizing that was already there.
`5<10`, `5<=10`, get stripped. `5 < 10`, `5 <= 10` don't. Making sure that the spaces are always there before the sanitizing happens prevents the final value getting saved as just a `5`.
To avoid the preg_replace when it would have no effect, I've also added a small strpos check first so it only processes if it sees any `<` characters.
I also moved the calc sanitizing to its own function, and added unit tests to cover a lot similar patterns.
It looks like workflows are also breaking because of the ubuntu version. I tried playing with that briefly but it looks like there are other issues too. I think a new version of …
=> Add padding to calculations before sanitizing happens

classes/controllers/FrmAddonsController.php, css/font_icons.css, js/formidable_admin_global.js
This adds a background color on the upgrade menu in lite:
=> Highlight the upgrade menu

.github/workflows/phpunit.yml
I think this is a fix for what I'm experiencing, from 8 hours ago https://core.trac.wordpress.org/changeset/51598
An update in WP master appears to have broken our workflow, assuming that composer is running update.
For now I'm just targeting WP 5.8. Should be fine changing back to master shortly.
=> Bump up ubuntu, target WP 5.8 for now.

changelog.txt, readme.txt
Question - How should I mention in the changelog that the required WordPress version has been bumped up to 5.0?
I'm also not sure if we want to mention the updates to the search? If we do, what should I put?
=> Update readme for 5.0

classes/helpers/FrmAppHelper.php, tests/misc/test_FrmAppHelper.php
I'm not totally sure what willed me to test this but duplicating long form keys totally breaks, similar to the long field key duplicating issue I fixed a while ago.
This double checks that a key is long before making it longer, if we're extending a key that was reserved in the database.
=> Fix issue with duplicating long form keys

tests/misc/test_FrmAppController.php
I made a release and it didn't go live because of this failing unit test that seemed to happen when I bumped the version.
It looks like it has specific tests for going up to the next major version? It seems that it breaks now that we're at 5.0.
This update makes it pass. I'm targeting the 6.0 major version now instead, which I think is what needs to be done here? I set the 5.0 test to use the current db version. I think that's what that's intended for?
=> Fix compare for update unit test

classes/views/frm-forms/add_field.php, css/frm_admin.css, js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3132
I moved the dropdown options for fields out of the HTML/PHP for each field, which should help to optimize long forms by removing tons of HTML on load 🥳.
For now these just use the individual field hooks. In the future I'd love to make this a little optimized but this is much less error prone as it is.
=> Add duplicate/delete options to field groups

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3142 at least for most keys.
I wanted to give this a go. It isn't too tricky to check both sets of inputs for inconsistencies.
Right now there are likely some keys that don't copy over because I'm intentionally using an allowlist to avoid some surprises or unexpected behaviour issuess. Right now the things that copy even if the changes in the original field were unsaved are:
- Name
- Required
- Unique
- Read only
- Default value
- Placeholder
- Description
- Size
- Max
- Format
- Before/after
- Separate values
- Options for radio/checkbox/dropdown fields
Works when duplicating fields individually or when duplicating groups. It looks like there might still be some gaps with duplicating sections though.
=> Duplicate some unsaved field keys

classes/views/frm-settings/recaptcha.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3162
I feel like there isn't a lot of reason to have a placeholder on these at all so I'm just removing them. I agree the placeholder we have is just doing more harm than good.
Easy peasy
**Before**
**After**
=> Remove captcha settings placeholders

classes/views/frm-fields/back-end/number-range.php, js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3153
Also requires https://github.com/Strategy11/formidable-pro/pull/3160 for some of the fix.
Applies to the next button for page break fields and slider labels, and the add/remove labels for repeater fields in the other pull request.
=> Update previews for next button and slider labels

css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/3169
=> Fix search filter is cut if half in Entries page when no results #3169

js/formidable_admin.js
Working toward a solution for https://github.com/Strategy11/formidable-pro/issues/3154
For now I'm not calling this a fix. It looks like there are other issues with the repeater form caching the fields so they appear in two places.
But I think this is important to include in this release, just so section ids don't get messed up anymore than they need to.
This currently calls the action once per field in the group that is being moved and would benefit to get optimized in the future.
=> Update section ids when moving a field group

classes/helpers/FrmTipsHelper.php, classes/views/frm-forms/settings-advanced.php, css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/3150
I bumped the old tooltip up into the other section, at the bottom, then added a new one that is more in-position and targeted with a placeholder checkbox.
**Before**
**After**
Adding a couple generic classes because I keep wanting an easier way to set some basic styles like tachyons/tailwind. Adding just a few, that I've wanted pretty often.
=> Add a grayed out submit with AJAX option with tooltip

classes/controllers/FrmFieldsController.php, classes/controllers/FrmFormsController.php, js/formidable.js, tests/fields/test_FrmFieldsController.php
Related to https://github.com/Strategy11/formidable-pro/issues/2360 and includes part of a fix for that as well.
Also see https://github.com/Strategy11/formidable-pro/pull/3177 for a related fix (submit with AJAX).
I noticed while working on that issue that we have all of these gaps as well with our JavaScript validation, which I got confused with this at first since it's the same set of issues.
I tried to make it as performant as possible by storing the form object as a variable when we initially check for the js validation in the global var, by only checking if there are required/invalid errors embedded in the HTML, and by ignoring the default HTML so only custom HTML is added to the form.
This update adds support for custom HTML from the "Customize HTML" part of settings but also via …
=> Allow custom HTML for error messages when validate with JavaScript is on

classes/models/FrmInbox.php
I was testing messages and noticed that there's data coming from the API but I never see the message.
It looks like the who value I'm seeing is an array with an everyone option:
```
[who] => Array
(
[0] => everyone
)
```
I'm adding to the check so that passes. It seems to expect an 'all' message instead, but this must have changed at some point.
With this update I actually see the new message.
=> Fix inbox visibility assignment issue

classes/controllers/FrmAddonsController.php, css/frm_admin.css, js/formidable_admin.js
https://recordit.co/5zjic0q2aC
Setting up the landing page plugin, I find the flow really jarring that I have to activate it and then close the pop up and save myself.
I've added a check, if we're activating a plugin from the settings page, I've added an option to trigger the save button from the pop up.
This update also removed some duplicate strings and moves some var declarations to the top of the function.
We should probably do this on other pages too but settings seems to cover most of these.
=> Add save and reload to settings page after plugin activation

js/formidable_admin.js
Testing things, noticed a little side effect of the side-by-side fields update.
Preventing adding a summary field to a field group. Once it auto-inserts the page break and stuff it comes out pretty funny.
=> Prevent dragging a summary field into a field group

js/formidable_admin.js
Caught a small issue with my new update. If there were changes it was actually showing the warning still. Looks like the fieldsUpdated value doesn't get flagged here automatically.
=> Set fields updated to 0 on save and reload

classes/controllers/FrmAppController.php, classes/models/FrmInbox.php, classes/views/frm-forms/list.php, classes/views/inbox/banner.php, classes/views/shared/admin-header.php, css/frm_admin.css, js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3022
The Inbox API can now pass along two new keys, emoji and banner.
For now any testing has to be done with fake data.
I was injecting into the current active message with:
```
$message['emoji']  = '🕺';
$message['banner'] = 'Multi-column forms are easier to create with the all-new form layout tool';
```
=> New inbox banners

js/formidable_admin.js
Think this fixes the issue behind https://github.com/Strategy11/formidable-pro/issues/3157
It seems moving a repeater can cause it to assign itself as a section. This update just makes sure that a section never returns itself when trying to determine what section a field is in.
Leaving that issue open for now as this doesn't really fix the issues automatically. I think we could use some extra checks to make sure nothing ever tries to embed into itself.
=> Do not return section for section field

css/frm_admin.css
If I set my padding to 150px for example:
**Before**
**After**
I added a little more top padding than the default. It looks nicer I think spaced from the "Add new entry" header a bit. It used to look more like:
=> Overwrite fieldset padding on admin

classes/controllers/FrmFieldsController.php, js/formidable.js
https://secure.helpscout.net/conversation/1634066257/81156/
And now also https://secure.helpscout.net/conversation/1636090425/81257?folderId=2445391
And looks like a third time now as well https://secure.helpscout.net/conversation/1636180030/81261?folderId=2445391
Looks like my custom error html update had a funny side effect I wasn't expecting.
`getFieldValidationMessage` is actually called in one place to get the pattern. It's not always a "validation message" as the function might lead you to think.
So the custom error html (which wasn't actually custom, it turns out that the error html sometimes doesn't include an id and I wasn't checking for that), was applying over the pattern so the pattern would break.
I also updated the default check so it would include these missing id cases …
=> Do not wrap html around validation pattern

classes/views/frm-forms/add_field.php, css/frm_admin.css, js/formidable_admin.js
Trying to make field dropdowns more accessible
**Related to** 
https://github.com/Strategy11/formidable-pro/issues/3172
https://github.com/Strategy11/formidable-pro/issues/3207
I can use the keyboard to delete and duplicate fields now when following VoiceOver instructions.
Tried a few things to make this nicer (giving the list an aria-label, setting a default aria-expanded=false, changing the li elements to use anchor which focus better).
=> More accessible field dropdowns

classes/helpers/FrmCSVExportHelper.php
https://secure.helpscout.net/conversation/1633894310/81145?folderId=4324209
**Separate values _label columns were not exporting properly when inside of a repeater.**
It looks like this was missed when I did the repeater csv export.
Pretty simple fix. The labels are all together as a CSV, just have to be exploded.
**Before**
**After**
=> Explode sep value labels for repeated fields

classes/controllers/FrmFieldsController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3207, at least how it should. We use `aria-required`, not `required` but this covers the issue.
@stephywells any idea why radio and checkbox were ever excluded here? Was it just an oversight or something?
It removed them from this exception and they work well with the `aria-required` attributes added.
=> Add aria required to required radio and checkbox fields

classes/controllers/FrmElementorController.php, classes/controllers/FrmHooksController.php
https://secure.helpscout.net/conversation/1637476380/81364/
Fixes https://github.com/Strategy11/formidable-pro/issues/3223
Moving the logic now into a new Elementor controller since this is the second time I've wanted to put hooks for Elementor somewhere and didn't have a great place for it. I didn't want to add another function to the Hooks controller. I've deprecated the other one I had added.
The pop up would just appear blank before because the required JavaScript and HTML were not being added to the page.
https://recordit.co/O9GK1pNHvz
@garretlaxton to test this, I'd like to see if this pop up has any other issues on this Elementor page that I didn't catch.
=> Add insert form popup on elementor admin

classes/models/fields/FrmFieldCombo.php
After updating the `aria-required` attributes for radios/checkboxes (https://github.com/Strategy11/formidable-forms/pull/531) I thought I'd check our other fields.
Some of the new fields have missing attributes. It looks like they're missing this call to the `frm_field_input_html` action which is pretty important.
It makes it more extendable, adds support for the `frm_field_classes` filter, adds `aria-invalid` when JavaScript validation is turned on, adds the missing `aria-required` attribute, adds the JavaScript validation messages that are missing.
@truongwp do you see any issues with this update? Do you think anything could go wrong here?
**Before**
**After**
**Before (JavaScript validation on in error state)**
**After (JavaScript validation on in error state)**
=> Make name fields more accessible

css/frm_blocks.css
Fixes https://github.com/Strategy11/formidable-pro/issues/3190
The rule above this new rule:
```
.frm-block-intro-content svg {
margin-top: 32px;
margin-bottom: 12px;
}
```
Is causing issues. I'm undoing that and it seems to do the trick.
=> Unset margin on block select caret svg

classes/controllers/FrmFormActionsController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3228
Super easy, the api data already includes a categories array that includes "Business" and "Elite" so the package can be really easily determined already 🚀.
=> Add data-requires to actions with Business/Elite in the category list

.github/workflows/phpunit.yml, composer.json, tests/base/FrmAjaxUnitTest.php, tests/base/FrmUnitTest.php, tests/emails/test_FrmEmail.php, tests/fields/test_FrmFieldCombo.php, tests/fields/test_FrmFieldType.php, tests/fields/test_FrmFieldValidate.php, tests/fields/test_FrmFieldsAjax.php, tests/forms/test_FrmFormsController.php, tests/forms/test_FrmFormsControllerAjax.php, tests/misc/test_FrmAddon.php, tests/misc/test_FrmAntiSpam.php, tests/misc/test_FrmHoneypot.php, tests/styles/test_FrmStylesController.php, tests/views/shortcodes/test_FrmFieldShortcodes.php
Trying to capture 2 pretty big issues with our unit tests here.
A lot of tests fail with this `The following file is not importing correctly: https://s3.amazonaws.com/fp.strategy11.com/images/knowledgebase/global-settings_enter-license1.png` message lately. I think, because we have more tests than before, that we're hitting rate limits trying to get files from our CDN.
These are grabbed every time setUp is called which can be quite often. I tested running the pro unit tests locally and logging how many times this avoided a download and I got _186 hits_. That should hopefully help speed up unit tests too if we don't have to download files from an external server as often.
```
1) test_FrmProFieldRange
The following file is not importing correctly: …
```
=> Fix issues with failing unit tests

.github/workflows/phpunit.yml, classes/views/frm-forms/add_field.php, css/frm_admin.css, js/formidable_admin.js
Following up on the other field dropdown accessibility update, I missed a couple details.
- It looks like I had messed up the styling on the Delete Group/Duplicate Group options because it uses a different style definition.
- It also looks like clicking just the edge of a Delete Field/Duplicate Field/Field Settings option wasn't triggering it, only if you clicked the text.
- It looks like it was still difficult to Delete/Duplicate a Field Group using a screenreader.
So I've made them use the same style class now with a new `frm_more_options_li` class, added a tabindex and focus() when the dropdown opens to help imrprove accessibility.
I also added in a fix that was on my todo list for side-by-side field enhancements, to delete tooltips when a field is deleted. I don't think there's a very …
=> Tweak field dropdowns

bin/zip-plugin.sh
I had packaged this in the pro release by accident initially, and ended up rebuilding to take it back out.
Adding an exception so it never gets added in.
=> Exclude temp.xml when making zip

classes/controllers/FrmFormActionsController.php, classes/views/addons/list.php, classes/views/frm-form-actions/default_actions.php, js/formidable_admin.js
This PR does a few things:
- Before, MailChimp shows in the top row of the form actions. This replaces MailChimp with HubSpot.
- The message shown for add-ons in the upgrade modal can be customized with data-message (the same as fields)
- Allow links in the download excerpt on the add-ons list page
- If the message is customized, show it separately from the upgrade button
- Add a custom message in the HubSpot class
There are three different scenarios for this modal:
1. Only Lite installed
2. Pro installed without access to HubSpot
3. Pro installed with access to HubSpot
(When the HubSpot add-on is installed, nothing should be different since the modal doesn't show.)
=> Include HubSpot signup

classes/helpers/FrmAppHelper.php, classes/models/FrmField.php, classes/models/FrmForm.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3250 though there maybe other places to filter as well that I missed.
For now I'm filtering field label, description, and custom_html.
As well as form name, description, submit text, success message, before html, after html, and submit html.
This is only if:
- The DISALLOW_UNFILTERED_HTML constant is on
or 
- The user logged in does not have the unfiltered_html permission
A super admin shouldn't notice a difference unless the constant was on.
=> Check unfiltered html permission before allowing unfiltered form/field data

css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/3227
It looks like it's just a big box shadow making it look so off.
I made the box shadow tiny now and I don't offset it at all so it takes up the proper space.
I think it looks a lot better, https://recordit.co/wGws2tTqY1
=> Change box shadow style on draggable options

classes/controllers/FrmFormsController.php, classes/controllers/FrmXMLController.php, classes/helpers/FrmXMLHelper.php
Part of https://github.com/Strategy11/formidable-pro/issues/3260
Because of caching-related issues I can never just turn this on and change the actual default with likely breaking a ton of forms. I have a few other items in my list to help promote this feature for those old forms.
But this part is easy and makes a big difference to change the default on new forms.
=> Set antispam token on new form creation

js/formidable.js
I noticed that because of this `.frm_required_field:visible input` selector every single rich text button (bold, italic, etc) is checked.
I'm just skipping these earlier rather than calling checkRequiredField on something that is not a field.
Also cleaning up the validate function. It takes fieldId as the first parameter but never uses it. It looks like it's inaccessible outside of this file so removing it should be safe.
=> Stop trying to validate rich text buttons

classes/helpers/FrmStylesHelper.php, css/_single_theme.css.php, css/custom_theme.css.php, tests/styles/test_FrmStylesHelper.php
Fixes part of https://github.com/Strategy11/formidable-pro/issues/3253
Focusing on removing this line.
```
$settings = $_GET;
```
But it looks like we don't really sanitize the data that comes through `$_POST` either.
I'm pulling all of the default keys and only using those. In my testing, that didn't seem to break anything. But I could use extra testing here @garretlaxton making sure that none of the styles go unsaved here.
I noticed that this gets triggered when you click "New Style". It creates this big URL,
```
http://example.com/wp-admin/admin-ajax.php?action=frmpro_load_css&flat=1&theme_css=ui-lightness&theme_name=UI%20Lightness&center_form=&form_width=100%&form_align=left&direction=ltr&fieldset=0px&fieldset_color=000000&fieldset_padding=0%200%2015px%200&fieldset_bg_color=&title_size …
```
=> Validate and sanitize style settings preview

classes/helpers/FrmFormsHelper.php
Talked about this in slack the other day.  It came up in Helpscout the other week. As I went into this code, it becomes pretty clear what is missing (the frm_inline_form class). We could probably make this more clear just with documentation, but it's also something we can just check for and add automatically 🕺
When `frm_inline_submit` is added in custom HTML for a form, the frm_inline_form class will be added automatically (if it isn't already set), because without it it does nothing.
**Before**
**After**
=> Add frm_inline_form to forms with inline submit class (if missing)

classes/models/FrmAddon.php
This should fix the issue with any add-ons with a different name for the main file as the plugin folder. This was written assuming the plugin folder name would always have a file with the same name to go with it.
There is a separate issue in the signature plugin too. PR incoming for that in the add-on.
=> Fix issue with some add-ons not showing the plugin info

classes/controllers/FrmXMLController.php
Tried exporting a CSV for a form that wasn't on my server and it results in two errors when there is no form found (since it's trying to find things with no id).
```
PHP Warning:  Attempt to read property "id" on null in /var/www/src/wp-content/plugins/formidable/classes/controllers/FrmXMLController.php on line 570
[04-Nov-2021 13:38:46 UTC] PHP Notice:  wpdb::prepare was called <strong>incorrectly</strong>. The query argument of wpdb::prepare() must have a placeholder. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.9.0.) in /var/www/src/wp-includes/functions.php on line 5663
```
Just making this safer by checking if no form is found and exiting early.
=> Validate form exists when trying to export csv

classes/helpers/FrmAppHelper.php, deprecated/FrmDeprecated.php, js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3254
Also requires https://github.com/Strategy11/formidable-pro/pull/3305
Since the theme selector is a pro-only feature I've also moved all of the JavaScript events out and put them into the newer pro style-settings.js file.
=> Remove jquery_ui_base_url from free plugin

classes/helpers/FrmFieldsHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3303
The issue isn't too crazy. It just has to replace `[\/if 4938]`. Since the post content can be in JSON objects now it can be backslashed.
=> Add backslashed if conditional to switch_field_ids function

classes/models/fields/FrmFieldCombo.php
Part of https://github.com/Strategy11/formidable-pro/issues/3253
The line
```
formidable/classes/models/fields/FrmFieldCombo.php:377: echo implode( ' ', $atts ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
```
Was brought up. And I'm trying to use phpcs:ignore as little as possible now.
Getting around this is pretty easy by just doing the escaping in the loop instead. I also got rid of `$atts` as the only other use for it was for placeholder which appears to be safe just passing into `$field` and letting `do_action( 'frm_field_input_html', $field );` handle it.
Requesting your review on this @truongwp since you wrote it initially. See any issues with this update?
=> Remove phpcs ignore from FrmFieldCombo

classes/helpers/FrmAppHelper.php, tests/misc/test_FrmAppHelper.php
Part of https://github.com/Strategy11/formidable-pro/issues/3253
Adding filtering for this `echo $icon` line is a little tricky and requires some additional filters that kses calls to allow for some exceptions in the style attribute values.
=> New function FrmAppHelper::kses_icon

classes/models/fields/FrmFieldCombo.php, tests/fields/test_FrmFieldCombo.php
Didn't notice I broke the unit tests with https://github.com/Strategy11/formidable-forms/pull/618
The string looks slightly different (order of attributes has changed, spacing has slightly changed). Nothing big.
=> Fix unit tests for combo fields after removing phpcs exception

classes/controllers/FrmEntriesController.php, classes/helpers/FrmAppHelper.php, classes/views/frm-fields/front-end/combo-field/combo-field.php, classes/views/frm-form-actions/_action_icon.php, classes/views/frm-form-actions/settings.php, classes/views/shared/form-nav.php
Related to https://github.com/Strategy11/formidable-pro/issues/3253
I'm trying to remove phpcs:ignore lines wherever possible. In both of these cases (array_to_html_params and js_redirect), if the function handles the echo there is no need for any phpcs:ignore line, as long as the logic is duplicated in a way that doesn't involve echoing an unescaped variable.
So with both of these I've added a new `$echo` param. I also found a line in a combo field view where this function was able to replace some logic.
This update removes 6 phpcs:ignore comments.
=> Add echo params to array_to_html_params and js_redirect functions

classes/views/frm-fields/back-end/dropdown-field.php, classes/views/frm-fields/front-end/dropdown-field.php
Removes two phpcs:ignore comments by removing the code entirely since it isn't used anymore.
Tested with a snippet:
```
add_action(
'plugins_loaded',
function() {
$field_object = FrmField::getOne( 326 );
$field        = FrmFieldsHelper::setup_edit_vars( $field_object );
$field_name   = 'item_meta[326]';
$view = FrmAppHelper::plugin_path() . '/classes/views/frm-fields/back-end/dropdown-field.php';
require $view;
die();
}
);
```
It renders fine by the back end view file, after I made sure that `$read_only` and `$html_id` are actually set. Otherwise, the require was throwing errors since the two views are fairly different.
=> Deprecate backend dropdown view

classes/models/FrmAddon.php
_I don't really know how to run this directly, this is pretty deep in EDD code, but I believe this shouldn't have any issues._
Related to https://secure.helpscout.net/conversation/1694625984/85305?folderId=4324209
If I have woocommerce installed and I run the following snippet:
```
set_site_transient( 'update_plugins', null );
```
> PHP Fatal error:  Uncaught Error: Attempt to assign property "translations" on null in /var/www/src/wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php:81
> Stack trace:
> #0 /var/www/src/wp-includes/class-wp-hook.php(305): WC_Helper_Updater::transient_update_plugins(NULL)
> #1 /var/www/src/wp-includes/plugin.php(189): WP_Hook->apply_filters(NULL, Array)
> #2 /var/www/src/wp-includes/option.php(1977): …
=> Set update plugins transient to object instead of null

classes/helpers/FrmAppHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3315
Surprised I missed this, but it isn't often I click the ellipses.
=> Do not strip data-open from icons

classes/helpers/FrmStylesHelper.php
I don't think this was causing issues because the variable was never accessed in this condition but it looks like `$style` was already taken as a variable name.
And it looks like I didn't declare it early enough if the get condition was being used, which is actually a bug.
Noticed this running phpstan
```
------ ---------------------------------------------------------------
Line   classes/helpers/FrmStylesHelper.php
------ ---------------------------------------------------------------
353    Call to an undefined method WP_Post::sanitize_post_content().
------ ---------------------------------------------------------------
```
=> Rename variable when sanitizing post content on preview

classes/helpers/FrmAppHelper.php, tests/misc/test_FrmAppHelper.php
I looked at every call to `FrmAppHelper::icon_by_class` to make sure I wasn't missing anything this time.
Found one more missing attribute (title) getting removed.
Added a few extra unit tests as well to cover this.
=> Add more kses icon unit tests and an exception for svg title

classes/helpers/FrmStylesHelper.php, tests/styles/test_FrmStylesHelper.php
https://secure.helpscout.net/conversation/1704392934/86079?folderId=2445391
It looks like border colors are the only setting that calls this function. It's used to calculate the color of an alt table row (zebra striped).
I missed this when I added rgba support to styles. Now I'm checking for rgba, and adjusting it if I find it.
=> Support rgba in adjust brightness function

classes/views/frm-forms/settings-advanced.php, classes/views/frm-forms/spam-settings/akismet.php, classes/views/frm-forms/spam-settings/antispam.php, classes/views/frm-forms/spam-settings/honeypot.php
The other day a ticket came up asking about the difference between honeypot and the antispam token (https://secure.helpscout.net/conversation/1709526153/86563).
We have enough information on this in our documentation at https://formidableforms.com/knowledgebase/add-spam-protection/. But if people don't check the documentation, this can be confusing. It isn't very clear what the new JavaScript token option actually is from a glance, or that it's even a token at all.
I've just added tooltips to make the plugin more educational on the topic as it isn't very straight forward. Hoping this can help avoid future tickets like that one. I also mention that file uploads can be protected with the antispam token if pro is installed only as it isn't applicable for free use, which is somewhat related …
=> Use css grid for spam settings and add tooltips

classes/controllers/FrmFormsController.php, classes/views/frm-fields/back-end/html-content.php, js/formidable_admin.js
Figured I'd give a go at this Sprint item https://app.asana.com/0/1201149924118706/1201160282718496
HTML fields are a free plugin thing and nothing here requires the paid plugin so I put everything here. If we want to move it and call it a more premium feature of HTML fields, let me know!
I also needed to update `should_insert_form_popup` a bit to include the formidable builder page now.
Most of this is JavaScript copied from pro and views code. All of the weird tiny mce issues I had I've had before so things weren't too hard to figure out.
I'm also not sure if we want to address the styling at all? There isn't a lot of space here for a wysiwyg so it gets kind of squished and take up more vertical space than it really needs.
Or if we want to remove any of the buttons? It might be that we …
=> Use tiny mce for html field descriptions

classes/models/fields/FrmFieldTextarea.php
Looking for more opportunities to improve on https://github.com/Strategy11/formidable-pro/issues/3253
This update removes two `phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped` comments. It turns out the first one was there for no reason and was passing without the comment.
I broke it out into multiple echo statements. The big echo was making it difficult to output the style without the need for an exception, and it wasn't really escaping in the right place as it was happening after `width:`, and the semi colon is after it closes the style attribute, which looks like a bug.
Instead of setting `$default_value`, I echo at the same time that we call `FrmAppHelper::esc_textarea` so it's more clear that escaping is happening here. That's the only exception that can't be removed.
=> Remove phpcs exceptions from textarea show_on_form_builder function

classes/helpers/FrmFormsListHelper.php, classes/helpers/FrmListHelper.php, classes/views/addons/list.php
Part of https://github.com/Strategy11/formidable-pro/issues/3253
This update removes 4 more phpcs exceptions by replacing echo statements that aren't easily escaped with calls to `FrmAppHelper::array_to_html_params` that handles the escaping more nicely.
I also cleaned up the part that was checking `} elseif ( method_exists( $this, 'column_' . $column_name ) ) {`. The `else` condition directly under it was doing the exact same thing, just not calling the method. It makes more sense to just put this if in with the else to get rid of duplicate code.
=> Remove phpcs exceptions in FrmListHelper

js/formidable_admin.js
I noticed the new rich text HTML editor logic is triggering JavaScript errors for fields that do not have a wysiwyg. Surprised this was missed to now. It doesn't seem to break anything though.
Just adding a few checks if editor is there before going further.
=> Add checks if editor actually exists in field setting

classes/helpers/FrmStylesHelper.php, css/_single_theme.css.php
- allow for more transparent bg colors
- On focus, use the color set for input fields
These came up while working on this style template:
https://sandbox.formidableforms.com/demos/wp-admin/admin-ajax.php?action=frm_forms_preview&form=contact-us
Before:
Read only fields and fields with focus had a white background and black text
After:
Transparent bg is allowed for read only and fields with focus.
The active input color now overrides the theme.
This is all tested and pretty minor changes.
=> Fixes for white styles on dark bg

classes/helpers/FrmFieldsHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3354
It looks like back in January 2020 there was a commit https://github.com/Strategy11/formidable-forms/commit/81d916fa94cd6b8555a903f4d6af6fcdddd4f52d
That added the `data-message` in always. Before, it was never there. So it looks like it was broken one way (it was never appearing), and then broken another way (always appearing).
That line of code is really long. I broke it up into an array and I'm calling `FrmAppHelper::array_to_html_params` now. I've kept the JavaScript the same.
=> Do not set data-message if it is empty

css/custom_theme.css.php
Related ticket https://secure.helpscout.net/conversation/1731135096/88134/
A customer is using `The H-Code premium WordPress theme from Themeforest.`.
The default styles show a radio input something like
I looked at a demo of H-Code and added a radio input to the page to see what styles were on it, and found:
So I'm fighting this so the default is `float: none` instead of the `float: left` that's messing it up.
I didn't have H-Theme but I replicated this by putting that CSS in my theme CSS, and then fixed it with this new style rule:
=> Add float none to radio and checkbox inputs

classes/helpers/FrmFieldsHelper.php, classes/helpers/FrmFormsHelper.php, classes/models/FrmForm.php, js/formidable_admin.js, tests/forms/test_FrmFormsHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/830
This update does a few things:
1. When you click to insert a field shortcode, if the field is not a URL type, the sanitize_url=1 option is injected automatically.
2. On save, if there are shortcodes detected in the success_url URL params, I add in the `sanitize_url=1` option. This way they get caught even if you didn't use the pop up.
3. Added support for sanitize_url and sanitize shortcode options when replacing shortcodes in the free plugin.
**Before saving**
**After saving**
=> Add sanitize_url=1 to redirect url shortcodes on save

css/_single_theme.css.php, js/formidable.js
Part of https://github.com/Strategy11/formidable-dates/pull/68
On its own it will validate and properly prevent the page from submitting but requires https://github.com/Strategy11/formidable-dates/pull/68 for an error message to be displayed.
One funny thing I was also noticing was that the error border styling happens on the month/year pickers.
We have this style set
So I added some `:not` rules to the theming so it avoids those.
=> Do not skip required inline datepicker in js required check

changelog.txt, readme.txt
@stephywells right now this is scheduled for tomorrow.
I know you mentioned releasing Landing pages on the 4th though, which would probably require a core release next week.
Do you think we should hold off on this release for a week, or do a release both weeks, or do landing pages the next week on the 11th?
Also, do you think we should include anything in the change log for https://github.com/Strategy11/formidable-forms/pull/657? I wasn't sure what to put for that.
=> Update readme for 5.0.16

classes/helpers/FrmAppHelper.php, classes/models/FrmTableHTMLGenerator.php, tests/misc/test_FrmAppHelper.php
We had this ticket come up about a month ago for it, it’s not very common but it happens. It seems common with upgrades to PHP 7.4. The "fix" is install ctype, but I'd like to avoid the errors in the first place since it isn't difficult to.
https://secure.helpscout.net/conversation/1727655661/87904/
I was looking over the Symfony components the other day and noticed that they have polyfills for these functions as it seems to be pretty likely that they may not be available on every server.
I took this function from there (https://github.com/symfony/polyfill-ctype/blob/main/Ctype.php) but I left out the part that calls "convert_int_to_char_for_ctype", we only use this on strings so I don't think this is important in our use case.
It looks like it happens in other plugins quite often, you …
=> Add a fallback for ctype xdigit

classes/helpers/FrmAppHelper.php, classes/views/frm-forms/form.php, classes/views/frm-forms/multiselect-accessibility.php, classes/views/frm-forms/settings.php, classes/views/frm-settings/permissions.php, css/frm_admin.css, js/bootstrap-multiselect.js, js/formidable_admin.js
Bootstrap multiselect is now on version 1.1.1.
The new version is more accessible so I removed some accessibility updates I had added before that are no longer required.
Fixes https://github.com/Strategy11/formidable-pro/issues/3257
Fixes https://github.com/Strategy11/formidable-pro/issues/3394
This applies to all of the back end multiselect dropdowns. There are quite a few:
**In actions**
**Field visibility**
**Global Permissions**
**Other Role Dropdowns in Form Settings**
=> Update bootstrap multiselect

js/formidable_admin.js
Missed this when I updated bootstrap multi-select. I removed frm_multiselect_button so there's no reason to use it for `aria-describedby` anymore.
=> Remove old aria describedby

classes/controllers/FrmFieldsController.php, classes/models/FrmFieldFormHtml.php, classes/models/fields/FrmFieldType.php, classes/views/frm-fields/front-end/combo-field/combo-field.php, js/formidable.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3238
- Errors in new fields now include role="alert" so they get more screen reader attention on error.
- Old fields will inject role="alert" when it replaces the [error] shortcode even if it is missing from the custom HTML.
- JavaScript side validation now includes aria-describedby on an input on error. This was happening already with PHP-side validation, but not JavaScript validation.
There are also some small tweaks in pro https://github.com/Strategy11/formidable-pro/pull/3406 to add role="alert" to total fields by default as well.
=> Add role alert in default html

js/formidable.js
This is part of https://github.com/Strategy11/formidable-pro/issues/3396
This covers every non-deprecated call that uses frm_js.ajax_url in the free plugin, which is only 3 places so this wasn't too difficult.
I've moved the call to `jQuery.ajax` into the function and cleaned this all up a bit. The shared details (that it's a POST request, that it uses the ajax url, have all been moved into the function.
The new function is pretty straight forward. The first parameter is `form`, the element of the `<form>` tag which needs to be passed to every call to this function to determine whether or not the target form is an API form or not.
In my testing, a form loaded with the API includes an action attribute that uses the ajax url, just pointed to the preview page instead. So it's easy to parse …
=> New function postToAjaxUrl

classes/views/frm-fields/front-end/dropdown-field.php
Related ticket https://secure.helpscout.net/conversation/1775519188/91384/
The other trigger has a special class "frm_other_trigger" but every other option in the dropdown is showing `class=""` which is a lot of unnecessary HTML getting printed to the page. 
**Before**
**After**
=> Only include class on dropdown option if other option

js/formidable.js
Following up on https://github.com/Strategy11/formidable-forms/pull/684
It looks like resendEmail really isn't form related. I'm just going to leave it alone. Copied it back from v5.1.
**Edit** - Seems the same for update field. I really only need to update the one in the free plugin.
=> Revert resendEmail function

classes/controllers/FrmStylesController.php
I need to add this new filter so that the API add on can overwrite the path to the fonts and use an action instead.
Because of CORS blocking the fonts need to include the `Access-Control-Allow-Origin` header but in order to do that and have it work on both Apache and Nginx (since htaccess doesn't work for both) I need to do this with PHP and serve the file afterward.
Related branch https://github.com/Strategy11/formidable-api/pull/103
=> New filter frm saved css

changelog.txt, classes/controllers/FrmAppController.php, classes/controllers/FrmFormsController.php, classes/controllers/FrmStylesController.php, readme.txt
Changing a few extra things.
- Going with 5.2 instead of 5.1.01 so changed some version tags.
- Bumping the minimum WordPress version to 5.2 now.
- Noticed I switched from asterisks to dashes a while ago without noticing. They used to be asterisks, I change them back for consistency.
=> Update readme for 5.2

classes/controllers/FrmAppController.php
I've switched to using the WordPress 6.0.0 beta locally.
It's logging a new deprecation.
> PHP Notice:  Function add_menu_page was called <strong>incorrectly</strong>. The seventh parameter passed to <code>add_menu_page()</code> should be an integer representing menu position. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.0.0.) in /var/www/src/wp-includes/functions.php on line 5768
I'm not totally sure why these are strings at the moment or why they are using decimals. But it looks like WordPress wants integers (non-decimal values), so I rounded down to 29 instead. Same position as before (under comments).
I looked at the last commit that changed this three years ago. …
=> Menu position should always be an integer

classes/helpers/FrmAppHelper.php
Noticed a PHP8+ deprecated message in this function. I'm not totally positive how I ended up with a null, I was playing with a few things.
> PHP Deprecated:  json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/src/wp-content/plugins/formidable/classes/helpers/FrmAppHelper.php on line 2571
=> Do not call json decode on null fix

classes/controllers/FrmStylesController.php, classes/helpers/FrmAppHelper.php
Running some tests with phpstan, I noticed these small issues. Easy fixes.
------ ---------------------------------------------------------------------------
Line   classes/controllers/FrmStylesController.php
------ ---------------------------------------------------------------------------
340    Result of static method FrmStylesController::custom_css() (void) is used.
------ ---------------------------------------------------------------------------
------ ------------------------------------------------------------------------------------------
Line   classes/helpers/FrmAppHelper.php
------ ------------------------------------------------------------------------------------------
3292   Static method FrmFormsHelper::get_plan_required() invoked with 2 parameters, 1 required.
------ …
=> Phpstan rule fix - custom css void is used

.gitattributes, .github/workflows/phpstan.yml, bin/zip-plugin.sh, classes/helpers/FrmListHelper.php, classes/models/FrmEntryFormatter.php, phpstan.neon, phpstan.stubs.php, tests/misc/test_FrmDirectFileAccess.php
Fixes two remaining issues. I'm hiding the rest at the moment with the goal of removing exceptions over time. But it is running at the max level already aside from those exceptions.
Runs in 7-11 seconds, significantly the fastest workflow which is nice for a few reasons - catching issues faster, using less of our GitHub allowance.
------ -----------------------------------
Line   classes/helpers/FrmListHelper.php
------ -----------------------------------
1156   Undefined variable: $data
------ -----------------------------------
I trace this error back to 6 years ago when Jamie copied the file from WordPress and missed the undefined variable https://github.com/Strategy11/formidable-forms/commit/14289c2500f3a358abbb5fbc2370da6f6bd4cb33
It's trying to call a function that starts with …
=> Add a PHPStan workflow

classes/models/FrmFormAction.php
Before:
Making changes to the saved form action settings using either the frm_before_save_action hook or the update() function were lost.
After:
This carries the changes forward from these hooks and function.
=> Fix issue with resetting values in a form action

css/custom_theme.css.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3397
Took a while figuring out how to reliably replicate this without enfold. I ended up copying the CSS from their demo into a blank HTML file and pulled in a new API form 😂.
The issue is actually pretty simple, just annoying to debug. Enfold includes this rule on checkboxes, `#top input[type="checkbox"]{display:inline}`. Because of the `#top` reference it beats our CSS rule and forces the checkbox to inline instead of inline-block. Since it's targeting by id, I think our best bet here is to just use `!important`.
=> Fix issue with checkbox styling in enfold

classes/controllers/FrmFormsController.php, classes/views/frm-entries/direct.php, classes/views/frm-forms/settings-advanced.php
Right now I've added two new check boxes to turn on/off the visibility of the form title/description which are currently always on in previews and off but adjustable with options for an embedded form. Now it's based off of this setting, which is off by default, so the default behaviour of a preview page is changing with this update, for consistency.
This has been included as part of a design we never implemented, as toggles. Right now all of our CSS for toggles is used for front end toggle fields and included in pro only, so it's a lot easier to just use checkboxes. Otherwise I'll need to pull the CSS into the free plugin and it will need to load all of the toggle styles twice.
That probably makes more sense either way since the other options on this page are currently all check boxes and …
=> Add form show title description options

classes/helpers/FrmFormsHelper.php
Noticed a small issue with https://github.com/Strategy11/formidable-forms/pull/706
Some warnings are getting logged on the settings page.
> [22-Feb-2022 18:17:43 UTC] PHP Warning:  Undefined array key "show_title" in /var/www/src/wp-content/plugins/formidable/classes/views/frm-forms/settings-advanced.php on line 34
> [22-Feb-2022 18:17:43 UTC] PHP Warning:  Undefined array key "show_description" in /var/www/src/wp-content/plugins/formidable/classes/views/frm-forms/settings-advanced.php on line 41
I wasn't defining defaults.
=> Add show title/show description values to defaults array

classes/models/FrmEntryValidate.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3434
This doesn't apply to old entries unless the user updates them.
Besides the `name` and `text` fields, we can add support for more field types. I'm not sure if we should do that.
=> Allow name fields to be the entry name

classes/controllers/FrmFormsController.php
I noticed we call these two lines of code in a few places and I was refactoring it to one function.
Then I noticed one of those functions is private and never gets called so I'm removing it.
=> Remove unused function FrmFormsController::init_modal

js/formidable_admin.js
Continuing to test bootstrap https://github.com/Strategy11/formidable-forms/pull/708
I noticed that there are these dropdowns with radio buttons in them in the style manager. There's code I missed that was syncing the icons with the button trigger. However, it looks like one of those (sections) had broken at some other point in time before the bootstrap update. So this fixes that.
I also made some other slight adjustments so events don't get stripped when the html changes with anchors inside. And added a little extra bit to try to make sure toggles are more accessible just in case. And I noticed the old `multiselectAccessibility` function in JavaScript that I missed when I pulled out the PHP code related to this. This no longer applies.
**Before in version v5.2**
**After**
=> Cleanup bootstrap code

css/custom_theme.css.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3461
@truongwp I didn't see an easier way to target these. If you have a better option moving forward, feel free to make another pull request.
=> Only set margin-bottom 0 for name subfields

classes/controllers/FrmXMLController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3455
The issue is that the loop sets `$name` but `$name` is supposed to be `$name  = FrmAppHelper::get_param( 'name', '', 'post', 'sanitize_text_field' );`. We don't want to overwrite it in this loop.
I renamed the loop variable to `$sanitized_form_name` instead, so it isn't overwriting `$name`.
Also cleaned up some of the logic where it was checking more than necessary or doing a weak check.
=> Do not overwrite $name when looping xml data

classes/controllers/FrmAppController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3459
They use Popper 2 but Bootstrap 4 uses Popper 1. De-registering it so it registers our popper js instead fixes the issue.
=> Fix Duplicator Pro conflict

classes/helpers/FrmAppHelper.php, tests/misc/test_FrmAppHelper.php
Related ticket https://secure.helpscout.net/conversation/1814896451/94441
> If you could add "___" to me before each random string, it would solve all my problems.
It seems like the easiest solution to their issue. Seems like a nice enhancement to add as well.
Example use.
```
function use_custom_field_key_separator() {
return '___';
}
add_filter( 'frm_unique_field_key_separator', 'use_custom_field_key_separator' );
```
Also supports `add_filter( 'frm_unique_form_key_separator', 'use_custom_form_key_separator' );`, etc. I figure passing the column in the filter name makes the most sense in this case.
But I'm open for suggestions to a different solution as well.
=> Allow for custom field key separators

css/frm_admin.css
I'm not totally sure when this actually was introduced. It looks like it was still happening when when I was checking out v5.0. I think it may have changed to a button when I updated bootstrap multiselect.
```
.frm-fields button.btn {
padding: 6px 9px;
}
```
I was looking at a quiz action and noticed the multiselect dropdown is exceeding it's space, overflowing past the action container.
**Before**
**After**
I also dropped a `vertical-align` style because that doesn't work with `display: block`. A warning gets flagged on my IDE about it.
=> Add border box box sizing to admin css buttons

classes/models/FrmEntryValidate.php, tests/entries/test_FrmEntryValidate.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3482
In the previous version, we get the field IDs of choice fields that don't have `Other` option. In this version, I get the field ID and options of all choice fields, then loop through to check.
=> Exclude field options from Akismet comment data

classes/widgets/FrmElementorWidget.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3487
Found a thread on this deprecation on the Elementor forums.
https://forum.elementor.com/fixing-common-issues-33/deprecated-register-controls-is-deprecated-since-version-3-1-0-11123/index2.html
The majority of comments were people who didn't understand the issue until I came across this comment.
Easy fix. The same function exists just without the underscore.
=> Remove underscore from register controls function (Elementor widget)

classes/helpers/FrmAppHelper.php, classes/models/FrmFieldFormHtml.php, js/formidable.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3507
This update adds two new simple filters that allow you to turn off specific accessibility features (as requested by this user).
```
add_filter( 'frm_focus_first_error', '__return_false' );
add_filter( 'frm_include_alert_role_on_field_errors', '__return_false' );
```
It should work with both JavaScript validation and without. If the role="alert" is included in custom HTML, it will be included anyway but this will prevent any forced insertion.
=> Add hooks for accessibility features

classes/helpers/FrmAppHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3583
This came up when I refactored the add new button code. I missed that the import button calls this code without any of the expected attributes.
My solution is to just check if none of the attributes are set. If all of those are missing it expects the function to do nothing.
The alternative is trying to do something like.
```
if ( ! $atts['import_link'] ) {
FrmAppHelper::add_new_item_link( $atts );
}
```
in the admin-header.php, or to check against `$atts['import_link']` specifically in this function but that introduces another option that isn't really related to the function.
But that would only catch the import button. This may effect other calls to `add_new_item_link`. As it's a public function I wouldn't be surprised if …
=> Remove unexpected add new button on import page

classes/controllers/FrmApplicationsController.php
Following up from a comment the other day.
> How complicated would it be to move allowed applications to the front of the list, and alphabetic each group separately?
=> Move unlocked application templates to the front

classes/helpers/FrmAppHelper.php, classes/models/FrmFormApi.php
Fixes https://secure.helpscout.net/conversation/1900124057/100035/
It happens when a call to `current_time( 'timestamp' )` is made if the `gmt_offset` WordPress setting is an empty string.
It's failing on this WordPress code.
```
time() + (int) ( get_option( 'gmt_offset' ) * HOUR_IN_SECONDS );
```
Technically this is more or a WordPress bug and we could probably remove this in the future. But it's causing fatal errors as soon as you load the admin pages if gmt_offset is set to an empty string. It's possible to fix on our end with this filter, and that probably makes sense while the issue exists in WordPress.
I made it public because it looks like pro uses `current_time( 'timestamp' )` as well so I think I may add an update there as well.
=> Add filter for gmt offset to avoid fatal error in php8

classes/controllers/FrmFormsController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3479
I can't really figure out why All in One SEO is causing this. But as long as `wp_print_styles` does not get called, it seems to work.
@stephywells you may understand this better. There might be a more robust solution. I didn't really get to the core of what's causing this.
=> Do not load css late if all in one seo is active

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3508
Tested it on the customer's site. Without the timeout it still wasn't working so whatever is hiding the postbox is hooking into the modal opening or something.
Long term it should be possible to try drawing this modal with JavaScript instead. Other modals like the new view/new application ones all appear to be fine, so I think it might have to do something with this modal existing already on page load.
=> Force postbox to display block in new form modal

classes/models/FrmEntry.php
Related ticket https://secure.helpscout.net/conversation/1924502130/101690/
There isn't a very practical way to hook into after these get deleted, just before. In this customer's case they want to build their cache after the deleting happens, which doesn't really work if you try to trigger it beforehand.
I opted to still pass the deleted entry so you can check it for specific things like form_id or post_id associated with the entry as well.
Example use.
```
add_action(
'frm_after_destroy_entry',
function( $entry_id, $entry ) {
$target_form_id = 294; // change this.
if ( $target_form_id !== (int) $entry->form_id ) {
return;
}
// Handle deleted entry for target form.
},
10,
2
);
```
=> New frm_after_destroy_entry_hook

classes/controllers/FrmApplicationsController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3645
=> Only include numeric application template keys to avoid errors appearing as templates

composer.json
This PR fixes the PHPStan broken workflow issue as described in [https://github.com/Strategy11/formidable-pro/issues/3663](https://github.com/Strategy11/formidable-pro/issues/3663).
=> Fixes PHPStan broken workflow adding composer/installer to allow-plugins rule.

classes/models/FrmTableHTMLGenerator.php, css/frm_admin.css
This updates the styling of a single entry in a table, based on the design here:
https://www.figma.com/file/K3L40rJTHXwjNeBA3LoWBr/%E2%9C%85-PDF?node-id=604%3A296
Requires https://github.com/Strategy11/formidable-pro/pull/3658
After:
=> Repeater-entry-style

classes/views/frm-form-actions/_action_inside.php
This becomes pretty apparent one you start trying to add a bunch of outcome quiz actions. The extra up-sell on every one takes up a lot of space.
I got confused by this before, when I went to install an autoresponder from this trigger only to refresh the action and see the settings didn't exist for my action type. I think it could be a misleading up-sell that could get customers frustrated thinking something supports automation when it doesn't.
This removes it from all quiz actions and others that aren't 'email', 'twilio', 'api', 'register', or 'zapier'.
**Before**
**After**
=> Stop showing autoresponder upsell for action types with no autoresponder support

classes/models/fields/FrmFieldType.php, tests/fields/test_FrmFieldType.php
Related to [https://github.com/Strategy11/formidable-pro/issues/3637](https://github.com/Strategy11/formidable-pro/issues/3637), a [PR](https://github.com/Strategy11/formidable-forms/pull/802) has been created to implement additional checks in `FrmFieldType::add_aria_description` function but the unit test for this function was not updated yet to cover the new changes to the function. This PR is targeted at updating the unit test that covers this so that the expected values are based on the new logic.
=> Update unit test to cover enhancements to add_aria_description function

js/admin/dom.js
Pretty positive this fixes https://secure.helpscout.net/conversation/1953381559/103981/ but it's tough to test against their caching.
You can see this behaviour if you try `eval( 'var testVariable = "testValue";' );` vs `eval( 'let testVariable = "testValue";' );`. The let example won't declare testVariable globally.
=> Declare frmDom as window var

.eslintrc.json, classes/controllers/FrmAddonsController.php, css/frm_admin.css, js/formidable_admin.js
issue: [#3389](https://github.com/Strategy11/formidable-pro/issues/3389)
Following from [https://github.com/Strategy11/formidable-forms/pull/511](https://github.com/Strategy11/formidable-forms/pull/511), a `Save and Reload` functionality has been added to the popup that appears when activating addons from the settings page. However, that didn't cover the same action from form builder. This PR is to extend the existing code and bring the same functionality to the form builder.
=> Fixes Issue #3389

classes/controllers/FrmAppController.php, css/frm_admin.css, js/formidable_admin.js
This uses javascript to move the renew banner above the screen options in the HTML.
This also removes some css that is no longer needed.
**Before:**
(entries list)
(forms list)
(full screen)
(lite)
**After:**
=> Fix screen meta placement

classes/models/FrmForm.php
I'm trying to add the missing translatable form strings, which a form duplication become incomplete without them as their respective translated strings are not copied to the new form.
=> add missing form strings.

classes/helpers/FrmEntriesHelper.php, classes/models/FrmEntryValidate.php
I mentioned this in Slack. Not sure to it, just removing the content check so it always does the blacklist check on the other fields like IP address.
=> Do not exit early for empty content on denylist check

js/formidable_admin.js
To replicate, just add a checkbox with `data-toggleclass` inside a form action.
=> Fix data-toggleclass doesn't work with content from AJAX

classes/controllers/FrmEntriesController.php, classes/models/FrmEntryMeta.php
Fields with [auto_id] are not currently incrementing when an entry is duplicating, resulting in entries with the same value and that defeats the purpose of having unique values for a given field with the help of the shortcode.
This PR aims to make sure that field values with [auto-id] gets updated when duplicating an entry.
=> Recalculate [auto_id] on entry duplicate.

classes/models/FrmFormAction.php, tests/forms/test_FrmFormAction.php
Referencing a comment from Garret https://github.com/Strategy11/formidable-quizzes/pull/133#issuecomment-1212400320
He mentioned an issue.
```
PHP Notice: Trying to get property 'post_status' of non-object in wp-content\plugins\formidable\classes\models\FrmFormAction.php on line 425
```
I added a unit test to replicate the issue. I'm not sure how to get it to happen on the front end exactly. I'm just adding a few extra type checks.
The problem is really that there's a line in the code here.
`$old_instance = isset( $all_instances[ $number ] ) ? $all_instances[ $number ] : array();`.
That if `$all_instances[ $number ]` is not set will all back to an array rather than an object. But the status update function is assuming that `$old_instance` is never an array.
The unit test catches this. …
=> Add extra checks for data in actions

classes/controllers/FrmAppController.php, classes/controllers/FrmApplicationsController.php
Fixes https://secure.helpscout.net/conversation/1980393108/106481/
Fixes `Uncaught TypeError: wp.hooks is undefined` in Applications.
Fixes `Uncaught TypeError: hooks is undefined` in the Form Builder.
The "View All Applications" page also requires https://github.com/Strategy11/formidable-pro/pull/3759
=> Applications compatibility fix with wp 5.6

classes/views/shared/upgrade_overlay.php, css/frm_admin.css, js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3755
Not all of the oneclick logic was being carried over. Add on statuses were missing and not getting updated, etc.
I removed all of the ID-specific stuff and made everything work with classes and allowing for multiple instances of things. The upgrade tabs still borrow from the upgrade modal but will use their own elements after the elements are initially cloned now.
More code is being re-used now. And there's a bit less jQuery and a bit more ES6 than before as well.
=> Fix issues with landing page upgrade tab message not reflecting license

classes/helpers/FrmXMLHelper.php
Fixes an issue mentioned in https://secure.helpscout.net/conversation/1983340821/106865/
> When pages are imported as part of an application they do not remember their parent page when it's brought across in the same application.
=> Update post parent id if imported page id parent matches

classes/models/FrmPluginSearch.php
- Some plugins weren't showing up in the plugin search results like "paypal"
- Shows add-ons in results, even if they don't already have access
- Add frm_plugin_search hook for adding more plugins into the search results (for internal use, no documentation needed)
=> Fix plugin search

classes/models/FrmEntry.php
Fixes https://secure.helpscout.net/conversation/1987233335/107342/
Deleted actions do not trigger conditional logic if the conditions are based off of item meta because the item meta is missing from the object.
=> Get meta with entry in FrmEntry::destroy function

js/formidable_admin.js
This pop up happens if you try to insert a field and then click save and try to leave the page before the field has inserted. It triggers the AJAX error function as it's aborted. Checking for a status code of 0 is the closest I could find to checking for that.
It's the third answer here but I don't think either of the first two are perfect either. The biggest criticism it has is that it will catch some other types of errors as well.
https://stackoverflow.com/questions/4807572/jquery-ajax-error-handling-to-ignore-aborted#answer-5958734
I tested the pop up with an error by failing the nonce check. It still works great. And the summary field re-enables fine. However I'm seeing other issues that can lead to 2 summary fields that I plan to look into as well.
=> Avoid empty error pop up when aborting jquery

classes/helpers/FrmAppHelper.php
Related update https://github.com/Strategy11/formidable-pro/pull/3777
This updates adds a lot of languages.
For date picker localization this adds. I checked against the old https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.min.js file and it already included support for all of these.
- ar-DZ (Algerian Arabic)
- be (Belarusian)
- cy-GB (Welsh)
- gl (Galician)
- ka (Georgian)
- kk (Kazakh)
- km (Khmer)
- ky (Kyrgyz)
- lb (Luxembourgish)
- mk (Macedonian)
- ml (Malayalam)
- nb (Norwegian Bokmal)
- nn (Norwegian Nynorsk)
- rm (Romansh)
- tj (Tajiki)
For reCAPTCHA this adds
- mr (Marathi)
- lo (Laothian)
- kn (Kannada)
- si (Sinhalese)
- gu (Gujarati)
- bn (Bengali)
- zu (Zulu)
- ur (Urdu)
- te (Telugu)
- sw (Swahili)
- am (Amharic)
I added all of the language code for …
=> Add more languages

css/frm_admin.css, js/formidable_admin.js
Following up on a Slack conversation from last week.
> I think we decided we shouldn't prevent it. That code must have been missed when we removed the limitation.
I kept the error handling that shows a pop up but renamed the function and removed the unneeded parameters required for summary field checks. There was quite a bit of old code left in here, lots to remove 🥳
I also switched from using `var` to `let/const` in more code so we can keep reducing our vars-on-top warnings. Only about 140 to go 😅.
I also updated a style rule. I noticed the clone option for summary fields is disabled. I removed the rule for a moment but it doesn't look too straight forward to enforce the "insert a page break" logic in there as well. Maybe that isn't important if two summary fields are on the same page …
=> Stop disabling summary fields

css/custom_theme.css.php
This fixes a conflict with Astra.
I noticed dropdowns all look weird like this in Astra. It's easy to fix though by adding a `background-position-y: center` style to a select.
**Before**
**After**
=> Vertically center background images in formidable dropdowns

classes/models/FrmEntryValues.php
I noticed these two warnings when I viewed an entry that I created from a Post. Because it doesn't get submitted normally, the description is just "Copied from Post" and these array keys don't exist.
=> Check if array keys exist in init_user_info function

classes/controllers/FrmAddonsController.php, classes/helpers/FrmAppHelper.php, classes/models/FrmPluginSearch.php, classes/models/FrmUsage.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3802
This exact issue is fixed all over the place. I added a new helper function that handles this check to reduce the copied/pasted checks we have all over.
=> New function FrmAppHelper::get_plugins that adds missing file

js/formidable_admin.js
This is just a small enhancement for side-by-side fields.
The way the multi-select works when you're holding the shift key, it would only consider the field group as selected if the actual field group was. Since a single field fills in the whole group it isn't very easy to click on the field's group without clicking on the field.
This means that when you shift+click it would just work like the `Cmd`/`Ctrl` key and just select another field group without using the shift rule of selecting all groups in between as well.
**Before**
**After**
=> Treat single field in group as selected group for multiselect

classes/controllers/FrmFormsController.php, classes/helpers/FrmFormsHelper.php, classes/models/FrmEmail.php
I went through the feature requests more today and found this one.
https://team.strategy11.com/feature-requests/2021/04/30/form-name-shortcode-for-emails/?modal=1
> I need to include the form name in the email message admin receives.
> I can't get [form_name] to work.
It has 10 upvotes and it is a pretty small task so I gave it a go.
This update adds support for the `[form_name]` shortcode in email subject and in email message.
**Before**
**After**
=> Add form name shortcode to email actions

classes/controllers/FrmFieldsController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3780
This update avoids having double autocomplete html attributes in a field by making sure that the option set in the field settings override the input shortcode html.
=> make sure autocomplete option has priority over input shortcode.

tests/base/FrmUnitTest.php, tests/entries/test_FrmPersonalData.php, tests/forms/test_FrmForm.php, tests/misc/test_FrmAppController.php, tests/misc/test_FrmAppHelper.php
- Checks if the install functions have been called yet, and avoid calling them a second time.
- Adds a second check for file path in case the file isn't in the formidable folder but in a formidable/form_id folder instead.
- Only try to create users for the unit tests that require users to pass.
=> Add a static installed bool for PHPUnit

classes/models/FrmEntryValidate.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3819
This is the first thing I tried to fix this. The item name has a length limit of 255, the example string was too long. Worked like a charm 🥳
=> Truncate super long entry names

.github/workflows/phpstan.yml, classes/helpers/FrmXMLHelper.php, phpstan.neon, stubs.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3746
This can be tested with the XML from https://github.com/Strategy11/formidable-quizzes/pull/155 as well which includes src data for both radio buttons with image options and for quiz outcomes.
=> Add image src to exported image field options

classes/helpers/FrmEntriesHelper.php
Related ticket https://secure.helpscout.net/conversation/2016033128/110605/
I'm not too sure how they have a string `field_options`. But I figure it's best to be on the safe side and avoid calling `array_merge` on a string.
=> Avoid fatal error when setting up a field with string field options

css/frm_admin.css
Related to https://github.com/Strategy11/formidable-googlespreadsheet/issues/12
This gets us a bit closer to the design with a bit bigger font size and more padding for the inside.
Design:
Before:
After:
=> A bit more styling on the default modals

classes/helpers/FrmAppHelper.php, classes/helpers/FrmStylesHelper.php, css/custom_theme.css.php
Part of https://github.com/Strategy11/formidable-pro/pull/3829
Lite doesn't require the font icons CSS. And Pro should be loading it. So in v5.5.1 I'm moving this to Pro (with https://github.com/Strategy11/formidable-pro/pull/3831).
If Pro is not active, this will still load the CSS if the Signatures add on is active. Otherwise the icons for signature fields also break. I added an issue in Signatures to switch to SVGs there as well. Eventually we can add a version check for Signatures too but it's harder to time that release https://github.com/Strategy11/formidable-signature/issues/84
**Size of formidable.css before**
**Size of formidable.css after**
Saving around 11.5KB.
=> Remove font icons from css

js/formidable_admin.js
This update helps make sure that when something with "frm_show_expired_modal" will always properly trigger the expired modal. I was seeing some inconsistency where clicking certain areas would trigger the upgrade modal instead.
It also makes sure that anything `.frm_show_upgrade` doesn't re-activate on load.
Required for https://github.com/Strategy11/formidable-pro/pull/3825
=> Update handleUpgradeClick function

classes/controllers/FrmFormsController.php
Fixes https://secure.helpscout.net/conversation/2021199211/111203/
The preview query function sets a random page. In this customer's case it was setting their "Posts Page" or "Blog Page" which meant that it was showing the 10 recent posts, and we were overwriting all 10 of them resulting in 10 forms.
=> Avoid posts page when setting a random page for preview

classes/views/frm-form-actions/_email_settings.php, css/frm_admin.css, js/admin/dom.js, js/formidable_admin.js, tests/base/FrmUnitTest.php
Includes https://github.com/Strategy11/formidable-forms/pull/885
And includes an update from Abdi that supports this update https://github.com/Strategy11/formidable-forms/pull/873
Fixes https://github.com/Strategy11/formidable-pro/issues/3737
Fixes https://github.com/Strategy11/formidable-pro/issues/3757
This update adds support for a rich text editor in email actions, which is a fairly highly voted feature request https://team.strategy11.com/feature-requests/2021/04/30/wysiwyg-email-editor/?modal=1
The shortcode popup will now appear directly below the text areas so it doesn't get in the way of seeing the content.
https://github.com/Strategy11/formidable-pro/issues/3757
=> TinyMCE Email Actions + Shortcode popup fix

js/admin/dom.js, js/formidable_admin.js
Rather than copying/pasting this logic for quiz outcomes I think it makes more sense to just re-use it from Lite so I'm moving it into the dom.js file as a wysiwyg init option instead.
Without this update, it won't trigger the pop up when you focus on the visual tab for Quiz Outcomes. Otherwise it should still work fine (and will still trigger when you click the ... as well).
=> Move "add focus events" logic for wysiwys to domjs

js/formidable_admin.js
Requires https://github.com/Strategy11/formidable-pro/pull/3838
If the versions get out of sync, the scale fields won't update live in the builder. I think that's a fine price to get rid of the code where it doesn't belong.
=> Remove builder update js for scale fields

js/admin/embed.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3852
Since these are settings now, it make sense not to have the options set by default in the embed examples since they override the setting. It seemed to confuse a customer, and I think we can avoid future support tickets by having it rely on the options in settings by default.
=> Remove title and description options from embed examples

classes/controllers/FrmFormActionsController.php, classes/controllers/FrmHooksController.php, js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3841 and Fixes https://github.com/Strategy11/formidable-pro/issues/3850
Its a bit tricky to find an ideal solution for this because sending an html to tinymce editor parses it and create DOM element (table in default-html case) and the browser auto fix changes the html which in unintended side effect. This update avoids that though and is backward compatible.
=> Issue 3841

classes/controllers/FrmFormActionsController.php, classes/controllers/FrmHooksController.php, tests/emails/test_FrmEmail.php
This update just uses `wpautop` to replace double line breaks with paragraphs for HTML emails.
=> replace newline with <br>

classes/helpers/FrmFormsHelper.php, classes/models/FrmApplicationTemplate.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3857
I'm just including a check against `FrmFormsHelper::ignore_template_categories` which is used for this with other templates already.
**Before**
**After**
=> Exclude license types from application categories

css/frm_admin.css, js/formidable_admin.js
With this update the dragged item no longer "clones". It now always uses the "frmbutton" look for new fields. For a field group, it says "Field Group" instead.
@stephywells @srwells Is this what you had in mind? Ignore the code for now. It's still in a prototype stage.
I'm also cleaning up some styles a bit.
For now I'm using the row layout icon for field groups. Trying to get a field count is more difficult than it should be at the moment.
=> New draggable helper function

classes/views/frm-form-actions/_email_settings.php
Jonathan mentioned to me that he's seen a few tickets so far that has requested to option to turn off the new rich text emails.
It isn't completely clear why, but I know some people actually have 99+ email actions, and loading TinyMCE for all of those would probably be a bad idea, so I can understand some cases when it makes sense.
Example snippets:
```
add_filter( 'frm_rich_text_emails', '__return_false' );
add_filter( 'frm_rich_text_emails', 'disable_rich_text_email_for_specific_action', 10, 2 );
add_filter( 'frm_rich_text_emails', 'disable_rich_text_email_for_specific_form', 10, 2);
function disable_rich_text_email_for_specific_action( $rich_text_emails, $args ) {
$target_action_id = 2381;
if ( $target_action_id === $args['form_action']->ID ) {
$rich_text_emails = false;
}
return …
```
=> New filter "frm_rich_text_emails"

classes/controllers/FrmFormActionsController.php, classes/controllers/FrmHooksController.php, classes/models/FrmEmail.php, tests/emails/test_FrmEmail.php
After merging https://github.com/Strategy11/formidable-forms/pull/927 and https://github.com/Strategy11/formidable-forms/pull/928 I have another thought.
The filter is already in lite so it makes sense to just make it part of `set_message`. We don't want to always use a hook, just when we need to.
@AbdiTolesa Do you see any issues with my update? I figured `html_entity_decode` only needs to be called for non-plain text so I moved it into the one condition.
I also moved it higher, to the top. I don't think we want to call `html_entity_decode` on any form data. That could be problematic. Ideally we could avoid this.
That should be fine right?
And do you have any ideas how it could work without the encoded data? I tried it out myself and I see why it's complicated. So if this is the best we …
=> No more hooks for issue 3850

css/frm_admin.css, js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3175
The drag/drop code has been rewritten to work better with sections and field groups.
This also fixes a bug with deleted groups. When sections were deleted, the children fields weren't also being deleted when using the delete group option.
And it fixes a couple of items from https://github.com/Strategy11/formidable-pro/issues/3118 including:
- "I added a summary field and the grouping that happened is odd. It should wrap the page break and the summary separately."
It also appears to resolve this issue I can appear to replicate on master when I drop a field into a row really quickly. It won't sync my layout but will set the layout class value to a double class like `frm6 frm6`, looking like this as a result:
**Recording** …
=> Replace sortable with draggable

css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/3870
The tooltip is flickering when the pointer is hovering on the tooltip. This is happening because the item triggering the tooltip is covered by the tooltip in some cases because there isn't enough space for it to fit normally, cancelling the hover event on the target element.
=> Ignore pointer events on tooltips

classes/helpers/FrmXMLHelper.php
I tried to import a very large XML file to test an issue on a customer's website. Around 250MB.
That didn't work out very well at first. I hit this `parser error : internal error: Huge input lookup` error.
**Before**
**After**
`loadXML` has a second parameter `$options`. It accepts constants from https://www.php.net/manual/en/libxml.constants.php
I've added two for now. It should optimize it, and allow for huge files now.
>  LIBXML_COMPACT (int)
>     Activate small nodes allocation optimization. This may speed up your application without needing to change the code. 
> LIBXML_PARSEHUGE (int)
>     Sets XML_PARSE_HUGE flag, which relaxes any hardcoded limit from the parser. This affects limits like maximum depth of a document or the entity recursion, as well as limits of the size of text …
=> Add LIBXML_COMPACT | LIBXML_PARSEHUGE options to loadXML function call

css/frm_admin.css, js/formidable_admin.js
- It was possible to drag a new field into a field group with a page break or a hidden field. I'm preventing this the other way (no adding a new page break or a hidden field to a group), but missed this check on the other end.
- Steve commented about issues with dragging. It looks like cursorAt doesn't really sync with scroll events. I've fixed this with a `transform: translateY( offset )` style that calculates based on the container's scroll position.
- I swapped the cursor setting to the JavaScript and removed it from CSS. I didn't realize `cursor` was a draggable setting until reading more into the documentation today.
**Before**
**After**
=> Drag and drop enhancements

js/formidable.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3856
I looked at the original suggestion, and the suggestion of adding a `-1` tabindex to the input is the best solution I can think of to handle this issue.
I figure a bot might be more likely to check for something like `tabindex="-1"` so I put it in an additional event listener first so it only happens if it detects a tab press.
=> Make honeypot field untabbable after first tab press

css/frm_admin.css
Looking at our full screen code I noticed "styles2" being referenced in a few places. I eventually figured out that's there's a "Forms" link from the Appearance menu item that uses this.
I noticed that there's still an old WP 5.7+ bug here on this page because the CSS was only targeting the one page. https://github.com/Strategy11/formidable-forms/pull/361
It seems like no one may really use this page if this hasn't come up in support after all this time. Do we actually think people are visiting this page? Do we track that? It may make sense to remove the secondary URL.
=> Do not hide update button on styles2 page

classes/controllers/FrmAppController.php, classes/controllers/FrmStylesController.php, classes/helpers/FrmAppHelper.php
Fixes https://github.com/Strategy11/formidable-views/issues/347
I refactored it a bit as well. Having this check for `self::is_admin_page( 'formidable-styles' ) || self::is_admin_page( 'formidable-styles2' )` everywhere felt problematic so I moved that into a new function that describes that's really going on because I wasn't even aware of this secondary URL in the theme menu. And most others must not be either if the update button was missing all of this time (see https://github.com/Strategy11/formidable-forms/pull/947 😅).
=> Stop treating views index with no filtered form ID as full screen

classes/helpers/FrmXMLHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3866
I looked at a few other things before I realized this was just a shortcode mistake. I always mix this shortcode order up because it doesn't start with frm like everything else 😅.
=> Fix shortcode typo in strpos check when importing views and pages

classes/controllers/FrmEntriesController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3880
But I also logged a new issue https://github.com/Strategy11/formidable-pro/issues/3886. I don't think this page should exist at this URL endpoint in the first place as it's problematic and causes issues like this one.
That's a larger fix though so I figure I'd still commit this fix first for now.
=> Hide screen options on entry duplicate action

classes/helpers/FrmAppHelper.php, classes/helpers/FrmCSVExportHelper.php, psalm.xml
Related ticket https://secure.helpscout.net/conversation/2022152412/111312
The XML file is included in one of Kristine's notes there. I'm not including it here because this is public.
This update works to remove a fatal error and a warning that I get when exporting this customer's entries as CSV.
I spent some time trying to debug the data coming through. As far as I can tell the CSV exports fine with these changes.
I ended up just adding type checks so the code won't break. I haven't really figured out the root of this issue. But I don't know if it's worth the effort either.
> PHP Fatal error:  Uncaught Error: [] operator not supported for strings in .../plugins/formidable/classes/helpers/FrmCSVExportHelper.php:481
> [18-Oct-2022 19:26:44 UTC] PHP Warning:  foreach() argument must be of …
=> Only append to array, only iterate an array during csv export

classes/models/FrmEmail.php, tests/emails/test_FrmEmail.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3847
This PR fixes the issue of line breaks not being ouput in html emails because the email body is passed through `wpautop` function but the second parameter was set to false.
=> turn on $br param for wpautop function

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3860
It looks like text inputs with advanced option are injected into the DOM when form actions are loaded but textarea fields are already loaded in different places on page loads. It might make sense to leave the css style for textarea SVGs as is but fix these for text fields when form actions are loaded.
=> Fix text input advanced option button style

js/formidable.js
This is required for Stripe link to work. I need to hook into before the form clears so my Stripe elements don't get destroyed when the form submits.
This hooks in only on success so the error handling is still handled normally in lite. If an entry is created successfully and the `frm_trigger_event_on_submit` class name is set on the form, it will just call that and exit early.
=> Trigger event instead of continuing

classes/models/FrmEntry.php
Before:
When caching is turned on, the user_info was empty in some cases, including inside a view. The problem was that the FrmEntry::getAll function added to the cache for FrmEntry::getOne, but the query wasn't exactly the same. (it.* vs it.id, it.item_key, it.name, it.ip, it.form_id, it.post_id, it.user_id, it.parent_item_id, it.updated_by, it.created_at, it.updated_at, it.is_draft')
After:
Now if an entry is cached from the FrmEntry::getAll function, it will include "description" like the FrmEntry::getOne function.
=> Fix entry info when cached

css/frm_admin.css
Fix https://github.com/Strategy11/formidable-pro/issues/3896
I think adding extra class that doesn't load on form builder page makes sense to avoid styles that affects form builder page.
=> add extra class specific to entry page

classes/helpers/FrmCSVExportHelper.php
Related to https://github.com/Strategy11/formidable-forms/pull/945
With that update this unit test breaks in Pro. Instead I'm setting it to an array as it works with the test better this way.
```
1) test_FrmCSVExportHelper::test_prepare_csv_row_empty_fields_in_repeaters
empty fields in repeaters are not exporting in the proper order
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'"Text Field #1","Text Field #2","","Text Field #4","","Text Field #6","Text Field #7","Text Field #8","Text Field #9"'
+'"Text Field #1","Text Field #2","","Text Field #4","Text Field #7","Text Field #6","Text Field #9","Text Field #8",""'
```
=> Fix failing pro unit test when calling fill_missing_repeater_metas

classes/models/FrmEmail.php, tests/emails/test_FrmEmail.php
Fix https://github.com/Strategy11/formidable-pro/issues/3889
This update avoids passing the whole html content through autop for html emails and just extracts the body content (if exists), wpply `wpautop` to it and then put it back into the original content.
Before:
```
<p><html><head></p>
<style>h3{text-decoration:underline;}.label{font-size:14px;font-weight:bold;padding-bottom:5px;}.value{font-size:17px;padding:0 0 0 5px;}.question{font-size:17px;padding:0 0 10px 0;}table{margin-bottom:60px;}tr,td{border:none;padding:6px;}.blue{background:#f0f8ff;}.grey{background:#f8f8f8;}</style>
<p></head><body><br />
LINE 1<br />
LINE 2<br />
</body></html></p>
```
After:
```
<html><head><style>h3{text-decoration:underline;}.label{font-size:14px;font-weight:bold;padding-bottom:5px;}.value{font-size:1 …
```
=> Issue 3889

tests/base/FrmUnitTest.php
Fixes a bug that was breaking the unit tests in stripe connect. If you pass a string for `$object` it will break when it called `getValue( $object )` because it is a string. If it's not an object, I pass null now.
> TypeError: ReflectionProperty::getValue(): Argument #1 ($object) must be of type ?object, string given
=> Only pass objects to reflection class getValue function calls

classes/controllers/FrmEntriesController.php, classes/controllers/FrmFormsController.php, tests/entries/test_FrmEntriesController.php
I was looking at the Support for a second in WordPress and noticed this issue https://wordpress.org/support/topic/frmentriescontroller-php/.
I haven't seen it come up in support but every time I see a fatal error with the stack trace I try to look at the code for a better idea.
This is simple to replicate with a basic snippet but I'm not sure how it comes up naturally. Possibly the option is a string, or another plugin is filtering the value and returning a string when it shouldn't.
```
add_filter(
'get_user_option_manageformidable_page_formidable-entriescolumnshidden',
function() {
return '';
},
9
);
```
I added a unit test that also covers this case. And I repeated the fix for the forms list which can have the same issue.
=> Avoid a fatal error if hidden columns are a string

images/icons.svg
I'm trying to work toward some better icon consistency as I work on the visual styler. The thicket pencil doesn't look great in the dropdown, but I think it may be worth avoiding adding another icon for the same thing when we can just replace our current one. It's a bit smaller and has less detail. I looked at the code and identified it's used in a few places. I think it looks okay.
I'm not sure if we want to just change all icons at once but I figure it's easier to do this one at a time since each one could be used in multiple places. Do we have updated icons for all of these in one of the designs?
It's also used when you edit a summary, but the SVG is separate code so it doesn't get updated with this update. If we want to change it there as well, it isn't difficult to update In Pro too. …
=> Update pencil icon

classes/models/FrmAddon.php, tests/misc/test_FrmAddon.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3947
@Crabcyborg Somehow, the unit test fails. The code before `$wp_roles->add_cap()` runs correctly (capabilities should be added to role `administrator`). But that method seems not to run. I printed some strings inside that method, but nothing showed in the terminal.
=> Fix plugin connection always falling

js/formidable_admin.js
Following up from https://github.com/Strategy11/formidable-forms/pull/987 to fix https://github.com/Strategy11/formidable-pro/issues/3024 and https://github.com/Strategy11/formidable-acf/issues/28
Complimentary pull request for clearing the field cache https://github.com/Strategy11/formidable-pro/pull/3948
=> Pass previous form id to frm update field after move and fix how previous section id is retreived

js/formidable_admin.js
This can be replicated by duplicating a form action that doesn't have a WYSIWYG editor.
=> Fix JS error when duplicating a form action

classes/helpers/FrmXMLHelper.php, classes/models/FrmDb.php
Fixes https://github.com/Strategy11/formidable-pro/issues/2242
This update fixes the issue of style not getting applied to the form it should on by trying the same action after the forms are imported plus getting around the cache issue in `FrmXMLHelper::update_custom_style_setting_on_import` when `FrmDb::get_var` is called clearing the cache saved with the key generated from the database query.
=> try to get style id from database even if name is numeric

classes/views/styles/_sample_form.php
As I'm working on the styler I've noticed some things in the sample form seem off, especially when compared side-by-side with the target form that doesn't have the same issues.
This update works to avoid both radio buttons being selected at the same time as the radio buttons have no `name` attribute, so they aren't connected.
This update only applies to the radio button in the styler's sample form **when Pro is not active**. For the same update in Pro, you also need https://github.com/Strategy11/formidable-pro/pull/3997 as Pro renders a different set of radio buttons inside of a repeater instead.
I pulled my solution from the dropdown HTML which handles this better.
```
<div class="frm_form_field form-field frm_half <?php echo esc_attr( $pos_class ); ?>">
<label for="field_wq7w5e" …
```
=> Prevent both radio buttons from being selected in sample form

classes/models/FrmStyle.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3964
This update just changes the default rootline size in the style setting page from `30px` to `24px`.
=> update default rootline size

classes/factories/FrmFieldFactory.php, tests/base/FrmUnitTest.php
This is required for https://github.com/Strategy11/formidable-pro/pull/3998 to pass unit tests.
XMLs are not a valid file type by default. But they're being uploaded to file fields here on import.
=> Allow XML files in file import in unit tests

css/frm_admin.css
I'm hitting this conflict when I try to preview the styler. In a normal preview this is useful.
@truongwp We only need this rule on the builder page, right?
=> Remove margin bottom from combo inputs container fields only on builder page

classes/models/fields/FrmFieldCaptcha.php
Related ticket https://secure.helpscout.net/conversation/2134228507/148173/
There was an extra double quote left from the hCaptcha update. This update removes the weird `"=""` you can see in this example.
=> Extra double quote in recaptcha field fix

classes/models/FrmApplicationTemplate.php, js/admin/applications.js
We talked about this in check-in this morning for the style templates modal. I figured I'd do the same here with Applications too.
=> Specify required license in applications modal

classes/controllers/FrmXMLController.php, classes/views/xml/import_form.php, js/formidable_admin.js, package-lock.json
Fixes https://github.com/Strategy11/formidable-pro/issues/4024
This update uses js to show or hide repeaters in the form export page based on the type of export selected. When CSV is selected, both forms and repeaters would be shown and the repeaters are hidden when XML is selected.
=> remove repeaters from exportable forms only for xml export

css/frm_admin.css, js/admin/dom.js
I think this may be the cause of https://github.com/Strategy11/formidable-pro/issues/3918 but I'm not 100% positive it's totally resolved. I think it may at least be related. When I noticed this behaviour in the styler, I linked to this issue as it seems similar.
With the visual styler I noticed that every time I closed a modal that the body became scrollable and I'd end up with a double scroll bar.
I had added this `overflowY: initial` rule when a modal closes previously to fix an issue with all modals scrolling to the top of the page which gets weird when you want to use the embed pop up anywhere where you've scrolled (like in the list of actions or in the list of forms).
I'm going with a less conflicting method now. Instead of changing the `overflowY` on the element directly, I added a …
=> Stop setting body to overflow-y: initial

classes/models/fields/FrmFieldType.php, classes/views/frm-fields/back-end/textarea-default-value-field.php
This is an extension from the previous update added to make sure paragraph is used instead of text field for RTE field default value setting when lite is updated but pro is not.
Before this update:
After:
=> fallback to textarea for rte default value field if pro is <= 5.5.6

classes/helpers/FrmAppHelper.php, js/admin/style.js, js/formidable_admin.js
Prevent movement when the form builder update button is clicked. This uses 'aria-busy' instead of changing the button label.
This also adds the loading spinner when the styler page is saved.
=> Fix buttons moving on save

js/admin/style.js
I noticed this was my session expired.
In the styler branch I wasn't getting these styles because I removed the `wp-core-ui` class.
This update just inserts the wp-core-ui class on the auth wrapper so the styles get applied properly.
**Before**
**After**
=> Fix close button on WP auth modal on styler pages

classes/models/FrmApplicationTemplate.php, classes/views/frm-forms/list-template.php, js/admin/applications.js
We talked about this in the meeting today. It's a pretty easy add. None of our templates are new enough to show it right now, but I used a period of 300 days to get a screenshot.
I went with 30 days. We use 10 for form templates. I don't know if we want to be more consistent. 10 seems pretty short. Since we don't add as many applications, a longer duration may make sense.
=> Add new tag to application templates

css/custom_theme.css.php
I'm seeing this with the "Sleek and Smooth" style.
Before:
After:
=> Prevent box shadow in RTE with rounded corners

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3917
This update fixes the broken autoscroll when dragging fields around a form with many fields that is scrollable. The form now auto scrolls up and down as you grab a field and move the cursor around the top/bottom inside the builder.
BEFORE:
https://user-images.githubusercontent.com/41271840/216592817-68b9ef47-69f4-440e-a8ef-49514b8530ee.mp4
AFTER:
https://user-images.githubusercontent.com/41271840/216592213-471b72b7-adfb-4cbf-9b88-63a9db862d1c.mp4
=> Fix broken auto scroll in form builder with scroll bars

classes/controllers/FrmAppController.php, css/frm_admin.css
This should make scrolling eaiser
Fixes https://github.com/Strategy11/formidable-pro/issues/3918
(I think)
=> Hide the WP admin menu and toolbar on full screen pages

classes/controllers/FrmAppController.php, classes/helpers/FrmHtmlHelper.php, classes/models/FrmStyle.php, classes/views/shared/toggle.php, psalm.xml, tests/styles/test_FrmStyle.php
This came up in support on Monday.
Someone had a `(rgba(...` style with that extra leading `(` on it. This caused the rest of the styles to break.
We already have some sanitizing in place to make sure colours are formatted as expected. But the checks weren't removing any excess brackets so I've updated this to make sure that it is always consistent.
I tried cleaning it up a bit more in a few other ways too. I noticed the same issue happened with an extra brace after the `rgb` like `rgb((` so I added some trimming to remove that as well.
And I added some other sanitizing. The r/g/b values now get passed through `absint` and the alpha goes through `floatval` so if any non-numeric values are used here, they'll get removed.
=> Add more sanitizing to styler colors

js/admin/settings.js, js/admin/style.js
Fixes https://github.com/Strategy11/formidable-pro/issues/4069
The styler still had the toggle accessibility code in it but it is no longer necessary as it looks like `settings.js` loads in the styler page by default. The two event listeners were both happening, causing it to toggle on/off simultaneously and remain unchanged.
Also I added a preventDefault to prevent the scroll behaviour.
=> Remove toggle accessibility code from styler

classes/models/FrmSettings.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4073
The defaults go through the same code that sanitizes. It led to this issue where my `false` default gets set to an empty string.
I intentionally want to support an empty custom CSS string without it forcing the old custom CSS, without needing to delete the old custom CSS (to be on the safe side in case there are issues like this that come up).
This update just makes sure that the `false` default isn't sanitized.
There may be issues though if someone had saved their global settings in v6.0 and saved an empty string for their custom CSS. Maybe we want to make a migration for that, but I fear a migration that changed global settings could have issues of its own. I noticed while testing that if I call `$frm_settings->store();` …
=> Stop sanitizing the custom CSS default

classes/views/shared/mb_adv_info.php, psalm.xml
Related ticket https://secure.helpscout.net/conversation/2157723026/151310/
There was an extra comma here. This only breaks in versions of PHP 7.2 and lower.
I spent some time trying to add a rule for this with phpcs, psalm, or phpstan, but it doesn't really appear to be easy to check for with any of these. Maybe with the PHPCompatibilityWP in phpcs but I don't think it's worth pulling that in just for a comma check.
But in that process, I removed some Psalm exceptions from view files. It was previously ignoring the files entirely. Now it's just ignoring specific rules.
=> Remove extra comma in mb adv info view

classes/helpers/FrmStylesPreviewHelper.php, js/admin/style.js
Fixes https://github.com/Strategy11/formidable-pro/issues/4072
The old code for this was fine because it was for the sample form where this setting doesn't exist. I hadn't considered this field setting.
This update adds a class to any field with the default set, and only those get changed now.
=> Avoid changing the label position container classes if a field does not use the default

css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/4079
A quick fix for making sure the sidebar is wrapped up into the next line.
BEFORE:
NOW:
=> add style that forces flex wrap

js/formidable_admin.js
Part of https://github.com/Strategy11/formidable-pro/pull/4085
Without this update the visual tab in the preview won't sync when you change the default value of the field.
=> Trigger change events for wysiwyg textareas

classes/controllers/FrmAppController.php, classes/views/shared/admin-header.php, classes/views/styles/_style-preview-container.php, classes/views/styles/_styles-list.php, classes/views/styles/show.php, css/admin/style.css, css/frm_admin.css
Use the WP full screen setting for full pages
Use the css from WP for full screen pages
Use more consistent classes for two column scrolling layout
Include frm_form_nav container for layout in a view without a form selected
To test:
- Go to edit a post and click the ... and turn off fullscreen mode
- Check all the full screen pages to make sure they look and scroll correctly
- Click the collapse the admin menu and check all the pages again
- Check on different screen sizes
- Go back and turn on fullscreen mode, and check all full screen pages again
=> Use the WP full screen setting for full pages

classes/models/FrmFormAction.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3991
It looks that there is a default limit (99) defined for the number of actions triggered in `FrmFormAction::prepare_get_action` which prevents those extra actions to be triggered even if `frm_${action}_action_options` filter is used to extend the number of actions added in a given form.
I imagine two alternative solutions.
First, it looks we actually can use the action's `action_options['limit']` value instead to account for the new limit of actions as in this PR.
If we don't want to do that, I think we need to provide `$args['limit']` value everywhere `FrmFormAction::get_action_for_form` is called so that we override the default limit mentioned above.
=> remove default limit on the number of actions triggered

classes/models/FrmFormAction.php
The unit tests were breaking in Pro. Posts have a limit of 1. To be on the safe side, I added a check to only change the limit if the option limit is greater than 99.
> There was 1 failure:
> 
> 1) test_FrmProEntriesHelper::test_search_form_posts
> Failed asserting that false is true.
> 
> /tmp/wordpress/src/wp-content/plugins/formidable-pro/tests/entries/test_FrmProEntriesHelper.php:712
> /tmp/wordpress/src/wp-content/plugins/formidable-pro/tests/entries/test_FrmProEntriesHelper.php:675
=> Only use action option limit if greater than 99

classes/views/styles/_styles-edit.php
This moves the hidden div so the flex css will apply to the preview section
Before:
After:
=> Fix https://github.com/Strategy11/formidable-pro/issues/4100

classes/controllers/FrmFormsController.php, classes/helpers/FrmOnSubmitHelper.php, tests/forms/test_FrmFormsController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4101
My last fix added `$method = 'message'` to show the default message if no actions match. But it breaks the form that hasn't been migrated. I added a check if the form hasn't been migrated there.
=> Fix confirmation action is forced to message

classes/controllers/FrmFormsController.php
This fixes the error in the pro unit tests with an empty url when redirecting after update
=> Pass the event name for redirects too

css/frm_admin.css
Fixes https://github.com/Strategy11/formidable-pro/issues/4092
Just a small fix to make sure the email message text area is easily expandable.
BEFORE:
NOW:
=> add right margin to fields box

js/formidable_admin.js
We don't need this anymore. It's no longer called since v6.0
=> Remove unused function "showFormMessages"

classes/views/frm-fields/back-end/field-captcha.php
Related ticket https://secure.helpscout.net/conversation/2172643190/153587
If you have a captcha field in your form but no captcha keys set, this error would trigger when Pro isn't active.
=> Do not use pro app helper for captcha icon note

classes/helpers/FrmFormsListHelper.php, classes/views/frm-forms/list.php
Fixes https://github.com/Strategy11/formidable-pro/issues/3824
This update allows searching forms in the selected category. In addition it would update the count of forms based on the search result.
_Searching in Published:_
Before search:
After search:
**BEFORE**
**NOW**:
_Searching in Trash:_
Before search:
**BEFORE**
After search (switches back to Published forms):
**NOW**
=> Use active form type when searching forms

classes/controllers/FrmFormsController.php
In v6.0, we used Confirmation code in Lite plugin to handle updating entry. Entry updating uses `show_title` and `show_description` instead of `title` and `description`. So we must handle them in Lite plugin.
=> Handle show_title and show_description in form display args

classes/views/frm-entries/list.php
I discussed this the other day in Slack.
We're showing the import/add new buttons on the Entries page when Pro is inactive but the add new button does nothing as it links to a page that we only support in Pro.
**Before (or when Pro is installed)**
**After (when Pro is not installed)**
=> Only show add new entry when pro is installed

css/frm_admin.css
German translations can be downloaded from here and dropped in the `/languages/` folder.
[formidable-de_DE.zip](https://github.com/Strategy11/formidable-forms/files/10912381/formidable-de_DE.zip)
A long German translation in buttons would cause them to break into multiple lines. I noticed this while looking at a customer's website in support the other day.
I extended this `max-width` before but this was before we added the embed button so it needs significantly more space.
I don't think we really need a `max-width`.
**Before**
**After**
=> Remove max width from #frm_publishing button wrapper element

stubs.php
The Problem: This allows calls to external code to get past without a class_exists/is_callable first.
Ideally, we should use hooks instead of calling FrmPro classes directly. But this is a start to prevent more unwanted Pro functions from being called in Lite.
=> Remove a few stubs we don't need in lite

css/frm_admin.css, js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/4087
This PR is aimed at making collapsed sections duplicatable, fix style issues in the context dropdown and also show the number of fields to be deleted in the confirmation box that is shown when trying to delete a section.
BEFORE:
NOW:
[issue_4087.webm](https://user-images.githubusercontent.com/41271840/222132436-603ba44f-4a68-4856-af69-dc4cdf2e77fc.webm)
=> Enable duplication of collapsed sections

classes/helpers/FrmFieldsHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4096 when Pro isn't active.
When Pro is active, https://github.com/Strategy11/formidable-pro/pull/4147 is required.
=> Skip any shortcode option that uses =0

classes/controllers/FrmAppController.php, classes/helpers/FrmFieldsHelper.php, classes/models/FrmForm.php, deprecated/FrmDeprecated.php
This update restores functions that are still referenced in the API add on, locations, and highrise that were removed in https://github.com/Strategy11/formidable-forms/pull/1117/files
=> Restore some deprecated functions used in addons

classes/helpers/FrmAppHelper.php, tests/misc/test_FrmAppHelper.php
Related ticket https://secure.helpscout.net/conversation/2189119190/155804/
Related update https://github.com/Strategy11/formidable-user-tracking/pull/24
Prior to this update `FrmAppHelper::human_time_diff( 0, 0 )` would return `53 years` as `$to` was "empty". I'm adding an exception for 0.
=> Support 0 for to value for human time diff function

js/admin/dom.js, js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/3962
The order of results is changed to Ascending from Descending but I don't believe out that is much important here or even better this way so I kept the solution as simple one liner to avoid extra DOM query but I can keep the order as before if needed.
In addition to that, I have now excluded the default `Ready Made Solution` and `Check all applications` texts from being accounted for when searching.
**BEFORE**:
Searching using keyword `Rea`:
**NOW**:
Searching using keyword `Rea`:
=> append template search results after categories list

bin/zip-plugin.sh
This shouldn't be used directly. The zip still includes the minified version.
=> Exclude admin js file from hubspot zip

js/admin/dom.js
Related ticket https://secure.helpscout.net/conversation/2196994272/156886/
The multiselect dropdowns (used for field visiblity settings, and global permission settings, and registration action role settings) wouldn't state to a screen reader whether the nested input was checked or not.
I'm fixing this with a `role="checkbox"` attribute and syncing the value of `aria-checked` when the dropdown shows and when the value changes.
=> Use checkbox role for multiselect buttons and add aria checked attribute

bin/zip-plugin.sh
I've been modifying `-x "*[^(dompdf)]/vendor/*" \` to exclude `[^(dompdf)]` every time I pack a zip for Pro.
I figured out an easier way to exclude the root vendor folder while keeping the PDFs vendor folder inside of the `dompdf` folder, using the `$source` variable that matches the current folder name.
=> Only exclude $source/vendor from zip

classes/controllers/FrmFormsController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4156
I also reordered the checks in the get met actions method. Previously, if the first redirect action is invalid, all remaining redirect actions are skipped.
=> Apply frm_redirect_url filter before checking invalid action

css/frm_admin.css
Before:
https://github.com/Strategy11/formidable-forms/pull/1135#issuecomment-1497670828
After:
This css overrides this in the wp forms.css:
```
::-webkit-datetime-edit {
line-height: 1.85714286;
}
```
@Crabcyborg is this too late to be merged?
=> Set the date fields the same height in the reports filtering

classes/controllers/FrmFormsController.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4174
I ran `FrmEntriesController::prepare_redirect_url` before processing shortcodes, so shortcode tags are encoded.
=> Fix shortcodes aren't parsing in redirect URL

classes/helpers/FrmStylesHelper.php
I stumbled by this code and noticed that `success_bg_color` was in this array twice.
=> Remove duplicate style setting key

classes/helpers/FrmXMLHelper.php, tests/xml/test_FrmXMLHelper.php
I was looking in HelpScout for errors and noticed a pretty common pattern with import errors.
It's common enough that there's information on how to avoid it in the documentation https://formidableforms.com/knowledgebase/import-forms-entries-and-views/#kb-simplexml_parse_error
In a few cases the customers included XML import examples
In https://secure.helpscout.net/conversation/2061631158/116223 it's because of an extra `<meta name="generator" content="Equity 1.7.13" />` tag added by the Equity WP theme. I was able to find the problematic code here in GitHub https://github.com/idxbroker/Equity-Framework
```
add_filter( 'the_generator', 'equity_generator' );
function equity_generator( $generator ) {
$generator .= "\r\n" . '<meta name="generator" content="' . PARENT_THEME_NAME . ' ' . …
```
=> Fix common XML import issues

tests/base/FrmUnitTest.php, tests/misc/test_FrmAddon.php, tests/misc/test_FrmCSVExportHelper.php
We don't ever run these versions anymore.
=> Stop checking for php 5.x in tests

js/formidable_admin.js
Fixes https://github.com/Strategy11/formidable-pro/issues/4176
The banner is being added in the proper place, then this JavaScript is breaking it.
Do we need this anymore @stephywells? It looks like it was added in v5.4.3 but the v6.0 changes appear to break it.
=> Remove moveTopBanner function

classes/controllers/FrmStylesController.php, classes/views/styles/_style-preview-container.php, css/custom_theme.css.php
Following up from Steph's comment here https://github.com/Strategy11/formidable-forms/pull/1141#pullrequestreview-1380009049
This update doesn't include https://github.com/Strategy11/formidable-forms/pull/1141. It's easier to test this when you can still break it with `(` or `)` like in my example here,
I added a referer check so it wouldn't interfere with the front end. It also only happens through the `frmpro_css` action but that is the fallback for when the CSS file doesn't work.
@stephywells What do you think we should use for the warning's message body? I put something but it could probably use more information.
=> Add a warning to the styler to a detect a broken style

classes/helpers/FrmAppHelper.php, tests/misc/test_FrmAppHelper.php
I noticed this came up a second time in support. It shouldn't really be possible as the same file that calls this clip function is also the file that has the function that supposedly doesn't exist. But to avoid it in the future, I'm adding a small `is_callable` check.
I also added a unit test.
First related ticket back from November last year https://secure.helpscout.net/conversation/2056768903/115574
And second related ticket that came up in March last month https://secure.helpscout.net/conversation/2183441439/155072/
=> Check if clip echo function is callable

classes/controllers/FrmEntriesAJAXSubmitController.php
Fixes https://github.com/Strategy11/formidable-stripe/issues/220
Fixes https://strategy11.slack.com/archives/CJFQ599V5/p1681620515610519
Improves upon https://github.com/Strategy11/formidable-forms/pull/1161 by fixing the issue in both Lite and Pro to avoid multiple patch releases and duplicate code.
It's also a private function so it will be easy to remove if WooCommerce fixes this on their end in the future.
=> Fix woocommerce conflict in one place

classes/helpers/FrmXMLHelper.php
In this pull request, we are improving the readability of import XML error messages by combining WP_Error details with the message.
https://github.com/Strategy11/formidable-pro/issues/4189
---
=> Improve Readability of Import XML Error Messages

classes/controllers/FrmAppController.php, classes/controllers/FrmHooksController.php, classes/helpers/FrmAppHelper.php, classes/views/shared/errors.php, css/frm_admin.css, js/formidable_admin.js, tests/misc/test_FrmAppHelper.php, tests/misc/test_FrmAppHeperAjax.php
This PR introduces dismissible warning message functionality. It adds the `FrmAppHelper::add_dismissable_warning_message` method, which can be used to easily display dismissible warning messages.
https://github.com/Strategy11/formidable-pro/issues/4134
=> Add Dismissible Warning Message Functionality

css/custom_theme.css.php, css/frm_blocks.css
With this PR, we strengthen the CSS selector for the repeater button color in Gutenberg to ensure the correct text color is displayed.
https://github.com/Strategy11/formidable-pro/issues/4131
<kbd>
</kbd>
<kbd>
</kbd>
=> Fix: Dark text on Repeater buttons in Gutenberg block preview

classes/models/FrmForm.php, classes/models/FrmOnSubmitAction.php, js/formidable_admin.js, tests/forms/test_FrmOnSubmitAction.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4148
=> Fix Confirmation actions don't enforce sanitize_url option in shortcodes

classes/helpers/FrmXMLHelper.php
This PR enhances the error message displayed when attempting to import XML files without the DOMDocument class installed on the server, providing a more user-friendly description and a link to the documentation for troubleshooting.
https://github.com/Strategy11/formidable-pro/issues/4207
In order to install XML, your server must have DOMDocument installed. Follow our documentation on [Importing Forms, Entries, and Views](https://formidableforms.com/knowledgebase/import-forms-entries-and-views/#kb-your-server-does-not-have-xml-enabled) to ensure DOMDocument is properly set up and XML support is enabled.
=> Enhance error message for missing DOMDocument during XML import

js/formidable_admin.js
In this pull request, we've updated the makeDraggable function to prevent elements with the .frm_show_upgrade class from being draggable.
https://github.com/Strategy11/formidable-pro/issues/4201
=> Prevent Dragging of Disabled Field Types

classes/helpers/FrmEntriesListHelper.php, tests/entries/test_FrmEntriesListHelper.php
This doesn't totally fix the root of the issue in https://github.com/Strategy11/formidable-pro/issues/3986 but it helps to avoid the fatal error if you used "description" as a field key.
I don't really understand why `'description'` is here in the switch/case statement. We don't include "Entry Description" as one of our options. It doesn't work here if it's an array, which is common as we store other data in this like user journeys.
@stephywells Do you see an issue with removing `description` from the switch/case here? When I do, the description uses its meta normally and doesn't cause the fatal error,
=> Stop trying to display entry descriptions in the entry list

classes/models/FrmAddon.php
See more detail here about how to test:
https://github.com/Strategy11/formidable-pro/issues/4219
This only updates the license activation process. This adds a block to wait 2 minutes before trying to activate the same license again.
=> Include the license in the POST request for dynamic urls

js/admin/embed.js
This pull request addresses the issue of the autocomplete dropdown being cut off within the embed modal when picking existing pages.
https://github.com/Strategy11/formidable-pro/issues/4224
https://qa.formidableforms.com/sherv/wp-admin/admin.php?page=formidable&frm_action=edit&id=1
1. Navigate to WP Admin > Formidable > Forms
2. Open an existing form or create a new one
3. Click on the Embed button in the top navigation
4. Click on "Select Existing Page"
5. Note: Make sure you have at least 51 pages (this enables the page autocomplete feature)
=> Fix: Autocomplete Dropdown Cutoff Issue in Embed Modal When Picking Existing Pages

classes/models/FrmFormAction.php
Noticed this. I don't think it benefits anyone having this here.
Confirmed in check-in that there isn't any reason for it.
=> Remove confusing useless comment floating in FrmFormAction.php

classes/views/xml/import_form.php, js/formidable_admin.js
Fix https://github.com/Strategy11/formidable-pro/issues/3715
Just adding a checkbox that allows selecting/deselecting forms for in the export table.
=> add 'Select All' button to forms export

css/frm_admin.css
This pull request addresses an issue where extra white space was present to the left of the admin page content on small screens.
https://github.com/Strategy11/formidable-pro/issues/4217
https://qa.formidableforms.com/sherv4/wp-admin/admin.php?page=formidable&frm_action=settings&id=1
1. You need to disable fullscreen mode. Check out https://github.com/Strategy11/formidable-pro/issues/4227
1. Open the `WP Admin > Formidable` page on a small screen device (smaller than `960px` and bigger than `850px`)
2. Confirm that the extra white space to the left of the page content has been removed.
=> Fix: Remove Extra Whitespace on Admin Page Content for Small Screens

css/frm_admin.css
This PR enhances the field buttons' appearance and usability in the form builder by extending their width to full size and standardizing the icon sizes for a more consistent look.
https://github.com/Strategy11/formidable-pro/issues/4206
https://qa.formidableforms.com/sherv/wp-admin/admin.php?page=formidable&frm_action=edit&id=1
1. Navigate to WP Admin > Formidable > Forms
2. Open an existing form or create a new one
3. Locate the "Add Fields" section in the sidebar to view the implemented changes
=> Enhance Field Button Width and Standardize Icon Sizes in Builder

css/frm_admin.css
This PR addresses the overflow issues found on the add-ons list page when viewed on smaller-width screens with an excessive amount of text.
https://github.com/Strategy11/formidable-pro/issues/4221
https://qa.formidableforms.com/sherv2/wp-admin/admin.php?page=formidable-addons
=> Fix: Resolve overflow issues on add-ons list page for smaller screens

classes/views/frm-forms/add_field.php, css/frm_admin.css
This PR resolves the styling issues present in the collapsed section. The specific areas of improvement include:
1. The misplaced collapse/expand toggle is now switched to an SVG and CSS is used to manage its rotation.
2. An extra border that was overlapping with `:after` has been removed to clean up the UI.
3. Excessive space between "Section" and "Collapsed" has been addressed.
https://github.com/Strategy11/formidable-pro/issues/4099
https://qa.formidableforms.com/sherv3/wp-admin/admin.php?page=formidable&frm_action=edit&id=1
1. Go to `WP Admin > Formidable`.
2. Open an existing form or create a new one.
3. Add a `section` field.
4. Verify that all styling issues have been properly addressed.
=> Fix Collapsed Section Styling Issues

classes/models/FrmForm.php, tests/forms/test_FrmForm.php
This is triggered by my "(no title)" form in PHP 8.2.
=> Check if result is null when getting form name

classes/controllers/FrmFormsController.php
Related ticket https://secure.helpscout.net/conversation/2256620330/163168/
This avoids the fatal error. I don't think we need to support form name shortcodes in an array that comes through this function.
=> Add a string check to replace_form_name_shortcodes function

classes/views/frm-forms/add_field.php, js/formidable_admin.js
This is required to make the Show password option live update. Without this update, users must update the form to see the change in the form builder, and the confirm password field won't have that button.
=> Add frm_conf_input_backend filter and show password live update JS

css/frm_admin.css, js/formidable_admin.js
This PR involves the removal of the back button from the 'Leave your email address' modal. The proposed changes are part of the Interface Reviews conducted by Razvan.
https://qa.formidableforms.com/sherv3/wp-admin/admin.php?page=formidable&triggerNewFormModal=1&free-templates=1
1. Navigate to `WP Admin > Formidable > Inbox`.
2. Click on the `Get Now` button in the `Get 10+ Free Form Templates` message.
3. Verify that the back button has been removed.
=> Remove Back Button from 'Leave your email address' Modal

.github/workflows/phpunit.yml, tests/base/FrmAjaxUnitTest.php, tests/base/FrmUnitTest.php, tests/base/frm_factory.php
I'm just adding a new factory class that extends the WordPress one so I can define the factory properties to bypass the dynamic property deprecation messages.
Since it's working in PHP 8.2 I added a few more workflow PHP versions so we're covering PHP 8.0, 8.1, and 8.2.
> Deprecated: Creation of dynamic property WP_UnitTest_Factory::$form is deprecated in .../formidable/tests/base/FrmUnitTest.php on line 57
> Deprecated: Creation of dynamic property WP_UnitTest_Factory::$field is deprecated in .../formidable/tests/base/FrmUnitTest.php on line 58
> Deprecated: Creation of dynamic property WP_UnitTest_Factory::$entry is deprecated in .../formidable/tests/base/FrmUnitTest.php on line 59
=> Fix PHP 8.2 deprecations

classes/controllers/FrmCronController.php, formidable.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4292
This small update just makes sure the events scheduled in lite are unscheduled when it is deactivated!
This could be tested with any cron management plugin. I'm using Advanced Cron Manager.
=> remove crons when lite is deactivated

classes/views/frm-fields/front-end/dropdown-field.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4286
The "other" option should be now selected when editing an entry either in front/back end, if it has been selected when submitting the entry.
=> make sure  param to FrmHtmlHelper::echo_dropdown_option is always boolean

classes/views/frm-forms/_publish_box.php, js/formidable_admin.js
This Pull Request delivers a solution for the JavaScript errors that emerged when the preview dropdown was engaged too swiftly.
https://github.com/Strategy11/formidable-pro/issues/4109
For a detailed guide on how to reproduce this issue, please refer to the video below:
https://www.loom.com/share/c70cc31f5daa49b6b4f97ca74f328d22
Kindly follow these steps to verify that the issue has been adequately addressed.
=> Resolved JavaScript Errors Triggered by Rapid Preview Dropdown Interactions

css/frm_admin.css, js/formidable_admin.js
This PR introduces two enhancements:
The first is synchronizing the visibility of category headings with their associated fields' search results. When all fields under a heading are hidden due to not matching the search criteria, the category heading will also be hidden.
The second enhancement addresses an issue where advanced fields were always shown in the field list, regardless of the search value. With the changes introduced in this PR, advanced fields won't show by default, they will only appear if the search string contains the field name.
https://github.com/Strategy11/formidable-pro/issues/4283
https://github.com/Strategy11/formidable-pro/issues/4289
https://qa.formidableforms.com/sherv5/wp-admin/admin.php?page=formidable&frm_action=edit&id=1
1. Navigate to `WP Admin > Formidable`. …
=> Enhancement of Category Headings Visibility and Search Results

classes/helpers/FrmXMLHelper.php
Fixes https://github.com/Strategy11/formidable-pro/issues/4321
This update makes sure a trashed form is permanently deleted before import.
Before:
After:
=> permanently delete trashed form before xml import

js/formidable_admin.js, js/packages/floating-links/config.js, js/packages/floating-links/s11-floating-links.js
Addressed the issue where floating links defined `__` as a global variable, introduced in a previous merge. I've restructured the code to minimize global exposure, ensuring that any global elements now have the "frm" prefix.
https://github.com/Strategy11/formidable-pro/issues/4346
- Install and activate "Formidable Google Sheets".
- Ensure you're using the stable version.
- [Link to the latest version](https://github.com/Strategy11/formidable-googlespreadsheet/tree/v1.0.1)
- Navigate to "WP Admin > Formidable > Global Settings".
- Open the browser's Inspect Element and ensure the `Uncaught SyntaxError: Identifier '__' has already been declared` error no longer appears.
=> Fix Global Variable Issue with Floating Links

classes/views/frm-forms/settings-advanced.php
I just came across this code. It's outside of the range now so I'm removing this tip.
=> Remove tip for confirmation actions

classes/models/FrmFieldFormHtml.php
Related update https://github.com/Strategy11/formidable-forms/pull/1199
Based on this comment https://github.com/Strategy11/formidable-forms/pull/1199#issuecomment-1660288775
I'm trying to match the tabindex on https://github.com/Strategy11/formidable-pro/pull/4249
=> Add tabindex to radio groups

css/frm_admin.css
Related update https://github.com/Strategy11/formidable-payments/pull/43
Following Truong's idea this update allows us to show the overlay when confirming deleting a payment in a way that doesn't require deprecations and it works for both the Stripe add on and the Stripe Lite update.
=> Add overlay css for payments page

classes/controllers/FrmSimpleBlocksController.php
Based on Steph's request: https://github.com/Strategy11/formidable-forms/pull/1217#discussion_r1279662745
=> Change modal in-product education link

classes/views/frm-entries/show.php
In this PR, we've added the 'next' and 'previous' buttons to the page where you view entries.
https://github.com/Strategy11/formidable-pro/issues/4199
https://qa.formidableforms.com/sherv/wp-admin/admin.php?page=formidable-entries&frm_action=list&form=1
1. Go to `WP Admin > Formidable`.
2. Choose an existing form or make a new one.
3. Go to `Entries` using the top navigation menu.
4. Open an entry (Click on the `View` button). You should see new buttons for navigating entries.
=> Addition of Entry Navigation Buttons on the "View Entry" Page

.gitignore, classes/helpers/FrmAppHelper.php, classes/helpers/FrmFieldsHelper.php, classes/views/frm-fields/back-end/inline-modal.php, formidable.php, js/admin/dom.js, js/formidable_admin.js
This PR includes:
- Ignore `formidableforms1.css` file.
- Improve `dom.tag()` to accept a string as one of children.
- Add JS action when show inline modal (in the backend).
- Add `inside_class` to the inline modal args (to fix the ugly styling of nested modals inside the `<div class="inside">` tag).
- Bump version for testing.
=> Required for Date calculation

classes/controllers/FrmAppController.php, classes/controllers/FrmHooksController.php, classes/views/shared/admin-footer-links.php, css/frm_admin.css
This PR introduces footer links. This enhancement ensures users no longer need to rely solely on the floating icon, which fades away upon scrolling.
https://qa.formidableforms.com/sherv2/wp-admin/admin.php?page=formidable
https://github.com/Strategy11/formidable-pro/issues/4350
1. Navigate to `WP Admin > Formidable`.
2. Check anywhere other than the builder pages and verify that the admin footer links have been added as depicted in the preview screenshot.
=> Added Footer Links for Improved User Accessibility

bin/zip-plugin.sh
I noticed this was getting included when I made a stripe release.
=> Exclude payments vendor folder from zip

.github/workflows/phpcs.yml
I noticed when reviewing another PR that there was a php 5.6 syntax error that didn't get caught. @Crabcyborg do you want to make any modifications to this workflow before we merge it?
=> Add phpcs check for php 5.6 and 8.1

css/frm_admin.css
Related update https://github.com/Strategy11/formidable-pro/pull/3829
This rule is really only intended for the builder page where the button is another style.
**Before**
**After**
=> Stop forcing white icons for repeater add buttons on the entry view page
